### ISSUE TITLE
css.selectors.is - Browser compatibility table out of date

### ISSUE THREAD

**Issue by stamminator** [mdn/browser-compat-data#10163]
The browser compatibility table section does not have the latest two stable releases of Chrome (at the time of this writing, that is v90). It also doesn't seem to have Chromium Edge represented in the list at all.

![image](https://user-images.githubusercontent.com/10633170/116477301-6b872f80-a84a-11eb-9805-8f2590165569.png)

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.is`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:is
* Report started: 2021-04-28T21:48:58.451Z

</details>

**Comment by vinyldarkscratch** [comment]
Is there a compatibility change between Chrome 88 and Chrome 90?  As opposed to CanIUse, our compatibility tables indicate the first version where the feature was implemented (or in some cases, the last version it was available in).  Thus, an "88" for Chrome means "this was implemented in Chrome 88 and is available in all following versions."

We also don't represent Chromium Edge as a separate browser from the original Edge, as Microsoft themselves do not.  The data is, however, a bit off for Edge, so that'll need to be resolved.

**Comment by stamminator** [comment]
🤦‍♂️ Sorry about that, not sure why I expected it to show later versions past the version in which it started being supported.

Thanks for the Edge fix though.

**Comment by queengooborg** [comment]
All good, haha!  Happens to the best of us.  😛
