### ISSUE TITLE
api.Element.afterscriptexecute_event - guessing IE is not supported

### ISSUE THREAD

**Issue by mollthecoder** [mdn/browser-compat-data#10298]
#### What information was incorrect, unhelpful, or incomplete?
The IE data is unknown
#### What did you expect to see?
No support.
#### Did you test this? If so, how?
I didn't test this but I'm sure i'm correct.

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.afterscriptexecute_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/afterscriptexecute_event
* Report started: 2021-05-05T15:43:41.929Z

</details>

**Comment by vinyldarkscratch** [comment]
Do you have any documentation or resources to back up your hypothesis?

**Comment by ddbeck** [comment]
On the MDN page for onafterscriptexecute, there's a link to [a demo](https://media.prod.mdn.mozit.cloud/samples/html/currentScript.html) (which actually tests the event, rather than the handler). I found it pretty easy to modify to run in IE, where it failed. I opened https://github.com/mdn/browser-compat-data/pull/10617 to fix this.
