### ISSUE TITLE
html.elements.meta.name.theme-color - New iOS, ipadOS and macOS offer support

### ISSUE THREAD

**Issue by JE4GLE** [mdn/browser-compat-data#10885]
New support for:
- Safari on macOS: Version 15.0 (17612.1.15.1.14)
- Safari on iOS: Version 15.0

Only works in dark mode with some colors, for example it works with #1976d2 but not with #ff7701.

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.meta.name.theme-color`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color
* Report started: 2021-06-08T20:05:39.818Z

</details>

**Comment by rhysforyou** [comment]
Another thing worth noting is that it seemingly only accepts hex codes for the colour.

**Comment by JE4GLE** [comment]
@rhysforyou Cannot confirm, I just tried it with rgb(100, 0 0) in Safari Version 15.0 (17612.1.15.1.14) on macOS and it worked just fine.

**Comment by rhysforyou** [comment]
@JE4GLE This was my mistake, what was actually happening was that Safari was ignoring the theme colour because it was too light, and I had my system set to run in dark mode. Safari will ignore theme colours if you're running dark mode and the colour is very light, or for certain colours that might conflict with things like the window controls.

**Comment by queengooborg** [comment]
This has been resolved in #10898!
