### ISSUE TITLE
javascript.builtins.WebAssembly.instantiate - Not working fully on Chrome

### ISSUE THREAD

**Issue by pjpmccarthy** [mdn/browser-compat-data#10896]
Chrome is not picking up the names of the external functions from the Rust code.
The EXACT same code works in Mozilla so Chrome is not compatible as the document claims.

rust
#[no_mangle]
pub extern fn add_one(x: u32) -> u32 ...

javascript
const { instance } = await WebAssembly.instantiate(bytes, { env: imports });
iStatus = instance.exports.add_one(2);

Uncaught (in promise) TypeError: instance.exports.add_one is not a function

**Comment by queengooborg** [comment]
The example linked on MDN Web Docs (https://mdn.github.io/webassembly-examples/js-api-examples/) seems to work fine in Chrome.  It looks like you are passing the `imports` into an `env` property, which is the incorrect way to pass in imports.

Unfortunately, since there isn't a complete code example that can be referenced, there's not much we can do to further research this.
