### ISSUE TITLE
api.Window.scrollTo - iOS Safari doesn't appear to support `{ behavior: 'smooth' }`

### ISSUE THREAD

**Issue by molovo** [mdn/browser-compat-data#11037]
#### What information was incorrect, unhelpful, or incomplete?

The browser compatibility for `Window.scrollTo` lists iOS Safari as supporting the `ScrollToOptions` parameter. The keys `left` and `top` within the object both work, but `behavior: 'smooth'` is ignored on iOS.

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.scrollTo`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo
* Report started: 2021-06-15T11:12:56.904Z

</details>

**Comment by vinyldarkscratch** [comment]
This is mentioned on the page for the options, see https://developer.mozilla.org/en-US/docs/Web/API/ScrollToOptions.  I'll admit it's not super clear from the page you're looking at, though, so I'll leave this open to help us come up with a better clarity solution.

**Comment by sirinejebari** [comment]
I am having the same issue. Anyone has an answer ?

**Comment by Kharacternyk** [comment]
Hi @queengooborg,
The link you have given appears to redirect to https://developer.mozilla.org/en-US/docs/Web/API/Window/scroll as of now, and that page does state that Safari on iOS supports the option since v14, which is not true even for v15. Perhaps the info about the incompatibility has disappeared along with the page about ScrollToOptions?
