### ISSUE TITLE
Labeling guidelines: Release notes for added features?

### ISSUE THREAD

**Issue by queengooborg** [mdn/browser-compat-data#11251]
Since the labeling guidelines have been developed and merged into `main`, I've been referring to them quite a bit when triaging new issues.  When looking at the guidelines for the `needs-release-note` PR, however, I was a little surprised to find one clause missing: added features.  While a newly added feature may not constitute a semver minor bump (or does it?), I feel that it's a significant enough change that we should inform our consumers, and say "hey, we've got this new piece of data for you!"

CC @ddbeck

**Comment by Elchi3** [comment]
So far adding data hasn't been considered as release-note-worthy and it was always a patch release only. New data doesn't break anyone, I think. Curious how other projects do this, though. (e.g. how do data projects like w3c/webref or w3c/browser-specs think about it).

**Comment by ddbeck** [comment]
I've got a bunch of thoughts on this. I'll try to group them together. The summary is that I think we shouldn't do this, but we could do something that's 10% of the effort for most of the benefits.

## What do other projects do?

I looked over webref and browser-specs: both have thinner release notes than we do.

The webref packages don't seem to have any release notes at all, though they use a fairly formalized process for bumping the version numbers, which produces an PR with a rather detailed look at what changed. Here's an example: https://github.com/w3c/webref/pull/292.

The browser-specs release notes tend toward a one-line summary of merged PRs. That's fine, though it's more of a changelog than release notes _per se_. Since we squash on merge, we get this more or less for free, via GitHub's compare view (which we link to in every release, though we could emphasize that more).

## What should the release notes do, anyway?

My barely considered take is that the release notes ought to tell consumers who are upgrading what has changed that might require changes on their part, or to make announcements which might impact how they think about the data (e.g., adoption of new data guidelines, major coverage milestones, etc.). The addition of individual data points probably doesn't meet that bar, though a large change might (e.g., I'd expect to write a release note when the Temporal API lands, because that's going to cause a big increase to the total number of features).

As far as our audience is concerned, nobody seems to have asked for this (to my knowledge), so perhaps nobody expects it (or even wants it)?

## What impact would this have on process?

This is the thorniest bit. Writing the release notes takes time. Some work on tooling has made this a little faster, but it's still fussy. Writing a detailed release note for every PR that adds a data point is not something I'm willing to take on alone; because of the above section, I only bother on PRs that might have a negative impact on consumers.

## Possible alternatives

That said, if there's interest in this sort of thing, I _could_ generate a list of added/removed features for every release. Since I wrote the script to figure out demixes (see https://github.com/mdn/browser-compat-data/pull/10889), this would be fairly low effort. This would have some limitations: it wouldn't reflect renames (e.g., you'd have features appear on both sides of the added and removed lists and it wouldn't be associated with a specific PR (i.e., you'd have to read the compare view yourself to find where a feature was added).

**Comment by queengooborg** [comment]
With the new release note style in play, this issue is now irrelevant, so I'm going to go ahead and close this.
