### ISSUE TITLE
For Chrome shows no tooltip on hover after setCustomValidity() is called

### ISSUE THREAD

**Issue by tpajor** [mdn/browser-compat-data#11342]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/setCustomValidity

#### What information was incorrect, unhelpful, or incomplete?
this feature is not supported by Chrome

#### Specific section or headline?
Browser support

#### What did you expect to see?
info, that this is not supported by Chrome

#### Did you test this? If so, how?
I set custom validity and it works on Firefox, but Chrome still uses it's default tooltip text

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlselectelement/setcustomvalidity`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/setCustomValidity
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlselectelement/setcustomvalidity/index.html
* Last commit: https://github.com/mdn/content/commit/3a5d65124798f70ef4777aef7ab11b7e9a5b7dbf
* Document last modified: 2021-06-13T14:10:35.000Z

</details>

**Comment by queengooborg** [comment]
I dug deeper into this to figure out what's going on.  The `setCustomValidity()` method will correctly update the popup that appears when clicking away and the input is invalid, but not the tooltip that appears when hovering over the element.

Chrome:
<img width="300" alt="image" src="https://github.com/mdn/browser-compat-data/assets/5179191/f95c119f-cb53-4735-bc7b-0fbd9f474823">

Firefox:
<img width="417" alt="image" src="https://github.com/mdn/browser-compat-data/assets/5179191/4548c85b-f73a-4309-b1c7-eb19eb7a8fca">

It's worth mentioning, however, that the example code provided by the reporter is also broken.  In the code, `setCustomValidity()` is called with an empty string when the input is focused.  However, calling `reportValidity()` will re-focus the element.  Because of that, the custom validity is set, reported, and then immediately unset before the custom message is displayed to the user.

A more accurate code example would be the following:

```html
<input id="login-input" type="email" value="" placeholder="Email" required />

<script>
	var loginInput = document.getElementById('login-input');
	loginInput.setCustomValidity('Please enter your full email address');

	loginInput.addEventListener('blur', function (event) {
		if (!loginInput.checkValidity()) {
			loginInput.reportValidity();
		}
	}, false);
</script>
```

**Comment by luis-panadero** [comment]
I have a workaround/hack fro Chrome. I intercept setCustomValidity, and set the title to the error message. So, Chrome now shows the correct tooltip.

https://codepen.io/zardoz89/pen/XJjmQvL

Also, calling reportValidity() in Chrome, it's a really bad idea. Chrome highjacks the user focus and don't allow to do ANYTHING on the web page if the user don't inputs something valid.
