### ISSUE TITLE
api.MediaRecorder.mimeType - Not supported in Safari

### ISSUE THREAD

**Issue by petersha0630** [mdn/browser-compat-data#11445]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API

#### What information was incorrect, unhelpful, or incomplete?
this function not support on  Safari on iOS 14.6 , Browser compatibility data  was incorrect.

#### Did you test this? If so, how?
got this error ==> mimeType: "video/webm; codecs=vp9"  NotSupportedError: mimeType is not supported

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/mediastream_recording_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mediastream_recording_api/index.html
* Last commit: https://github.com/mdn/content/commit/728053ce1768f0c09352e455683667a50e03cde3
* Document last modified: 2021-04-29T03:50:08.000Z

</details>

**Comment by vinyldarkscratch** [comment]
I believe that the error that you're experiencing may be due to the _codec_ you're attempting to use being unsupported, rather than the function itself.  If the `mimeType` attribute isn't supported, you should get something more along the lines of `mimeType is undefined`.  (In fact, I'm looking at the [Web video codec guide](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs#vp9) and it states that VP9 is not supported by Safari.)  Have you tried with a different codec?

**Comment by petersha0630** [comment]
I try to use codec VP8 and h264 , still not work , is this function can not record the remote webrtc stream in Safari on iOS 14.6 ?

**Comment by queengooborg** [comment]
Sorry for the long delay in a reply, we've been focusing heavily on other projects.

It's sounding like you're looking for development help, which isn't something we can provide here in BCD.  Without more details as to what you're attempting to accomplish, or test code to compare with, it's hard to say whether there's actually a browser compatibility issue or if it's just development issues.  I'm going to close this, but if it's not a development help issue, please feel free to reopen this issue and add more details such as test code.
