### ISSUE TITLE
svg.attributes.presentation.shape-rendering - Missing compatibility info and optimizeSpeed example

### ISSUE THREAD

**Issue by Leif-W** [mdn/browser-compat-data#11669]
#### What information was incorrect, unhelpful, or incomplete?

SVG shape-rendering compatibility marked as '?' for all browsers, despite being defined in SVG 1.1 about 18 years ago, and SVG 2.0 about 10 years ago.  This is not a new feature.

#### What did you expect to see?

Expected to see clear information: Yes, No, or Maybe with Caveats.

#### Did you test this? If so, how?

Brave 1.26.77 / Chromium 91.0.4472.164 mobile seemed to support this, with noticable differences in image quality between **geometricPrecision** and **crispEdges** if zooming in.

"Tested" just by looking at https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/shape-rendering page, zooming in, and seeing very subtle differences between options **geometricPrecision** and **crispEdges**.  Although the example should have a third circle for **optimizeSpeed**.

<details>
<summary>MDN page report details</summary>

* Query: `svg.attributes.presentation.shape-rendering`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/shape-rendering
* Report started: 2021-07-22T10:58:06.535Z

</details>

**Comment by queengooborg** [comment]
Sorry it took so long to respond!  We're currently working on filling out all of the data and replacing the `null` values (the question marks) with accurate data, though SVG is currently not a high priority (based upon page view count).  I'm going to close this issue since we're tracking this in #3555 already, but we'd happily welcome a PR to fill out this information!
