### ISSUE TITLE
Collaboration with caniuse?

### ISSUE THREAD

**Issue by Krinkle** [mdn/browser-compat-data#1192]
Per https://github.com/mdn/browser-compat-data/issues/116#issuecomment-366355631, I'm curious if a possible collaboration with CanIuse has been considered? These two initiatives seem to overlap rather largely. Rather than duplicating effort, it'd be cool if one could be based on the other in some way.

/cc @fyrd, @Elchi3

**Comment by ExE-Boss** [comment]
You should probably also open an issue on [the Can I use… repository](https://github.com/fyrd/caniuse).

**Comment by teoli2003** [comment]
There is currently a fundamental difference between the two sets of data.
MDN is listing compatibility information for features at a very low level: each CSS property, each method and property of each interface gets an entry. CanIUse lists compatibility information as a much higher level: E.g. "CSS Grids" instead of grid-template-row.

For example, MDN BCD could be used fairly easily to build linters or validating tools, something CanIUse data is not able to do. On the other side, when you have a blog article about overall support.ut "CSS Grids", MDN BCD is not really practical to display support information there.

There may be a convergence point here (and I think so), but it is not trivial.

**Comment by Elchi3** [comment]
We're collaborating now: https://hacks.mozilla.org/2019/09/caniuse-and-mdn-compat-data-collaboration/ :tada:

**Comment by SebastianZ** [comment]
This is awesome news! That's a big step forward for both projects.

Sebastian
