### ISSUE TITLE
javascript.builtins.Array.includes - includes() work in IE 11

### ISSUE THREAD

**Issue by YosefHazan** [mdn/browser-compat-data#12041]
#### What information was incorrect, unhelpful, or incomplete?
includes() not work in IE 11
#### What did you expect to see?
includes() work in IE 11
#### Did you test this? If so, how?
yes and this work !

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Array.includes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes
* Report started: 2021-08-17T19:02:46.281Z

</details>

**Comment by zloirock** [comment]
Nope.

**Comment by vinyldarkscratch** [comment]
The Array `includes()` method is not supported in IE.  I'm assuming that you tested this by opening the developer console on some page (like Google.com).  Keep in mind that, when testing in the developer console, many websites will implement _polyfills_ which patch older browsers to provide support for otherwise unavailable features.  When testing support, it's best to open a blank page (`about:blank`) or empty HTML file with no external scripts loaded.
