### ISSUE TITLE
api.Window.postMessage - Chrome and Edge lost data using transferrable object when host and iframe's second domain differs

### ISSUE THREAD

**Issue by bingliang-zh** [mdn/browser-compat-data#12174]
Test environment: Chrome 92.0.4515.159, Edge 92.0.902.78, Firefox 91.0.1, all 64 bit on Windows 10 64bit.

#### What information was incorrect, unhelpful, or incomplete?

When Chrome and Edge `postMessage`ing a transferrable object or contains a transferrable object, if the host's secondary domain differs from iframe's, the receiver's `event.data` will be null. Which misbehaves. I suppose chromium's OOPIF causes this, but I'm not sure.
After all the MDN site says Chrome and Edge fully support `postMessage`, that's incorrect or incomplete information to me.

#### What did you expect to see?

Shows that "On Chrome and Edge, `window.postMessage` isn't fully supported."

#### Did you test this? If so, how?

I have two htmls, one for the host, the other for the iframe.

host.html
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <script type="module">
      window.onload = (e) => {
          const iframe1 = document.getElementById('iframe_1').contentWindow;
          const iframe2 = document.getElementById('iframe_2').contentWindow;
          const mask1 = new ArrayBuffer(256);
          iframe1.postMessage({ mask: mask1 }, "http://b.local.com", [mask1]);
          const mask2 = new ArrayBuffer(256);
          iframe2.postMessage({ mask: mask2 }, "http://b.remote.com", [mask2]);
      }
    </script>
  </head>
  <body>
    <p>This is Host</p>
    <iframe
      id="iframe_1"
      src="http://b.local.com/iframe.html"
      sandbox="allow-scripts allow-same-origin"
    ></iframe>
    <iframe
      id="iframe_2"
      src="http://b.remote.com/iframe.html"
      sandbox="allow-scripts allow-same-origin"
    ></iframe>
  </body>
</html>
```

iframe.html
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <script type="module">
      window.addEventListener('message', receiveMessage);

      function receiveMessage(event) {
          let origin = event.origin;
          if (origin !== "http://a.local.com") return;
          console.log(event.data);
      }
    </script>
  </head>
  <body>
    <p>This is Iframe</p>
  </body>
</html>
```

Then put host.html and iframe.html into nginx's html folder.
Add `127.0.0.1 a.local.com`, `127.0.0.1 b.local.com`, `127.0.0.1 b.remote.com` to hosts file.

Visit <http://a.local.com/host.html>

In chrome and edge, console's output is:

```text
{mask: ArrayBuffer(256)}
null
```

Firefox's console output:
```text
Object { mask: ArrayBuffer }
Object { mask: ArrayBuffer }
```

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.postMessage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage
* Report started: 2021-08-25T05:24:39.192Z

</details>

**Comment by queengooborg** [comment]
I finally dug into this one to figure out what exactly is going on, as this is quite the complicated issue.  TLDR, everything was working as expected on my end -- I was able to transfer data to and from other origins with ease.  The only difference was that I didn't modify a hosts file, and instead took advantage of having a second computer.  Otherwise, the code was mostly untouched, aside from renaming the `mask` key of the objects sent to the iframes to better distinguish them.

I don't know the intricate details of your server setup, so there's a number of possible reasons it's not working.  But if I had to guess, I'd say that the reason it's working for me and not for you is simple: you're not using HTTPS for what your browser thinks is an external domain.  There are potentially other security features (like CORP/COOP/COEP) that are playing a factor in this, but that's just a guess.

Ultimately, I have to close this as invalid, and consider the core reasoning to be for security, not because `postMessage()` has a broken implementation.
