### ISSUE TITLE
Add Oculus Browser to browsers

### ISSUE THREAD

**Issue by dominiccooney** [mdn/browser-compat-data#12303]
I would like to add compatibility data for Oculus Browser.

Oculus Browser comes with the Quest and Quest 2 VR headsets. People use it both for browsing regular 2D sites and the growing number of immersive experiences like social chat in Mozilla Hubs, watching video in YouTube VR, playing games in Construct Arcade, exploring places in Matterport, and many others.

We hope to help developers create pages that work great in all browsers, and use modern features when available, by publishing data about all the web platform features Oculus Browser supports. Adding Oculus Browser will let BCD cover specs like [WebXR Layers](https://www.w3.org/TR/webxrlayers-1/) and [Hands](https://www.w3.org/TR/webxr-hand-input-1/) accurately.

Oculus Browser is an evergreen browser. We usually release every two weeks and people get updates automatically through Oculus' store update mechanism. [Here are some proposed Oculus Browser version data.](https://github.com/dominiccooney/browser-compat-data/blob/3b9cdb9129752f7b8a2ca3aa6e91b183b86914bd/browsers/oculus.json) (I am still working on compat-data.) These only cover historical versions of interest; the last two months' data show every release. We *do* make developer facing changes in point releases, for example, we enabled WebXR Hands in 15.1 and Layers in 16.1. We welcome feedback whether to publish point releases without significant developer facing changes.

Oculus Browser is based on Chromium. We use a major.minor version numbering scheme, rev the major version when we update Chromium, and stay close to every other stable version of Chrome. For example the Oculus Browser 15.x was based on Chromium M89, 16.x was based on Chromium M91, and 17.x will be based on Chromium M93, the current stable Chrome version.

I am happy to review Oculus Browser data issues and PRs. If I'm unavailable BCD can escalate to Oculus' spec editors or Facebook's liaisons with Open Web Docs to reach the Oculus Browser team.

For help getting and testing a feature in Oculus Browser, developers can read [our documentation;](https://developer.oculus.com/documentation/web/) MDN, where I'm contributing to WebXR and WebGL docs; and the [specs 1,](https://www.w3.org/TR/webxr/) [2,](https://www.w3.org/TR/webxrlayers-1/) [3](https://www.w3.org/TR/webxr-hand-input-1/), explainers, and samples Rik at Oculus is editor or co-editor of. And a lot of us hang out in #browsers on [WebXR Discord.](http://discord.gg/Jt5tfaM)

**Comment by ddbeck** [comment]
Thanks for opening this issue, @dominiccooney! I think you're making a good case for Oculus Brower's inclusion in BCD. Some thoughts, based on [our guideline for adding a browser](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#addition-of-browsers):

- When it comes to reviewers and release process, I think you've made a good case. I know there will be details to work out (for example, it'll be nice to have a release date for the first included version), but I'm not worried about getting it done.

- When it comes to documentation, I think things are looking good as well. Knowing the Chromium version mapping helps a lot for general web APIs and there's some detail to rely on for VR-specific features. I think the one area of concern here is that direct testing will be challenging, given the hardware requirements. I'm assuming (maybe wrongly?) that there's no way to use Oculus Browser independently of an Oculus device; we'll be leaning heavily on your reviews and trusting that you'll report the data accurately. That makes it slightly riskier than I would otherwise prefer, but I don't think it's a showstopper.

- When it comes to an downstream consumer story, I know there's already some evidence of interest in this, to support the creation of WebXR docs, driven by Open Web Docs and @Elchi3.

  That said, I do think we need to open a discussion on mdn/content, if we're to follow the separate stream to work to be done to get Oculus-specific data to appear on MDN. When we introduced Deno to BCD, the MDN team had some questions to vet a candidate browser (I'm working on getting those questions and, hopefully, publishing them for you and other candidate browsers). The Deno discussion is probably the model for this: https://github.com/mdn/content/discussions/6457.
