### ISSUE TITLE
Fetch APIs - Inconsistent with CanIUse

### ISSUE THREAD

**Issue by queengooborg** [mdn/browser-compat-data#12340]
As brought up in https://github.com/mdn/browser-compat-data/pull/12291#issuecomment-916774685, it seems that our data is inconsistent with CanIUse.  https://caniuse.com/fetch  We should update our data to maintain consistency.

**Comment by foolip** [comment]
In particular, caniuse.com has a note that says "Only available in Chrome and Opera within ServiceWorkers" for Chrome 40-41. This is probably correct, and we should figure out which APIs are supported in service worker scope in Chrome 40-41 and use `partial_implementation` there.

The collector probably can't answer these questions now, because these API will tend to now use `[Exposed=(Window,Worker)]`, which means we'll generate tests for dedicated workers, but we need to detect support in service workers specifically, which we don't generate tests for.
