### ISSUE TITLE
css.properties.unicode-bidi - link reference on Safari/Chrome lockup missing

### ISSUE THREAD

**Issue by Volker-E** [mdn/browser-compat-data#12377]
#### What information was incorrect, unhelpful, or incomplete?

Where does the information on `-webkit-isolate` lockup issues on Safari and Chrome up to 47 come from? Couldn't find information in the Chromium bug tracker. Are links allowed and recommended here?

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.unicode-bidi`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/unicode-bidi
* Report started: 2021-09-13T14:40:10.102Z

</details>

**Comment by queengooborg** [comment]
It looks like this information came from the original wiki tables before we migrated to a machine-readable JSON structure; that is, we actually don't know where the data comes from.  Considering this, I question the accuracy of the data.  If you have a bug or other resources that confirm the data, we'd love to see them, otherwise I'd welcome a PR to remove that note!

Note, you might be able to find something in WebKit's bug tracker instead: https://bugs.webkit.org

**Comment by queengooborg** [comment]
There has been no response so I'm going to go ahead and close this issue.
