### ISSUE TITLE
api.HTMLAudioElement - Not all audio formats supported

### ISSUE THREAD

**Issue by DusteDdk** [mdn/browser-compat-data#12392]
#### What information was incorrect, unhelpful, or incomplete?
Incomplete: The Audio() element does not fully support the filetypes indicated in the documentation.
It is documented that FLAC is supported, however, FLAC files with a large ID3 tag does not work as expected.

#### What did you expect to see?
I expect it to say partial support.
I expect that if I point the address bar to a file, and it plays, then the Audio() class will be able to decode that file if I set its src property to the URL of that file.

#### Did you test this? If so, how?
1. Point the addressbar to a FLAC file with an ID3 header. Verify that it plays as expected, stop it.
2. Press F12, in the js console type: (new Audio()).src='path/to/file.flac'; and press enter, a decode error. Even though content-type from server is correct AND the url has the .flac extention, the Audio element ignores these, tries to guess, and fails to decode the FLAC file as MP3.

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLAudioElement`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement
* Report started: 2021-09-14T19:26:39.334Z

</details>

**Comment by ktmf01** [comment]
ID3 support is not part of the FLAC spec. In fact, [it is discouraged](https://xiph.org/flac/faq.html#general__tagging).

Therefore, I would consider this not 'partial support'. The FLAC format is fully supported, as ID3 is not part of the spec.

**Comment by DusteDdk** [comment]
> Therefore, I would consider this not 'partial support'. The FLAC format is fully supported, as ID3 is not part of the spec.

Yeah, the reality, though, is that flac files like that, which play just fine (tm) in all players (including firefox) are not uncommon, they're out there on the Internet, it's not like I created a bunch just to annoy people and complain, I literally hit my head on this multiple times when browsing music.

Your "technically correct" conclusion conveniently ignores reality. In much the same way that the browser in question ignores the HTTP CONTENT-TYPE HEADER!!!! in lieu of trying to ducktype the datastream with some third-party library (which is a reasonable fallback in case there is no CONTENT-TYPE, but is an exceptionally retarded default thing to do when the header is available).

**Comment by ktmf01** [comment]
> Your "technically correct" conclusion conveniently ignores reality. In much the same way that the browser in question ignores the HTTP CONTENT-TYPE HEADER!!!! in lieu of trying to ducktype the datastream with some third-party library (which is a reasonable fallback in case there is no CONTENT-TYPE, but is an exceptionally retarded default thing to do when the header is available).

Are you sure it does that? It could very well be it tries to parse the file as FLAC first and fails, because the FLAC format specifies the first 4 bytes of a stream or file must be fLaC. If a ID3v2 tag is present, this is not the case and a decoder or parser could decide to not investigate any further as a FLAC file and ducktype instead. I wouldn't call that retarded in any way.

You are right that many decoders are able to skip over an ID3v2 tag. This might be because the FLAC format is designed in such a way that a decoder can start decoding at any point in a stream (this was done so FLAC can be multicast without problems). It could be some decoders simply ignore the ID3v2 tag not because they know it can be ignored but because they are simply programmed to look for the first FLAC frame they find, ignoring anything before that point.

Still, this technicality (not being able to parse a malformed FLAC stream) is not something I would consider necessary to claim full support.

**Comment by queengooborg** [comment]
Because browser vendors may implement support for individual media codecs as desired, a lack of support for an entire codec wouldn't be enough to mark the `Audio()` constructor as partially supported in BCD.  We are considering a way to add data for media formats though, see #6971.

---

Regardless, I'm going to say that this is very much an edge case.  I have not been able to set up a test case because all audio programs I've been using have been writing Vorbis tags to the FLAC file, not ID3v1 or ID3v2 tags.  This includes Adobe Audition, Audacity and even _ffmpeg_ -- and if a low-level program like ffmpeg isn't letting me do so, I feel confident in saying that any FLAC files that _do_ have ID3 tags are malformed.

**Comment by queengooborg** [comment]
Well, here are my questions to you then:

- What browser are you using?  (You had not mentioned which browser is affected.)
- Is this still an issue in the latest version of the browser?
- Have you found a corresponding bug report in the browser's bug tracker, or created one yourself?
- What is the source of the FLAC files you are testing with?  Are they ones you downloaded or did you create them yourself?
- What happens if you use the standard way of defining an audio source on construction?  `new Audio('path/to/file.flac')`
