### ISSUE TITLE
api.Request.keepalive - Supported on Safari?

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#12486]
#### What information was incorrect, unhelpful, or incomplete?

`Request.prototype.keepalive` exists on WebKit Nightly and Gnome Web, so probably also on Safari.

#### What did you expect to see?

A support number

#### Did you test this? If so, how?

Typed on console

<details>
<summary>MDN page report details</summary>

* Query: `api.Request`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Request
* Report started: 2021-09-20T00:10:19.648Z

</details>

**Comment by ashnicdill** [comment]
NO please do not this isn't me!!!! This is not Ashley Dill that requested
this. I'm Ashley Dill. I don't know what any of this is. I only use my
Motorola phone with Google and Chrome. With my old phone and now probably
this one, that he hacked it and recorded Everytime I talked. This is a
major invasion of privacy. Please help. He could even record my screen and
may see these emails. My husband is very smart, knows how to build apps,
and I need to figure out how to make it stop. We have been separated for
months. He has never had permission to use my phone and I do believe has
access to 100% of it. I can't even change some settings. I bought this new
Motorola because he did the same thing to my last phone. Can someone help
me? Please? He owns a Windows computer and Samsung phone

**Comment by queengooborg** [comment]
This has been resolved by #12579!
