### ISSUE TITLE
webextensions.manifest - <PUT TITLE HERE>

### ISSUE THREAD

**Issue by killer51588** [mdn/browser-compat-data#12494]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `webextensions.manifest`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_compatibility_for_manifest.json
* Report started: 2021-09-20T16:55:35.071Z

</details>

**Comment by ashnicdill** [comment]
This isn't me. I have NEVER added web extensions. Apps and sites and chrome
never work properly because of my issue. My husband is very smart, knows
how to build apps, and I need to figure out how to make it stop. We have
been separated for months. He has never had permission to use my phone and
I do believe has access to 100% of it. I can't even change some settings. I
bought this new Motorola because he did the same thing to my last phone.
Can someone help me? Please? I signed out of whatever 5000x is and a
Windows computer which he has. He also has a Samsung phone. I cannot
control settings. He has accessed 100% of my phone to include messages,
apps such as Snapchat, Instagram, Facebook, google accounts, my phone
literally everything. Even the sim card and I can't even fix some settings.
