### ISSUE TITLE
css.properties.transform-style - Problem in Chrome 94

### ISSUE THREAD

**Issue by HugoFortunato** [mdn/browser-compat-data#12605]
Apparently I'm having a problem with the transform-style property: preserve-3d in the last version 94 of Chrome.

I have an app in production and since the last Chrome update, last Saturday my flip-card doesn't work anymore. Remembering that, the same code works in Safari and Firefox.

**Comment by queengooborg** [comment]
I had just closed #12604 because they were reporting the same problem.  I thought it was a development issue, because the example on the MDN page is functioning just fine for me in Chrome 94, but there might be some more to this.

Can you provide more details as to what's going on, such as screenshots, code examples, what behavior changed in Chrome 94, etc.?

**Comment by queengooborg** [comment]
I'm closing this issue in favor of the earlier #12604.  Let's continue in that issue!
