### ISSUE TITLE
Feedback wanted: BCD release notes

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#13229]
Hi all,

please take a look at the release notes https://github.com/mdn/browser-compat-data/blob/main/RELEASE_NOTES.md

Do you read the release notes regularly? 
Which information is useful to you?

Do you make use of the "Notable changes" lists? It often talks about renames and removals like so:
- "api.BaseAudioContext.createPeriodicWave.disableNormalisation_supported was renamed to api.BaseAudioContext.createPeriodicWave.constraints_disableNormalization_parameter"
- "The following non-existent, long-removed, or otherwise irrelevant features have been removed: api.Element.overflow_event"

Do you make use of the statistics section?

> 10 contributors have changed 111 files with 1,162 additions and 946 deletions in 60 commits (v4.0.7...v4.0.8)
> 13,390 total features
> 815 total contributors
> 3,631 total stargazers

We would like to automate releases some more and your feedback helps us to determine the importance of the information in BCD release notes. Thanks!

**Comment by mahozad** [comment]
I'm talking about the GitHub releases not the RELEASE_NOTES.md file.

I have subscribed to "Release" notifications of my favorite projects and repositories on GitHub, including this repository.

Although it's been some time since I worked on Web projects, I regularly check my GitHub notifications (when there is a blue dot on the bell icon) for these release notes, and I love to see them.

It has become like an RSS feed reader for libraries/projects changelog, new features etc.
Please keep them coming.

---

As a side note, I have written a [GitHub workflow job] for [one of my own libraries] that automatically generates the release notes from the repository CHANGELOG.md file (and also creates the showcase APK) so I do not have to create the release notes for GitHub releases again and by myself.

Also, as you probably know, there are ready-to-use GitHub actions like [this] for that purpose.

  [GitHub workflow job]: https://github.com/mahozad/android-pie-chart/blob/master/.github/workflows/publish-new-release.yml#L199
  [one of my own libraries]: https://github.com/mahozad/android-pie-chart/releases
  [this]: https://github.com/marketplace/actions/release-changelog-builder

**Comment by meduzen** [comment]
I consume the data of this repository for [canistop.net](https://canistop.net) using automation, and like @mahozad I’ve subscribed to “releases” notifications.

I’m interested by any potentially breaking change in the structure of the browsers data.

So, when reading the release note, that’s the single thing I’m looking for. As such, it would be great if the “scope” of each entry could be highlighted.

For example, in the [4.0.0](https://github.com/mdn/browser-compat-data/releases/tag/v4.0.0) all “notable changes” are listed without distinction. Taking a subset, it roughly looks like this:

> ### Notable changes
>
> - The schema for browser release data now supports the optional accepts_flags boolean hint, which indicates whether a browser (or individual release) should contain flags data. Presently, this is a hint for data contributors or tools. The value of accepts_flags doesn't (yet) make any guarantees about the contents of feature data. (#11286)
> - Descendant features of api.HTMLCanvasElement.getContext and api.HTMLCanvasElement.toBlob have been reorganized to follow the guideline for parameter object features. See the PR for a detailed list of features affected. (#11234)
> - The following features were lower-cased for consistency with other feature names: (#11961)
>   - api.CanvasRenderingContext2D.drawImage.Smoothing_downscaling (now smoothing_downscaling)
>   - api.OfflineAudioContext.OfflineAudioContext.Parameters_accepted_in_an_object (now parameters_accepted_in_an_object)

I think having just the scope/type of change i front of each entry would help me to scan and picture what the release is all about. A but like this:

> ### Notable changes
>
> - **[Browsers data]** The schema for browser release data now supports the optional accepts_flags boolean hint, which indicates whether a browser (or individual release) should contain flags data. Presently, this is a hint for data contributors or tools. The value of accepts_flags doesn't (yet) make any guarantees about the contents of feature data. (#11286)
> - **[Web API]** Descendant features of api.HTMLCanvasElement.getContext and api.HTMLCanvasElement.toBlob have been reorganized to follow the guideline for parameter object features. See the PR for a detailed list of features affected. (#11234)
> - **[Web API]** The following features were lower-cased for consistency with other feature names: (#11961)
>   - api.CanvasRenderingContext2D.drawImage.Smoothing_downscaling (now smoothing_downscaling)
>   - api.OfflineAudioContext.OfflineAudioContext.Parameters_accepted_in_an_object (now parameters_accepted_in_an_object)

**Comment by j-m** [comment]
As a consumer, these release notes are vital but could use a cleanup, imo:

`Notable changes` -> `Breaking changes` and say what happened with each, even if repeated

i.e.

> Notable changes
The following non-existent, long-removed, or otherwise irrelevant features have been removed:
api.MediaSettingsRange (#13373)
api.ProcessingInstruction.data (#13388)
http.headers.Feature-Policy.vibrate (#13278)
http.headers.Feature-Policy.vr (#13260)

becomes 

> Breaking changes
Removed `api.MediaSettingsRange` (#13373)
Removed `api.ProcessingInstruction.data` (#13388)
Removed `http.headers.Feature-Policy.vibrate` (#13278)
Removed `http.headers.Feature-Policy.vr` (#13260)

But definitely keep it short and sweet with a link to each PR. 

I would also recommend including new features and fixes, too, as some people pay pin the package to `~` and exact (not just to the default `^`) and in all honesty seeing "known issues" in a >1 versioned library is worrying; if something is still in progress then either don't merge it or reduce its scope. 

But, seeing as you're following semver, I would strongly recommend adopting the [conventional commits standard](https://www.conventionalcommits.org/en/v1.0.0/) and completely automate the process with one of the well established change-log generators:
- https://github.com/conventional-changelog/conventional-changelog
- https://github.com/conventional-changelog/standard-version
- https://github.com/semantic-release/semantic-release

As impressive as the stats are, I don't think the changelog is the right place for them, perhaps go bananas with it and include a interactive graph in your docs somewhere. I know they're at the bottom of each release but if, like me, you rarely update this package then that's a lot of extra fluff to scroll through when you're jumping several versions (on both https://github.com/mdn/browser-compat-data/releases and https://github.com/mdn/browser-compat-data/blob/main/RELEASE_NOTES.md)

**Comment by ddbeck** [comment]
Thanks for the feedback that's already appeared so far. It's quite interesting and valuable! I've made one last call for feedback before we start changing things up, but it sounds like there's lots of opportunities to improve things, even without a lot of effort up front. For example, I generated a list of changes for the latest release (with a very, very rough looking set of shell scripts).

cc: @Elchi3 

<details>

<summary>Example generated notes for v4.0.11</summary>

## Removals in this version
- Removed `api.MediaStreamAudioSourceOptions` ([#13523](https://github.com/mdn/browser-compat-data/pull/13523))
- Removed `api.MediaStreamAudioSourceOptions.mediaStream` ([#13523](https://github.com/mdn/browser-compat-data/pull/13523))
- Removed `api.PhotoCapabilities` ([#13479](https://github.com/mdn/browser-compat-data/pull/13479))
- Removed `api.PhotoCapabilities.fillLightMode` ([#13479](https://github.com/mdn/browser-compat-data/pull/13479))
- Removed `api.PhotoCapabilities.imageHeight` ([#13479](https://github.com/mdn/browser-compat-data/pull/13479))
- Removed `api.PhotoCapabilities.imageWidth` ([#13479](https://github.com/mdn/browser-compat-data/pull/13479))
- Removed `api.PhotoCapabilities.redEyeReduction` ([#13479](https://github.com/mdn/browser-compat-data/pull/13479))
- Removed `api.Range.insertNode.collapsed_ranges` ([#13424](https://github.com/mdn/browser-compat-data/pull/13424))
- Removed `api.XMLHttpRequest.readyState.constants` ([#12879](https://github.com/mdn/browser-compat-data/pull/12879))
- Removed `css.types.calc.color_values` ([#13486](https://github.com/mdn/browser-compat-data/pull/13486))
## Additions in this version
- Added `api.AudioData.timestamp` ([#13390](https://github.com/mdn/browser-compat-data/pull/13390))
- Added `api.AudioDecoder.isConfigSupported` ([#13391](https://github.com/mdn/browser-compat-data/pull/13391))
- Added `api.AudioEncoder.flush` ([#13397](https://github.com/mdn/browser-compat-data/pull/13397))
- Added `api.AudioEncoder.isConfigSupported` ([#13393](https://github.com/mdn/browser-compat-data/pull/13393))
- Added `api.DeviceMotionEvent.requestPermission` ([#13398](https://github.com/mdn/browser-compat-data/pull/13398))
- Added `api.DeviceOrientationEvent.requestPermission` ([#13398](https://github.com/mdn/browser-compat-data/pull/13398))
- Added `api.HTMLMetaElement.media` ([#13452](https://github.com/mdn/browser-compat-data/pull/13452))
- Added `api.HTMLOutputElement.HTMLOutputElement` ([#13453](https://github.com/mdn/browser-compat-data/pull/13453))
- Added `api.ImageData.colorSpace` ([#13454](https://github.com/mdn/browser-compat-data/pull/13454))
- Added `api.ImageDecoder.decode` ([#13455](https://github.com/mdn/browser-compat-data/pull/13455))
- Added `api.ImageDecoder.isTypeSupported` ([#13456](https://github.com/mdn/browser-compat-data/pull/13456))
- Added `api.Ink` ([#13457](https://github.com/mdn/browser-compat-data/pull/13457))
- Added `api.Ink.requestPresenter` ([#13457](https://github.com/mdn/browser-compat-data/pull/13457))
- Added `api.MediaSession.setCameraActive` ([#13460](https://github.com/mdn/browser-compat-data/pull/13460))
- Added `api.MediaSession.setMicrophoneActive` ([#13460](https://github.com/mdn/browser-compat-data/pull/13460))
- Added `api.Navigator.ink` ([#13457](https://github.com/mdn/browser-compat-data/pull/13457))
- Added `api.Navigator.pdfViewerEnabled` ([#13458](https://github.com/mdn/browser-compat-data/pull/13458))
- Added `api.Navigator.virtualKeyboard` ([#13464](https://github.com/mdn/browser-compat-data/pull/13464))
- Added `api.NavigatorUAData.platform` ([#13465](https://github.com/mdn/browser-compat-data/pull/13465))
- Added `api.NavigatorUAData.toJSON` ([#13465](https://github.com/mdn/browser-compat-data/pull/13465))
- Added `api.PermissionStatus.name` ([#13466](https://github.com/mdn/browser-compat-data/pull/13466))
- Added `api.Profiler` ([#13462](https://github.com/mdn/browser-compat-data/pull/13462))
- Added `api.Profiler.Profiler` ([#13462](https://github.com/mdn/browser-compat-data/pull/13462))
- Added `api.Profiler.sampleInterval` ([#13462](https://github.com/mdn/browser-compat-data/pull/13462))
- Added `api.Profiler.stop` ([#13462](https://github.com/mdn/browser-compat-data/pull/13462))
- Added `api.Profiler.stopped` ([#13462](https://github.com/mdn/browser-compat-data/pull/13462))
- Added `api.Scheduler` ([#13463](https://github.com/mdn/browser-compat-data/pull/13463))
- Added `api.Scheduler.postTask` ([#13463](https://github.com/mdn/browser-compat-data/pull/13463))
- Added `api.SpeechSynthesisEvent.elapsedTime.milliseconds` ([#13236](https://github.com/mdn/browser-compat-data/pull/13236))
- Added `api.TaskController` ([#13463](https://github.com/mdn/browser-compat-data/pull/13463))
- Added `api.TaskController.setPriority` ([#13463](https://github.com/mdn/browser-compat-data/pull/13463))
- Added `api.TaskController.TaskController` ([#13463](https://github.com/mdn/browser-compat-data/pull/13463))
- Added `api.TaskPriorityChangeEvent` ([#13463](https://github.com/mdn/browser-compat-data/pull/13463))
- Added `api.TaskPriorityChangeEvent.previousPriority` ([#13463](https://github.com/mdn/browser-compat-data/pull/13463))
- Added `api.TaskPriorityChangeEvent.TaskPriorityChangeEvent` ([#13463](https://github.com/mdn/browser-compat-data/pull/13463))
- Added `api.TaskSignal` ([#13463](https://github.com/mdn/browser-compat-data/pull/13463))
- Added `api.TaskSignal.onprioritychange` ([#13463](https://github.com/mdn/browser-compat-data/pull/13463))
- Added `api.TaskSignal.priority` ([#13463](https://github.com/mdn/browser-compat-data/pull/13463))
- Added `api.VideoDecoder.isConfigSupported` ([#13467](https://github.com/mdn/browser-compat-data/pull/13467))
- Added `api.VideoEncoder.flush` ([#13468](https://github.com/mdn/browser-compat-data/pull/13468))
- Added `api.VideoEncoder.isConfigSupported` ([#13468](https://github.com/mdn/browser-compat-data/pull/13468))
- Added `api.VideoFrame.copyTo` ([#13469](https://github.com/mdn/browser-compat-data/pull/13469))
- Added `api.VirtualKeyboard` ([#13464](https://github.com/mdn/browser-compat-data/pull/13464))
- Added `api.VirtualKeyboard.boundingRect` ([#13464](https://github.com/mdn/browser-compat-data/pull/13464))
- Added `api.VirtualKeyboard.hide` ([#13464](https://github.com/mdn/browser-compat-data/pull/13464))
- Added `api.VirtualKeyboard.ongeometrychange` ([#13464](https://github.com/mdn/browser-compat-data/pull/13464))
- Added `api.VirtualKeyboard.overlaysContent` ([#13464](https://github.com/mdn/browser-compat-data/pull/13464))
- Added `api.VirtualKeyboard.show` ([#13464](https://github.com/mdn/browser-compat-data/pull/13464))
- Added `javascript.builtins.Array.findLast` ([#13370](https://github.com/mdn/browser-compat-data/pull/13370))
- Added `javascript.builtins.Array.findLastIndex` ([#13370](https://github.com/mdn/browser-compat-data/pull/13370))
- Added `javascript.builtins.Error.Error.fileName_parameter` ([#13172](https://github.com/mdn/browser-compat-data/pull/13172))
- Added `javascript.builtins.Error.Error.lineNumber_parameter` ([#13172](https://github.com/mdn/browser-compat-data/pull/13172))
- Added `javascript.builtins.TypedArray.findLast` ([#13370](https://github.com/mdn/browser-compat-data/pull/13370))
- Added `javascript.builtins.TypedArray.findLastIndex` ([#13370](https://github.com/mdn/browser-compat-data/pull/13370))

</details>

**Comment by ddbeck** [comment]
The most recent release used a mostly-generated process. See https://github.com/mdn/browser-compat-data/releases/tag/v4.0.12.

**Comment by ddbeck** [comment]
It's been a while without further commentary on releases. I'm going to close this, though work continues on improving our release process. Thanks, everyone!
