### ISSUE TITLE
performance.measure() return value browser inconsistency

### ISSUE THREAD

**Issue by wbamberg** [mdn/browser-compat-data#13418]
This comes from https://github.com/mdn/content/pull/10235 which comes from https://github.com/mdn/content/issues/10009.

There's a browser inconsistency in the return value of https://developer.mozilla.org/en-US/docs/Web/API/Performance/measure.

It looks like:

* the old spec version: https://www.w3.org/TR/user-timing/#measure-method specified no return value
* the new spec draft: https://w3c.github.io/user-timing/#dom-performance-measure specifies that the method returns a [`PerformanceMeasure`](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceMeasure)

From testing, it looks like at least:
* Firefox 96 follows the old spec, returning `undefined`
* Safari 15 and Chrome 95 follow the new spec, returning a [`PerformanceMeasure`](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceMeasure)

I don't know if it would be better to handle this using a note or a subfeature.

**Comment by hamishwillee** [comment]
@wbamberg FYI only, this sounds very similar to https://github.com/mdn/browser-compat-data/pull/13236 in which `SpeechSynthesisEvent.elapsedTime` spec changed from returning `ms` to `s`. The way this was handled was to add a subfeature showing support for the old way of doing things that is removed in the version where the new way of doing things arrives. Also marking the subfeature non-standard.

Since I just went through that process I'll give it a go for this too.
