### ISSUE TITLE
css.properties.width.fit-content - Incorrect info for Firefox

### ISSUE THREAD

**Issue by danny0838** [mdn/browser-compat-data#13428]
#### What information was incorrect, unhelpful, or incomplete?
It's said that Firefox supports the prefixed value only since 3.* and Firefox for Android supports the prefixed value only since 4.*.

#### What did you expect to see?
Firefox 94 is known to support the unprefixed value.

Firefox 74 is known to support the prefixed value only.

Firefox for Android 96 is is known to support the unprefixed value.

Firefox for Android 68 is is known to support the prefixed value only.

#### Did you test this? If so, how?
Tested on a page that renders differently if the value is supported or not.

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.width.fit-content`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content
* Report started: 2021-11-10T12:00:13.038Z

</details>

**Comment by robinmetral** [comment]
I was surprised to see that the compat data still says `fit-content` is only usable with the `-moz` prefix on Firefox:

https://github.com/mdn/browser-compat-data/blob/138148b9448cbfee4b54e61ecff7fd640bf805be/css/properties/width.json#L190-L193

I think that this was fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1732759, so indeed no need for the prefix anymore since Firefocx 94

**Comment by queengooborg** [comment]
This was fixed by #16392!
