### ISSUE TITLE
api.Window.localStorage - local html-file dosn´t acces to the data of a other local html-file in the same folder

### ISSUE THREAD

**Issue by karlsson72** [mdn/browser-compat-data#13853]
Firefox 68.0.1 (32-bit) works with localStorage and acces over two local html-files in the same folder
Firefox 72.0.2  (32-bit) works with localStorage and acces over two local html-files in the same folder

and now 
Firefox 94.0.2 (32-bit) dosn´t work with localStorage and acces over two local html-files in the same folder
Firefox 94.0.2 (64-bit) dosn´t work with localStorage and acces over two local html-files in the same folder

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.localStorage`
* MDN URL: https://developer.mozilla.org/de/docs/Web/API/Window/localStorage
* Report started: 2021-12-03T17:19:13.961Z

</details>

**Comment by queengooborg** [comment]
From what I can tell gleaming over the documentation for `localStorage`, this change is to be expected: "In all current browsers, localStorage seems to return a different object for each file: URL. In other words, each file: URL seems to have its own unique local-storage area."

It seems that the spec doesn't actually define how web browsers are meant to handle `localStorage` for `file:` paths, so developers not rely on behavior for `localStorage` across local files.  Because `file:` path behavior is also undefined, I don't think this is something BCD would record support information for.
