### ISSUE TITLE
api.Element.dblclick_event - <dblclick fails for firefox at server>

### ISSUE THREAD

**Issue by sonam-vg** [mdn/browser-compat-data#14260]
#### Opened a firefox browser. Executed a application.
My code sample is below.
`  $('#tableID tbody').on('dblclick', 'tr', function () {
// some logic
});`

dblclick event works fine for chrome but not for firefox version 95.0.2 (64-bit)
It works on server when we do 4 clicks instead of 2 clicks.
I am not sure weather single click is picked when we do 2 clicks
**It works on localhost but not on server.**

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.dblclick_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/dblclick_event
* Report started: 2021-12-28T13:29:01.393Z

</details>

**Comment by queengooborg** [comment]
Unfortunately this sounds like a development issue, since a) it's working on localhost, b) it appears you're using jQuery, and c) this event has been around for a long time.

Normally we don't provide development help here, but I just wanted to point out that jQuery has its own double-click handler: https://api.jquery.com/dblclick/
