### ISSUE TITLE
css.types.image.gradient.linear-gradient - the status of Firefox is confusing

### ISSUE THREAD

**Issue by mfuji09** [mdn/browser-compat-data#14598]
#### What information was incorrect, unhelpful, or incomplete?

The following in the status note of Firefox 

> (Version 16) Before Firefox 36, gradients weren't applied on the pre-multiplied color space, leading to shades of grey unexpectedly appearing when used with transparency.

It seems to say Firefox 37 or later has full support, but this status looks Firefox doesn't have full support yet.

#### What did you expect to see?

The following line should be added:
Version 37 : Full support

#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `css.types.image.gradient.linear-gradient`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/CSS/gradient/linear-gradient()
* Report started: 2022-01-20T00:58:00.664Z

</details>

**Comment by evanw** [comment]
> The following line should be added:
> Version 37 : Full support

Pre-multiplied alpha is still broken in the latest version of Firefox (Firefox 120.0.1 on macOS):

![](https://github.com/mdn/browser-compat-data/assets/406394/b1acc7dc-1377-4ee2-8231-ee27f5adf131)

It would be incorrect to mark Firefox as supporting pre-multiplied alpha.

I discovered this issue because I'm trying to find a compatibility table entry for esbuild's CSS processor so I can work around these Firefox bugs. The addition of the `premultiplied_gradients` entry in #21472 would be very helpful for me as long as I can use it to tell that Firefox doesn't support pre-multiplied alpha.
