### ISSUE TITLE
TimeZoneName is not supported by Safari < 15.4

### ISSUE THREAD

**Issue by dilyanpalauzov** [mdn/browser-compat-data#14911]
https://caniuse.com/mdn-javascript_builtins_intl_datetimeformat_datetimeformat_options_parameter_options_timezonename_parameter says Intl.DateTimeFormat supports the TimeZoneName option for long time.

The release notes for Safari 15.4 beta at https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes state that this option is supported from this version on.

**Comment by debiru** [comment]
Hi, I'm not a core committer, I'm just one reporter like you.

On this matter, take a look at this table.

 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#browser_compatibility

Safari originally supported the DateTimeFormat() constructor and options, and the new option values have been supported since.

The release notes for Safari 15.4 beta at https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes says "Supported the TimeZoneName option in Intl.DateTimeFormat.", it means that the new option is supported.

**Comment by dilyanpalauzov** [comment]
My understanding is that https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#browser_compatibility and https://caniuse.com/mdn-javascript_builtins_intl_datetimeformat_datetimeformat_options_parameter_options_timezonename_parameter use the same data sources and show the same data.  But the output is different for Safari/timeZoneName.

**Comment by debiru** [comment]
If you were to modify something about this case, what would you think should be modified?

The reason I say this is this, I try to create a Pull Request from an Issue whenever possible, because it seems to be difficult to get a fix if you just create an Issue. If you have a suggestion that needs to be fixed, it might be easier for the core committers to respond if you mention it in an Issue.

**Comment by dilyanpalauzov** [comment]
https://caniuse.com/mdn-javascript_builtins_intl_datetimeformat_datetimeformat_options_parameter_options_timezonename_parameter takes data from this repository, apparently, and does not show correct data.  I cannot describe the problem better.

**Comment by debiru** [comment]
Hmm... I see. I was going to help fix this problem by my creating a pull request if I could find out what needs to be fixed. But I'm not sure, so I'll wait for someone more knowledgeable to come along who can tell us what we need to fix about this.

**Comment by queengooborg** [comment]
This has been fixed by #14786!
