### ISSUE TITLE
css.types.counters - It's strange that the supported version of WebView Android is 1.

### ISSUE THREAD

**Issue by debiru** [mdn/browser-compat-data#15208]
#### What information was incorrect, unhelpful, or incomplete?

Probably the supported version of WebView Android is 37, not 1. See the related other properties page.

- This property:
    - https://developer.mozilla.org/en-US/docs/Web/CSS/counters()#browser_compatibility
- Other properties:
    - https://developer.mozilla.org/en-US/docs/Web/CSS/counter()#browser_compatibility
    - https://developer.mozilla.org/en-US/docs/Web/CSS/counter-reset#browser_compatibility
    - https://developer.mozilla.org/en-US/docs/Web/CSS/counter-increment#browser_compatibility

<details>
<summary>MDN page report details</summary>

* Query: `css.types.counters`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/CSS/counters()
* Report started: 2022-03-01T06:30:51.355Z

</details>

**Comment by queengooborg** [comment]
Thank you for opening this issue!  In BCD, we keep something called "ranges" for super old browsers, such as WebView 37 and below.  This is a mark to say "we know it's at least in browser version X, but it could have been implemented earlier" -- which is what you've stumbled into.  Because ranges were confusing to so many readers, however, we decided to render the tables on MDN web docs as if these ranged values were simple version numbers (i.e. "≤37" becomes just "37").  Our intention was to decrease confusion and increase corrections from the community, like yourself who had noticed this discrepancy!

All of this is a bit of a roundabout way to explain that the "37" entries you're seeing for the other browsers are actually "≤37", or "37 or possibly earlier".  Based upon the fact that counters support was added to Safari 3, which WebView Android 1 is based upon, I think the right move would actually be to change the other three properties to "1", rather than `counters()` to "≤37".  Would you be up for changing your PR to do just that?

**Comment by debiru** [comment]
Yes, that is correct. The other pages contained inequalities. I would like to respond.
