### ISSUE TITLE
api.Navigator.registerProtocolHandler - title argument is removed from Blink

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#15357]
#### What information was incorrect, unhelpful, or incomplete?

Title argument is not available anymore

#### What did you expect to see?

As such.

#### Did you test this? If so, how?

```
> navigator.registerProtocolHandler.length
2
```

https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/navigatorcontentutils/navigator_content_utils.idl;l=26;bpv=1;bpt=0 says https://source.chromium.org/chromium/chromium/src/+/ca26c5e768516b0226302307a2bbd23b0b5842af removed it.

<details>
<summary>MDN page report details</summary>

* Query: `api.Navigator.registerProtocolHandler`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler
* Report started: 2022-03-13T14:27:37.717Z

</details>

**Comment by Elchi3** [comment]
https://storage.googleapis.com/chromium-find-releases-static/ca2.html#ca26c5e768516b0226302307a2bbd23b0b5842af says that removal was in Chrome 88, released on 2021-01-19. 

That said, this now meets "feature was implemented and has since been removed from all browsers dating back two or more years ago." per https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features.

I will open PRs to remove the `title` argument from BCD and from MDN content.
