### ISSUE TITLE
Schema check on use of flags in android on FF after 79 or Opera

### ISSUE THREAD

**Issue by hamishwillee** [mdn/browser-compat-data#15544]
You can't have a flag in FF for Android after FF79 or in Opera for Android (at least some versions, according to  https://github.com/mdn/browser-compat-data/pull/15505#pullrequestreview-922407124).

Can we add a schema check? Shouldn't be up to the reviewer to have to spot this.

**Comment by queengooborg** [comment]
We do have a linter to prevent flags in select browsers, though it's more of an "all-or-nothing" situation.  I've opened #15568 to take care of Opera Android, and we're planning to remove all Firefox Android flag data once two years have passed since the release of v79 (in other words, we'll remove Firefox Android flag data on 2022-07-28).

**Comment by hamishwillee** [comment]
@queengooborg Thanks very much.

**Comment by queengooborg** [comment]
This has been fully fixed by #15950!
