### ISSUE TITLE
Linter: Make sure multiple version ranges are sorted according to some rules

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#1596]
Given multiple version ranges ...
```json
"webview_android": [
  {
    "version_added": "44"
   },
   {
    "alternative_name": "AnimationPlayer",
    "version_added": "39",
    "version_removed": "44"
  }
],
```
we should make sure that the first array element is always the most relevant (as this one will appear in the main compat cell).

For that we need to come up with some rules to guarantee "most relevant" first and generally make sense of the ordering there. Thoughts:

- Order reverse-chronological
- if there are prefixes, preferences, alternative_names or the like, rank less high.

**Comment by connorshea** [comment]
I opened #1996 earlier with this same intent after finding a problem with the ServiceWorker page:

On the [ServiceWorker](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker) page, this happens:

<img width="1055" alt="screen shot 2018-05-08 at 2 45 48 pm" src="https://user-images.githubusercontent.com/2977353/39782202-bbb2bf4e-52ce-11e8-9ca4-1654a97d57e5.png">

The problem here is that the support array first has the information about Edge 16, where the feature is supported behind a flag, and then subsequently has information about Edge 17, where it's fully supported by default.

The `ServiceWorker.json` file has these lines:

https://github.com/mdn/browser-compat-data/blob/6cad84af2697fe68585adb2a8405677324bbf12f/api/ServiceWorker.json#L16-L29

The reason this is a problem is because Kumascript assumes that the support array will have the proper support info first, which in this case doesn't happen.

See [these lines in kumascript](https://github.com/mdn/kumascript/blob/6ef0ef64afeb3ddf92bc50c9bf94c4731000268b/macros/Compat.ejs#L155-L156):

```javascript
// the first entry should be the most relevant/recent and will be treated as "the truth"
checkSupport(supportInfo[0].version_added, supportInfo[0].version_removed);
```

If we make this assumption, we should try to enforce it with the linter somehow, though I'm not sure how you'd go about doing that. 🤔 

<details>

<summary>Here's an example where it works properly</summary>

From [the flex page](https://developer.mozilla.org/en-US/docs/Web/CSS/flex#Browser_compatibility)

<img width="1066" alt="screen shot 2018-05-08 at 2 53 00 pm" src="https://user-images.githubusercontent.com/2977353/39782463-86ebf34c-52cf-11e8-90f6-8660103bcc61.png">

https://github.com/mdn/browser-compat-data/blob/01c2b6d10545f74bf88dd2fdbfb6f0c49a2cb9a9/css/properties/flex.json#L44-L78
</details>

**Comment by yasya1100** [comment]
> Учитывая несколько диапазонов версий ...
> 
> ```json
> " webview_android " : [
>   {
>     " version_added " : " 44 "
>    },
>    {
>     " альтернативное_имя " : " AnimationPlayer " ,
>      " version_added " : " 39 " ,
>      " version_removed " : " 44 "
>   }
> ],
> ```
> 
> мы должны убедиться, что первый элемент массива всегда является наиболее релевантным (так как он появится в основной совместимой ячейке).
> 
> Для этого нам нужно придумать некоторые правила, которые в первую очередь гарантируют «наиболее релевантное» и в целом имеют смысл их упорядочивания. Мысли:
> 
> * Порядок в обратном хронологическом порядке
> * если есть префиксы, предпочтения, альтернативные имена и т.п., ранг ниже.

name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  super-lint:
    # Name the Job
    name: Lint code base
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

**Comment by yasya1100** [comment]
``name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  super-lint:
    # Name the Job
    name: Lint code base
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          

- [ ] GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

 @[](url)

**Comment by yasya1100** [comment]
@yasya1100`

**Comment by caugner** [comment]
As concerns display of BCD on MDN, this has meanwhile been addressed by https://github.com/mdn/yari/pull/5649 (support history) and https://github.com/mdn/yari/pull/5946 (support cell).

/cc @queengooborg

**Comment by caugner** [comment]
FWIW This ranking/ordering algorithm implemented in yari is even a bit more sophisticated than the one suggested in  #5352.

https://github.com/danielhjacobs/yari/blob/0e9484e8c432a7fbc0f3780b98655279d8c71182/client/src/document/ingredients/browser-compatibility-table/utils.ts#L147-L189

---

**But** ... I also wonder if it wouldn't be best to distinguish between _repository_ and (npm) _package_.

In particular, _always_ ordering items in the repository simply by their lowest version_number (i.e. `item.version_added ?? 0`), and then optionally by other criteria, has the big advantage that the position of each element is stable, and doesn't change as a side-effect of introducing a newer item (which is good for `git blame`).

In _packaged_ BCD, the most relevant item _could_ be moved to the top. Alternative approaches for the _packaged_ BCD would be:

1. Marking the current item with `current: true`.
2. Adding a `__current` key to the feature that replicates the most relevant item.
3. Restructuring the release data completely by separating the `history` (what BCD currently exposes) from a summarized "status" of that history (per browser, of course), or returning that on-demand:

```ts
type SupportStatusSummary =
  | { implemented: "never" }
  | {
      implemented: "partial" | "full"
      alternative_name?: string
      flags?: Array<{type: string, name: string, value_to_set: string}>
      version_added: string,
      version_removed?: string
    }
```

**Comment by queengooborg** [comment]
I personally feel that we should keep the contributor version as close to the bundled version as possible, and that this shouldn't introduce a schema-changing update.  However, I'd be down to implement a sorting algorithm based on Yari's own, to synchronize the rendering on Yari with what other consumers will receive!

**Comment by queengooborg** [comment]
I've merged the PRs for migration 005, with the intention that we can follow-up with any changes to sorting in the later, should we desire to do so.  (Not that it matters as much now, since Yari has their own sorting.)

**Comment by juniorcastro0152-hub** [comment]
Becase They always attack me 🥺

**Comment by NoClueMike** [comment]
https://github.com/mdn/browser-compat-data/issues/1596#issuecomment-3972755039
