### ISSUE TITLE
http.headers.Feature-Policy - should it be marked as "supported" on Fx/Safari?

### ISSUE THREAD

**Issue by queengooborg** [mdn/browser-compat-data#15987]
In both Firefox and Safari, this feature is marked as supported, but partially implemented with the caveat that it is "Only supported through the `allow` attribute on `<iframe>` elements."  With this in mind, should we really consider this feature to be "supported"?

**Comment by lukewarlow** [comment]
Imo we should probably split this data into two entries one for the allow attribute and one for the header. That way its clearer that Safari and Firefox support one to varying states but not the header.

Especially because most or certainly a large portion of consumers of Feature Policy data, (or its newer derivatives like permissions policy) are probably looking for the allow attribute support.

Not sure how this would look on the mdn/content side, potentially an overarching page for the concept of Feature Policy and the two support tables?

If we choose not to split it out then i'd be hesitant to remove it because it's useful data even if slightly misleading at first glance.
