### ISSUE TITLE
Incorrect use of "mirror" results in null data with no errors

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#16418]
Setting the Firefox data to "mirror" doesn't make sense, but the build script silently turns that into null in the built data, and because we test the source, tests will pass.

I think we need more safeguards for problems like this before we use "mirror" widely.

**Comment by queengooborg** [comment]
I'm not able to reproduce this; setting Firefox to `mirror` produces the following error in the lint:

```
Problems in 1 file:
✖ api/AbortController.json
  → Versions – 1 error:
    → → api.AbortController sets firefox to mirror, however firefox does not have an upstream browser.
```

**Comment by queengooborg** [comment]
#16432 should fix that issue with mirroring, since it flat-out errors if `upstream` isn't defined for the browser we're trying to mirror to.  I also opened up #16434 to update the `diff` script to mirror data when showing diffs, which should greatly help in ensuring mirroring is working as intended!  (After #16434 lands, we should probably set up a workflow to report the differences on pull requests.)

**Comment by foolip** [comment]
Thanks @queengooborg for following up so quickly on this 👍

**Comment by foolip** [comment]
> After https://github.com/mdn/browser-compat-data/pull/16434 lands, we should probably set up a workflow to report the differences on pull requests.

Yes!!!
