### ISSUE TITLE
Linter: Make sure version_added & version_removed versions make sense

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#1660]
I saw this in a PR:

```
"version_added": "10",
"version_removed": "9"
```

Probably doesn't make sense as a feature can't be removed before it has been added. The linter should have caught this.

**Comment by ExE-Boss** [comment]
I thought that I did this as part of #1338, but it turns out I only made it enforce that `version_added` can’t be a [falsy value](https://developer.mozilla.org/docs/Glossary/Falsy) if `version_removed` is a [truthy value](https://developer.mozilla.org/en-US/docs/Glossary/Truthy).

Anyway, this can be done in Node using the [<img src="https://img.shields.io/npm/v/semver.svg?label=semver" align="top" alt="semver"/>](https://www.npmjs.com/package/semver) package.

**Comment by vinyldarkscratch** [comment]
`semver` doesn't seem to like one-digit version numbers, so in the PR I just submitted, I used a different package called `compare-versions` that I'm using in my other linter PR.  It seems to work pretty well, too!
