### ISSUE TITLE
Automatically update browser release information

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#1664]
The JSON files in https://github.com/mdn/browser-compat-data/tree/master/browsers are created/updated manually.

At least the UC ones are derived by [a script](https://github.com/mdn/browser-compat-data/commit/8dc7ef0f27bd965f59b44be8d0e0aa908cace425) and could be automated, and it's probably the case for some others as well, based on information like:
* https://chromereleases.googleblog.com/search/label/Stable%20updates
* https://developer.microsoft.com/en-us/microsoft-edge/platform/changelog/
* https://www.mozilla.org/en-US/firefox/59.0/releasenotes/ (reliable URL pattern)
* https://webkit.org/blog/

**Comment by ExE-Boss** [comment]
Firefox could probably be handled as part of the new release publishing process.

**Comment by foolip** [comment]
https://github.com/mdn/browser-compat-data/pull/2093 illustrates a challenge with any approach like this. If we do not have a human review step, then errors in the data sources will propagate to this repo, so the scripts would need to be very defensive.

**Comment by foolip** [comment]
@voxpelli this is the old issue I mentioned. I don't actually have a proposal that would work for any browser though, so I'll close this.

**Comment by captainbrosset** [comment]
I've been doing some thinking about this lately and have a high-level proposal that I think could work.

Instead of scraping the information from various sources on the web, let's ask browser companies to give us the information instead.
On the Edge team, we have a build pipeline we use to release new nightly/beta/stable versions of Edge which we could most likely plug into to retrieve information such as the version number and release date.

I'm envisioning a system sort of like this:

1. We have a clone of the BCD repo, with issues enabled (or this could be the BCD repo itself).
1. Each browser puts a notification system in place on their end that creates a new issue every time a new stable release happens, containing information about the date, and version number, and the dates of the following beta and nightly builds too.
1. The github clone has an action that gets triggered on new issues. The action reads the issue, converts this into the right browser.json file, and opens a PR on the BCD repo.

For 2, speaking for Edge only, I think this is relatively easily done. I'm sure other browser vendors could do this too. And if not, they could also just open issues by hand. Which also means that anyone else could open issues too. So, even if we didn't automate the whole thing, I think this would give us a better chance of being up to date because opening an issue is a lower barrier than creating a PR.

For 3, I have played around with actions in the past, and can confirm that something like this is doable.

@foolip what do you think? I was also talking about this with @queengooborg.

**Comment by voxpelli** [comment]
>  think this would give us a better chance of being up to date because opening an issue is a lower barrier than creating a PR

Wouldn't be that hard to automate PR creation I think, interacting with the GitHub API to create commits is pretty straight forward (I did this long ago and eg. created [this short helper module](https://github.com/voxpelli/node-github-publish/blob/main/index.js))

I like the idea of automating this like that @captainbrosset 👍
