### ISSUE TITLE
MediaDevices.getDisplayMedia() ignores constraints in FF

### ISSUE THREAD

**Issue by zemiacsik** [mdn/browser-compat-data#16771]
# Request type

- [x] Correction or update

# Details

[MediaDevices.getDisplayMedia()](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia) should accept [MediaTrackConstraints](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints#Properties_of_shared_screen_tracks) according to documentation:

> Either a Boolean (which indicates whether or not a video track is requested) or a MediaTrackConstraints object providing the constraints which must be met by the video track included in the returned MediaStream. If constraints are specified, a video track is inherently requested.

However it does not and for example if you use this, it does not affect it at all:
`getDisplayMedia({ video: { cursor: 'never', displaySurface: 'browser' } })`

# Expected result

It should take constraints into account if I provide them (or at least allow to user to select desired one, it is not possible to select browser tab in FF atm [Chrome has this possibility in selection pop up]).

**Comment by queengooborg** [comment]
(I have now learned today that GitHub does not sort issues by number, but by creation date, interesting!)

I don't think that we need to make any updates because I think this may be a case of misreading the documentation.  There's a page documenting the [`displaySurface` constraint](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/displaySurface), and down in the BCD section it states Chromium added support in 107, Safari in 11.1, and Firefox still does not have support.  This issue's creation date predates Chromium 107, so if the reporter has tested both Chrome and Firefox around that time, they'll find that there's no support, exactly as BCD states.
