### ISSUE TITLE
Make Travis CI output more helpful

### ISSUE THREAD

**Issue by kaycebasques** [mdn/browser-compat-data#1694]
The Travis build lists all of the files that pass. It's a very long list. It's hard to scroll down to the info that I need in order to fix the build.

Can you modify it to only test files that have changed in this PR?

https://travis-ci.org/mdn/browser-compat-data/builds/358642970?utm_source=github_status&utm_medium=notification

**Comment by ExE-Boss** [comment]
That’s probably too complicated and not really worth the investment, plus you can always just use `Ctrl+F`.

**Comment by jwhitlock** [comment]
I'm not aware of an easy way to determine what files have changed in a PR, so we'd need to figure that out first. It may be easier to go the other way - have a config option for the linter to only output errors.

To lint a single file locally:

```
$ node test/lint api/Performance.json
api/Performance.json
  JSON schema – OK 
  Style – OK 
  Browser versions – OK 
```

**Comment by kaycebasques** [comment]
Thanks @jwhitlock that helps

**Comment by Elchi3** [comment]
This issue is similar to https://github.com/mdn/browser-compat-data/issues/371 which got fixed in https://github.com/mdn/browser-compat-data/pull/521.

We didn't change the travis output, but locally you can do `npm run show-errors`.
I think I like the more verbose travis output, but happy to hear other opinions (will close if I hear nothing, though).

**Comment by kaycebasques** [comment]
It makes little sense to me to run the tests for hundreds of files that haven't been modified, but John gave me a workaround and I'm not maintaining the infrastructure, so I'm good. Thanks for the help.
