### ISSUE TITLE
css.properties.transition - Firefox seem to be supporting property without prefix

### ISSUE THREAD

**Issue by rubiesonthesky** [mdn/browser-compat-data#17208]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The compatibility table says that Firefox needs -webkit prefix. It seems that Firefox 102 at least supports transition without prefix. 

But I have no idea, when the support was added.

### What browsers does this problem apply to, if applicable?

Firefox

### Did you test this? If so, how?

I did test locally on Firefox

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/transition

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.transition`
* Report started: 2022-08-02T09:14:54.404Z

</details>

**Comment by queengooborg** [comment]
This seems to be a rendering issue of the tables rather than an issue with the data itself.  It appears that the icon for a prefix requirement is showing when it shouldn't.  For the data itself, here's the story:

- Firefox 4 added the properties, but required the `-moz-` prefix.
- Firefox 16 added unprefixed variants.
- Later, Firefox 49 added the ability to use the `-webkit-` prefix as well as the unprefixed version to enable compatibility with older websites written for Chrome/Safari.

I'll try to get a fix out for the engine ASAP!
