### ISSUE TITLE
Document it more clearly that compat data for iOS lists the OS version, not the Safari version.

### ISSUE THREAD

**Issue by romainmenke** [mdn/browser-compat-data#17241]
see : https://github.com/mdn/browser-compat-data/blob/main/docs/contributing.md#finding-browser-version-numbers-for-features

see : https://developer.mozilla.org/en-US/docs/MDN/Contribute/Processes/Matching_features_to_browser_version#safari

It is not obvious on MDN compat table and in the contributing guidelines that the versions for iOS are OS versions and not Safari versions.

Can this be documented explicitely?

**Comment by queengooborg** [comment]
I added a section to the second article while moving it over to BCD: https://github.com/mdn/browser-compat-data/blob/main/docs/matching-browser-releases/index.md#safari-on-iosipados to explain that the iOS version is to be used rather than the Safari version, but I don't know how it could be made more visible, especially on the MDN tables.  There is a data guideline for this as well: https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#safari-for-ios-versioning

**Comment by romainmenke** [comment]
The updated documentation on BCD is very helpful, thank you!

I am also unsure how this can be made clear on the MDN tables.
They are already very dense, so extra footnotes or legends would just add more noise.
I assume `Browsers on iOS` might also not be a popular solution :)

I've only been actively maintaining polyfills and fallbacks for older browsers for the past ±3 years and coincidentally seem to have picked this up right around the migration.

Before this I only used these tables as a web developer and they were more an indication of how "safe" a feature was to use. I wasn't actually interested in the exact numbers at that time.

**Comment by queengooborg** [comment]
Taking a look at this again, I think that we could safely close this issue.  Since Safari 15 / iOS 15, the version numbers of Safari and iOS have lined up.  As such, it may no longer be needed to explicitly state this on the tables!  What do you think?

**Comment by romainmenke** [comment]
Yeah, given the reluctance to do update the label there isn't much more that can be done here.

Thank you for submitting that patch and for revisiting this issue @queengooborg 🙇
