### ISSUE TITLE
Include Chrome and Edge extended stable

### ISSUE THREAD

**Issue by taymonbeal** [mdn/browser-compat-data#17257]
Chrome now has an [extended stable](https://chromium.googlesource.com/chromium/src/+/master/docs/process/release_cycle.md#extended-stable) release channel analogous to Firefox's ESR. This isn't reflected in this repo; when Chrome 103 was released, Chrome 102 was marked as "retired", even though it was still getting another four weeks of security updates.

[This also applies to Edge.](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-channels#extended-stable-channel)

**Comment by foolip** [comment]
@taymonbeal do you intend to use this information in some way if it's added to BCD? It would be a slight additional effort to maintain, and we'd want to make sure some consumer of BCD wants it.

**Comment by taymonbeal** [comment]
I wound up getting it directly from Chrome's releases API instead.

**Comment by queengooborg** [comment]
Out of curiosity, what is your use case for the Chromium ESR data?

**Comment by taymonbeal** [comment]
Tracking what versions of browsers we need to maintain compatibility with.

**Comment by queengooborg** [comment]
I'm not sure I understand the use case (and the minimal details provided don't help much), however since you mentioned that Google's API does the trick for you (and nobody else has requested this), I'm going to go ahead and close this issue.  If another user asks for this data to be added to BCD, I'll look into it once again!
