### ISSUE TITLE
css.types.color.color-mix - no longer experimental

### ISSUE THREAD

**Issue by svgeesus** [mdn/browser-compat-data#17335]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

`color-mix()` is flagged as experimental, which used to be correct.

However, on June 15 2022 [CSS WG resolved that `color-mix()` was cleared to ship, ahead of Candidate Recommendation](https://github.com/w3c/csswg-drafts/issues/7310#issuecomment-1156717607). This means it is no longer experimental and no longer expected to change much, if at all.

The [CSS snapshot 2022](https://drafts.csswg.org/css-2022/) has been updated to add `color-mix()` to the [list of Safe to Release pre-CR Exceptions](https://drafts.csswg.org/css-2022/#CR-exceptions).

Following those resolutions, Safari Technical Preview 151 was just released with `color-mix()` enabled (no longer behind a flag).

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

(see links above)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.types.color.color-mix`
* Report started: 2022-08-13T11:21:38.183Z

</details>

**Comment by queengooborg** [comment]
Thanks for the information!  However, we base experimental status on how many browsers have implemented the feature and included it by default in a stable release (that is, not hidden behind a flag or in a beta/TP release).  Since the only two browsers (Firefox and Safari) that have implemented and shipped the feature in a stable release have done so behind flags, the feature is still to be considered experimental.

**Comment by svgeesus** [comment]
Thanks for the clear explanation.
