### ISSUE TITLE
html.elements.input.type_date - Ignores position in viewport and overflows browser border

### ISSUE THREAD

**Issue by moeatsy** [mdn/browser-compat-data#17411]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

When we put the input element to the bottom of a page and click it to expand calendar, in Safari the calendar's popover will ignore position inside viewport and overflow bottom border of the browser. So users with maximized Safari window will not be able to choose any date.

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

I expected same behavior as in chrome, calendar popover to be over input element.

### MDN URL

https://developer.mozilla.org/ru/docs/Web/HTML/Element/Input/date

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.input.type_date`
* Report started: 2022-08-17T15:24:29.922Z

</details>

**Comment by queengooborg** [comment]
Hi @moeatsy!  I can confirm the overflow issue on my end, however I don't think that it's significant enough to document in BCD.  It's a small UI bug that's observable under specific circumstances, and otherwise the input works just fine.

I would recommend opening a bug with WebKit at https://bugs.webkit.org instead, so the Safari engineers know that this is something that should be fixed!
