### ISSUE TITLE
SVG oncancel- broken link

### ISSUE THREAD

**Issue by MrBrain295** [mdn/browser-compat-data#17523]
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/Events

### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

The MDN link on the `oncancel` [this page](https://github.com/mdn/browser-compat-data/blob/main/svg/attributes/events.json) is broken.

### What did you expect to see?

A working link.

### Did you test this? If so, how?

I tried to open the link and it gave a 404 error.

**Comment by queengooborg** [comment]
I moved this issue over to mdn/content so that the page can be created, but after looking deeper into this, I actually think that this entire set of data should be removed, both on BCD and content.  Looking through, the list of event attributes seems to perfectly match GlobalEventHandlers, of which we had removed a while back.

I'll bring this up during the next content planning meeting!

**Comment by Elchi3** [comment]
Yeah let's close this.
