### ISSUE TITLE
__meta lacks schema documentation

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#17574]
I'm working with BCD for the first time in about four months and there's been a number of breaking changes since then, but so far some seem to be un- and under-documented.

Since v4, there's a new top-level (and maybe elsewhere?) key: `__meta`. Unlike the browsers and compat data, there's no associated JSON Schema or schema documentation for the meta object.

Key questions, as a consumer:

- Can I trust that the keys described in the README are the only keys that will ever appear? Are either optional?
- Is the meta object or its properties part of the semantic versioning scheme?
- Should I expect the `__meta` object to ever appear elsewhere in the structure? (e.g., is it like the `__compat` notation, in that it will denote a kind of structure underneath it, to be used in multiple contexts?)

**Comment by queengooborg** [comment]
Hey Daniel -- first of all, welcome back!

Due to the fact that the `__meta` key is only applied to the top level during the build process and it is applied to the top level of the data, creating a schema definition for it didn't seem like the best option since there's no schema to validate the final build.  I figured that https://github.com/mdn/browser-compat-data#__meta would be the best place to document this, as the object is top level and, yes, is covered by semver policies.

> Can I trust that the keys described in the README are the only keys that will ever appear? Are either optional?
> Is the meta object or its properties part of the semantic versioning scheme?

Yes, the `__meta` are covered by the semver policy and any new keys added to it will result in a minor semver bump.  In turn, any removals of the keys will result in a _major_ bump.  All properties will always be present in the built package data.

> Should I expect the `__meta` object to ever appear elsewhere in the structure?

No, this object will _only_ be present at the top level of the BCD package -- and that's why it was not documented in the schema.  This object will not be found anywhere else.

Hope this helps!

**Comment by queengooborg** [comment]
I'm going to close this issue since again, this object is not applicable to the spec, and I feel that all the questions are answered in the readme already.  Let me know if you have any additional questions!
