### ISSUE TITLE
mathml.elements.math - out-of-date compatibility table

### ISSUE THREAD

**Issue by duckwork** [mdn/browser-compat-data#17578]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

I think the data is quite out of date --- caniuse.com has [info for much newer versions](https://caniuse.com/mathml).

### What did you expect to see?

Up-to-date informatoin

### Did you test this? If so, how?

I looked at it and I looked at caniuse.com and they were very different.

### Do you have anything more you want to share?

Thanks for this resource!

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/MathML

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `mathml.elements.math`
* Report started: 2022-08-27T03:29:47.825Z

</details>

**Comment by queengooborg** [comment]
We tend to try and avoid adding data for unreleased browser versions, as the version number can change.  Even now, CanIUse's data is now inaccurate per the source they link, which states that release is _estimated_ to be in Chrome 108: https://chromestatus.com/feature/5240822173794304

**Comment by duckwork** [comment]
AFAICT the data was out-of-date for even released versions; MDN ends at Chrome 25, Firefox 4, etc. Those browsers are currently at 104 and 91 respectively, and that's on Debian. Maybe I'm misunderstanding browser versions; I know they're really silly.

**Comment by queengooborg** [comment]
Ah, I see where the confusion is: unlike CanIUse, we don't list every browser version in the compatibility tables.  If you see "45" as the version number on a table, that means that the feature was added in version 45 and supported since, including the current version!  Whereas if you see "24-25", that means the feature was "added in 24 and removed in 25".  The green check or red X in each cell will let you know if the feature is supported or not in the current version of the web browser!

**Comment by duckwork** [comment]
Ohhhhhh! Thanks <3
