### ISSUE TITLE
api.XMLHttpRequest - XMLHtttpRequest is not working in iOS

### ISSUE THREAD

**Issue by vivekvelineni** [mdn/browser-compat-data#17963]
### What type of issue is this?

Incorrect support data XMLHttpRequest() is not working on IOS

### What information was incorrect, unhelpful, or incomplete?

XMLHttpRequest() is not working on IOS. It is deprecated from IOS 13 update

### Did you test this? If so, how?

I have created a website that uses XMLHttpRequest(), it works in windows, macOS, and Android but not in ios.
Here is the link to the site: https://yt-playlist-video-duration-calculator.vercel.app/

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.XMLHttpRequest`
* Report started: 2022-10-08T17:35:33.522Z

</details>

**Comment by fwebdev** [comment]
I doubt that they removed XMLHttpRequest in iOS 13. Our pages are using this heavily without Problem. Maybe there is an Missunderstanding

**Comment by queengooborg** [comment]
It sounds like it's probably a development issue rather than a browser issue.  It doesn't sound right for something as widely used as XHR to be deprecated in a browser, especially specifically a mobile variant.  Additionally, a tool we use all the time for BCD uses XHR for some of its critical functions, so if it _were_ deprecated and removed, we'd know pretty quickly.
