### ISSUE TITLE
Chrome 108 should mirror to Opera 94, but it doesn't

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/browser-compat-data#18224]
In https://developer.mozilla.org/en-US/docs/Web/API/MediaSource#browser_compatibility, The Chrome 108 data mirrors Opera support to version 93, but I've just checked and Opera 94 is based on Chrome 108.

**Comment by chrisdavidmills** [comment]
Hrm, I'm confused now. Looking at https://github.com/mdn/browser-compat-data/blob/main/browsers/opera.json, Opera 94's engine version is set to 108, which is where I'm assuming where the mirror data gets taken from...so how come version 93 is mirrored in the version referenced above?

Is this because the new Opera version was only just added... see https://github.com/mdn/browser-compat-data/commit/bc145de20f2180455f37c73ad2b490492d676799 ?

**Comment by queengooborg** [comment]
I believe this is because of the way that the mirroring script handles beta/nightly releases, see https://github.com/mdn/browser-compat-data/blob/b626adc774876722f2e49fa6f2e10a0989c2883a/scripts/release/mirror.ts#L108-L111.  Since Chrome 108 and Opera 93 are both the beta release of the browser, it's mapping them together.  This was done because of Safari iOS beta releases, I believe, but now that we have `preview`, we no longer need this, so I'll submit a PR to fix this!

**Comment by chrisdavidmills** [comment]
@queengooborg this is great, thanks a lot!
