### ISSUE TITLE
api.MediaMetadata.artwork - Compability with Safari on iOS 16 is missing

### ISSUE THREAD

**Issue by rthymis** [mdn/browser-compat-data#18239]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Compability with Safari on iOS 16 is missing. 

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet), Firefox, Safari

### What did you expect to see?

Compability information about Safari on iOS 16.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/MediaMetadata/artwork

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.MediaMetadata.artwork`
* Report started: 2022-11-18T22:16:50.428Z

</details>

**Comment by queengooborg** [comment]
This issue is confusing.  What do you mean by "missing compatibility data with Safari 16?"  Is the feature incompatible with Safari 16 and you were expecting to see that represented in the data?  Is there some other issue with Safari 16 that's not represented?

I'm assuming you're probably thinking that the "15" that shows up means "we've tested support up to Safari 15" or something like that, and are simply misreading the tables.  The version number that's shown on the tables is the earliest version that supports this feature, so "15" means "supported from Safari 15 to current version".

**Comment by rthymis** [comment]
I was indeed misreading the tables. Thank you for making it clear.
