### ISSUE TITLE
api.Element.requestFullscreen - Not working in Angular PWA App for IOS Device only

### ISSUE THREAD

**Issue by gmgodhani** [mdn/browser-compat-data#18440]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Angular PWA App not working Javascript requestFullscreen() for IOS Device only

### Did you test this? If so, how?

`if (element.requestFullscreen) {
      element.requestFullscreen();
    } else if (element.msRequestFullscreen) {
      element.msRequestFullscreen();
    } else if (element.mozRequestFullScreen) {
      element.mozRequestFullScreen();
    } else if (element.webkitRequestFullscreen) {
      element.webkitRequestFullscreen();
    }`

### Do you have anything more you want to share?

In Angular PWA App, I have to make div toggle for Full screen and Exit Full Screen.

For this, I have used this code But **this is not working as App mode in IOS Device**. Any Idea?

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.requestFullscreen`
* Report started: 2022-12-15T04:46:02.490Z

</details>

**Comment by queengooborg** [comment]
The compatibility note says that this only works on iPadOS, not iOS (AKA, iPad, not iPhone).  Are you using an iPhone or an iPad?  If you're using an iPhone, support has not been implemented.

**Comment by gmgodhani** [comment]
Hey @queengooborg I'm using PWA App in IPad.

**Comment by queengooborg** [comment]
Gotcha -- I just did some more digging into Angular PWA, and I see that it offers a system like React Native where you can create and install a separate mobile app, and that's what you're having troubles with, right?

Unfortunately, we don't track compatibility data for other iOS and iPadOS browser-based apps, primarily due to the high effort to low demand ratio.  I would recommend raising an issue with Angular or comment on an existing issue on their repository.
