### ISSUE TITLE
"ping-other-repos" workflow fails on Dependabot commits

### ISSUE THREAD

**Issue by queengooborg** [mdn/browser-compat-data#18565]
### What type of issue is this?

Infrastructure issue

### What is the issue?

The `ping-other-repos` workflow fails on all commits authored by Dependabot.  Looking closely, it seems that the token is not passed into the workflow for Dependabot commit.

Dependabot: https://github.com/mdn/browser-compat-data/actions/runs/3854711506/jobs/6568995481
Other Author: https://github.com/mdn/browser-compat-data/actions/runs/3854109447/jobs/6567746489

CC @sideshowbarker

### What behavior were you expecting?

It's odd to see the token not getting passed into commits authored by Dependabot.  I wonder why...

### What version(s) of BCD is the issue present in?

- [ ] The current BCD release
- [X] The current version of the `main` branch

**Comment by sideshowbarker** [comment]
Since we don’t need the "ping-other-repos" workflow to run for dependabot merges anyway, I think we can deal with this by having the workflow check if the `github.actor` is `dependabot[bot]` — and if so, then doing an early return to bail out of the workflow and completely skip the actual workflow steps. So I opened #18568 with a change which does that.
