### ISSUE TITLE
css.properties.filter - SVG support data is incorrect

### ISSUE THREAD

**Issue by estelle** [mdn/browser-compat-data#18917]
### What type of issue is this?

Incorrect support data (ex. Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

There is a BCD support row for the `filter` property "On SVG elements".

`filter` works on `<SVG>` elements and  the`<path>` element in Edge and other browsers. See https://codepen.io/estelle/pen/rNZNqaK. I am not sure if this line is incorrect. Or, if support is correct, to what this line is referring.

### What did you expect to see?

A more information table row header or more accurate support information

### Did you test this? If so, how?

Created a codepen and looked at it in other browsers. https://codepen.io/estelle/pen/rNZNqaK

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/filter

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.filter`
* Report started: 2023-02-15T00:46:24.911Z

</details>

**Comment by foolip** [comment]
I found my way here via https://github.com/mdn/browser-compat-data/pull/21569 when trying to determine exact versions and remove the ranged versions.

Chrome didn't support the CSS `filter` property on SVG elements, tracked by this bug, fixed in Chrome 89:
https://issues.chromium.org/u/1/issues/40134524

Testing https://codepen.io/estelle/pen/rNZNqaK in Chrome 88 and 89 confirms this. I also tested https://software.hixie.ch/utilities/js/live-dom-viewer/?saved=12923 and got the same results, it starts working in Chrome 89.

The WebKit bug remains open: https://bugs.webkit.org/show_bug.cgi?id=246106

I'll send a PR to fix this data.
