### ISSUE TITLE
Servo is missing in JS and HTML browser version information 

### ISSUE THREAD

**Issue by nathaniel-watson-ctg-com** [mdn/browser-compat-data#19036]
### MDN URL

https://github.com/jdm/servo-embedding-example 

### What specific section or headline is this issue about?

Browser compatibility

### What information was incorrect, unhelpful, or incomplete?

All of the tables like this that I can find on MDN are missing Servo. It makes it difficult to determine if Servo is supported for a particular feature. 

### What did you expect to see?

I expect Servo to be listed at least as a desktop browser environment with accurate version information where available, with the usual "?" symbol for unknown cases.

**Comment by queengooborg** [comment]
I'm not opposed to adding data for Servo to BCD, however this would be a big project and there are a number of issues that currently prevent us from doing so:

- Downstream-consumer interest
  - There has been very little interest in Servo being documented in BCD (in fact, this is the only relevant issue that I can find).  Due to the massive undertaking of researching a new web browser, we'd need more consumer interest to be able to justify the time and effort it takes to add it in.
- Reviewers
  - We'll need committed, long-term reviewers to verify the Servo data and ensure that it's accurate.  And given we're struggling to review the browsers we _currently_ document...
- Release cycle
  - Servo doesn't seem to have any official alpha/beta/stable releases; it's only been nightly builds.  Until it follows a release cycle with set versioning, we won't be able to track features well.
- Documentation
  - While there is documentation for Servo, it's focused more on the backend, it looks like.  There isn't a lot regarding the web APIs available to end users, and as such, not a lot of data we can reference.

See https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/browsers.md#addition-of-browsers for more details on how we decide to add new browsers.

I'm going to close this for now, but once again, it's an interesting idea!
