### ISSUE TITLE
URL points to 404

### ISSUE THREAD

**Issue by frenic** [mdn/browser-compat-data#1998]
This URL leads to a 404. Not sure if the problem is that the URL exists or if the page is mistakenly missing.

https://github.com/mdn/browser-compat-data/blob/38807cca2f47417a8ee2d81fd38b09a3823641ff/css/properties/appearance.json#L6

**Comment by connorshea** [comment]
[`-moz-appearance`](https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-appearance) is the "proper" page as far as I can tell, I'm not sure why it's called that instead of `appearance`, since it tracks `appearance` and `-webkit-appearance` anyway. Maybe `appearance` should redirect to that, or the page should to be moved?

It should also be noted that the feature isn't standardized yet and seems to have run into some trouble in the W3C. https://drafts.csswg.org/css-ui-4/#appearance-switching

**Comment by connorshea** [comment]
Also, it should be noted that a lot of the MDN URLs lead to 404s ¯\_(ツ)_/¯

**Comment by connorshea** [comment]
I wrote a Ruby script that checks all the MDN URLs in the dataset for 404s, here are the results:
https://gist.github.com/connorshea/7d20a96cfee35addbbf944ceb04a25a8

**Comment by connorshea** [comment]
Turns out a Node script was written to do the same thing in #1703 :D

**Comment by connorshea** [comment]
@ddbeck this can probably be closed?

**Comment by ddbeck** [comment]
Yeah, I think there are lots of MDN pages that we allow to have broken `"mdn_urls"` on the basis that those pages _should_ exist, but don't. This is one of those cases. But thank you for the report @frenic and the follow up comments, @connorshea. 👍
