### ISSUE TITLE
Add extensions to collector-report.schema.json

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#20102]
### What type of issue is this?

Schema issue

### What is the issue?

In https://github.com/mdn/browser-compat-data/pull/19941#discussion_r1204487252 @queengooborg reported that https://github.com/GooborgStudios/mdn-bcd-collector can take into account changes that extensions make to web-exposed APIs, and that is should be part of the schema.

However, in https://github.com/GooborgStudios/mdn-bcd-results the `extensions` property is always an empty array, so we don't have a concrete example to work from. @queengooborg's schema suggestion says that it's an array of strings, which would be simple enough to enforce, but what should the update script to with the array of strings?

**Comment by queengooborg** [comment]
> what should the update script to with the array of strings?

In the root of the collector, there is a file called `browser-extensions.json` which contains data regarding all of the known browser extensions that cause issues with feature detection.  Inside of it, there is a key called `affectedTests` which lists the BCD features that are affected by the browser extension.  If an extension is detected and its ID is listed in the `extensions` property of a report, the `update-bcd` script should ignore any results for the listed BCD features and its subfeatures (in other words, treat them as `null`), so that they do not affect the output.

**Comment by queengooborg** [comment]
Also, the `extensions` property is defined in the schema file already it looks like.

**Comment by foolip** [comment]
Oh, I guess @mzgoddard took your suggestion but had questions about it 😃
