### ISSUE TITLE
http.headers.Content-Security-Policy.report-to - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by psrdotcom** [mdn/browser-compat-data#20185]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Chrome current version - 114.0 but support was added till 79. Firefox version is old with unsupported CSR report-to.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet), Firefox, Legacy Edge (12-18), Safari, Node.js, Deno

### What did you expect to see?

Updated versions of respective browsers

### Did you test this? If so, how?

By checking the browser versions

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Content-Security-Policy.report-to`
* Report started: 2023-06-21T15:16:59.110Z

</details>

**Comment by queengooborg** [comment]
It is unclear what you think is incorrect about our current data and what you would like to see changed in BCD.  If there is an issue with our data, please provide a precise explanation of what you think is incorrect (ex. "this was supported in Firefox since 104, but the data says it's unsupported", or "the tables say support was added in Chrome 90, but support was added in Chrome 70").  Closing as there is no actionable information.
