### ISSUE TITLE
Are we documenting the WebAssembly JS API in the right place?

### ISSUE THREAD

**Issue by queengooborg** [mdn/browser-compat-data#20349]
While going through the WebAssembly JavaScript API, I happened to notice that the spec is written like an API specification, rather than a JavaScript specification.  If we compare https://tc39.es/ecma262/multipage/#sec-intro and https://tc39.es/ecma402/#introduction, we see that they are structured identically; https://webassembly.github.io/spec/js-api/, on the other hand, is not structured the same way.

The specification also documents interfaces, namespaces, dictionaries and enums in WebIDL just like an interface.

Given this, I'm wondering if it makes sense for us to move all that data from `javascript.builtins.WebAssembly` to `api.WebAssembly`.

**Comment by Josh-Cena** [comment]
Cross-linking https://github.com/orgs/mdn/discussions/151.

Wasm is maintained by W3C, not TC39, so they will surely use W3C spec conventions.

I don't feel as strongly about BCD structure as content structure. This is because Wasm is implemented by the JavaScript engine (V8, etc.) instead of the host (Chromium, etc.), so updates are delivered at the same pace as JS features, so it somewhat makes sense to put them together. At the same time, the webassembly part of BCD doesn't look nearly as structured at the moment. If we want to maximally reflect content structure, we would still want to put it under https://github.com/mdn/browser-compat-data/tree/main/webassembly, though, because it's not a web API.
