### ISSUE TITLE
api.CanvasRenderingContext2D.createConicGradient - Washed-out colors in Firefox

### ISSUE THREAD

**Issue by SimunOnio** [mdn/browser-compat-data#20953]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

Only in Firefox, ctx.createConicGradient() method makes colors look desaturated and washed out.

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

From mdn web docs example:
In Firefox
![Fy333](https://github.com/mdn/browser-compat-data/assets/127319486/819fb7dd-770d-4d54-af19-6c410959a781)

In Chrome
![idSY4](https://github.com/mdn/browser-compat-data/assets/127319486/e1674e18-261c-4aa5-86a1-c96c2d377e2c)

### Did you test this? If so, how?

Opened mdn web docs example in Firefox and Chrome.

It works in Firefox if browser settings are changed:
gfx.canvas.accelerated](about:config => gfx.canvas.accelerated => true

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createConicGradient

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.CanvasRenderingContext2D.createConicGradient`
* Report started: 2023-10-12T19:43:57.899Z

</details>

**Comment by queengooborg** [comment]
I was not able to reproduce this issue in Firefox on my local system or in BrowserStack.  I believe that this is a hardware-specific issue, possibly due to bad drivers or other such issues.  I'd recommend reporting this to [Bugzilla](https://bugzil.la) if it hasn't already been reported, and include details of your hardware configuration.
