### ISSUE TITLE
Navigator:userAgentData - Not Available on MacOS or iOS in any browser, including Chrome

### ISSUE THREAD

**Issue by sidewayss** [mdn/browser-compat-data#21308]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Incorrect/Incomplete: Based on my tests on the latest versions of the OSes and browsers, `navigator.userAgentData` is not available on any browser in MacOS or iOS, including Chrome. Here is the relevant section of the MDN page:

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgentData#browser_compatibility

Here is the caniuse.com page: https://caniuse.com/?search=navigator.useragentdata

I don't know how to make those edits here, or what edits to make. Should it be a numbered footnote? Should the green color on caniuse.com be that olive green instead of the bright green? How is that indicated in the JSON here? Chrome is the only browser that is incorrectly labeled, but maybe it should be a more global note. fyi - I have contributed to MDN/content, but not to this project, so I'm interested in how things work here as well.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

I expect to see a footnote about Chrome on iOS/MacOS or a global note of some kind about those operating systems.

### Did you test this? If so, how?

I tested it on browserstack.com using the latest iOS, MacOS and Chrome.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgentData#browser_compatibility

### Do you have anything more you want to share?

I can share screenshots of my Watch results in the debugger if you like.

**Comment by wbamberg** [comment]
I can see `userAgentData` in Chrome on macOS:

<img width="649" alt="Screen Shot 2023-11-29 at 9 58 15 AM" src="https://github.com/mdn/browser-compat-data/assets/432915/f0af3ab5-8a0e-4e5a-9a9d-308b8e824363">

**Comment by queengooborg** [comment]
The reason that Chrome on iOS doesn't support `navigator.userAgentData`, even though Chrome on Desktop and Chrome on Android do, is because it's not _actually_ Chrome.  All browsers on iOS and iPadOS use WebKit (Safari) as it is integrated directly into the operating system, so regardless of whether the UI is Chrome, Firefox or some third party, it's still Safari in the background.

If the label is changed from `Safari on iOS` to just `iOS` (or `iOS/iPadOS`), then that might provide better clarity to developers.  I'm going to close this issue since there isn't any issue with the support data for `navigator.userAgentData`.

**Comment by joseph-tech-dev** [comment]
Also in Firefox Linux, it is not available.

<img width="1247" height="167" alt="Image" src="https://github.com/user-attachments/assets/e91f99c7-648d-48ff-a9b4-c7a048b496c3" />
