### ISSUE TITLE
html.elements.hr - iOS Safari 17.x supports the feature, Android Chrome doesn't

### ISSUE THREAD

**Issue by dfabulich** [mdn/browser-compat-data#22725]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hr#browser_compatibility the `<hr>` in `<select>` feature contains incorrect data.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet), Safari

### What did you expect to see?

This feature should have at least partial support in iOS Safari 17.4 (probably iOS Safari 17.0), and, as far as I can tell, it has no support on Android Chrome at all

### Did you test this? If so, how?

Apropos #21648 I tested https://adrianroselli.com/demos/splitting-within-selects/index.html

There, I clicked/tapped on the "Select a major" example, and checked only visually. (I did no a11y testing.)

* Chrome 123 / macOS Sonoma 14.4: exposes the `<hr>` visually in the page
* Safari 17.4 / macOS Sonoma 14.4: exposes the `<hr>` visually in the page
* Chrome 123 / Android 13: does not expose the `<hr>` visually in the page (contradicting @aardrian's findings)
* Safari 17.4 / iOS 17.4: exposes the `<hr>` visually in the page
* Safari 17.4 / iPadOS 17.4: exposes the `<hr>` visually in the page (contradicting @aardrian's findings)

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

The Chrome team announced that `<hr>` in `<select>` had come to Chrome 119, with no mention that it doesn't work on Android. https://developer.chrome.com/blog/hr-in-select/

The Safari team announced that `<hr>` in `<select>` had come to Safari 17. In #21648, @aardrian tested this in "Safari 17" (presumably Safari 17.0) and find that it worked on macOS 14.0, but not on iPadOS 17.0.3. That really doesn't make sense to me; it makes me wonder whether @aardrian was somehow accidentally testing the wrong version of Safari/iPadOS…?

### Do you have anything more you want to share?

A screenshot of it not working on Chrome 123 / Android 13:

![Screenshot_20240327_172525](https://github.com/mdn/browser-compat-data/assets/96150/c2d3d8e2-b0a9-4279-abaf-165e327372d8)

A screenshot of it working on iOS Safari 17.4:

![Simulator Screenshot - iPhone 15 - 2024-03-27 at 18 01 42](https://github.com/mdn/browser-compat-data/assets/96150/0b143c6c-20d9-4380-a1a8-0ecc055c3a17)

**Comment by aardrian** [comment]
@dfabulich 

> - Chrome 123 / Android 13: does not expose the `<hr>` visually in the page (contradicting @aardrian's findings)

That does not contradict my findings. It's a different result using a different browser release. As [I note in the post](https://adrianroselli.com/2023/10/splitting-within-selects.html#HR-Mobile), I tested Chrome Canary (120) / Android 13. That is a different release than what you tested.

> - Safari 17.4 / iPadOS 17.4: exposes the `<hr>` visually in the page (contradicting @aardrian's findings)

That does not contradict my findings. It's a different result using a different browser release. As [I note in the post](https://adrianroselli.com/2023/10/splitting-within-selects.html#HR-Mobile), I tested Safari on iPadOS 17.0.3. That is a different release than what you tested.

> The Safari team announced that `<hr>` in `<select>` had come to Safari 17. In https://github.com/mdn/browser-compat-data/issues/21648, @aardrian tested this in "Safari 17" (presumably Safari 17.0) and find that it worked on macOS 14.0, but not on iPadOS 17.0.3. That really doesn't make sense to me; it makes me wonder whether @aardrian was somehow accidentally testing the wrong version of Safari/iPadOS…?

It doesn't make sense to you because you are assuming the Safari release is not tied to the iDeviceOS release. Technically I tested Safari 17.0.3 and you tested Safari 17.4.

I have since upgraded my iDevice, so I cannot provide a screen shot. I have not updated Chrome Canary on my Android, so I _can_ provide a screen shot, which follows.

Observe how it exposes the `<hr>` as its own empty selectable option. You asserted I claimed it "does not expose the `<hr>` visually in the page", though the prior sentence is what I wrote in the post (because I copied it from there).

![A select menu expanded to show two entries that have no visible text but still take up space and have the circle on the right that indicates if they are selected.](https://github.com/mdn/browser-compat-data/assets/1376607/8fa4b33e-a462-4bfa-b183-96dafc9f664f)

![Chrome Canary version screen showing Canary 120.0.6084.0 on Android 14, Pixel 6](https://github.com/mdn/browser-compat-data/assets/1376607/01a4caa7-8d69-4514-b9b4-03c01fa60e03)

Anyway, this issue is really about more recent support than my testing. It should be filed as that since there is no evidence that what I reported for the versions I tested was wrong. If you have evidence (by testing the specific versions I tested), then please add it. Otherwise consider renaming and re-scoping this issue (especially since Safari 17.x supporting it is not accurate).

**Comment by dfabulich** [comment]
I'm going to close and re-file this issue as two issues, to distinguish the two topics.

**Comment by dfabulich** [comment]
Split off #22729 and #22730.
