### ISSUE TITLE
css.selectors.any-link - Related bug in Webkit mentioned has been marked as resolved.

### ISSUE THREAD

**Issue by papparappa** [mdn/browser-compat-data#22794]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

"Safari currently matches <link> elements with link pseudo-classes. See [bug 220740](https://webkit.org/b/220740)."

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

The bug in question was marked as a duplicate of [this one](https://bugs.webkit.org/show_bug.cgi?id=227847) which in turn has been marked as "RESOLVED FIXED"

### Did you test this? If so, how?

Didn't test it on CodePen but the ticket in question mentions that the tests are passing on Safari:
https://wpt.fyi/results/html/semantics/selectors/pseudo-classes/link.html?label=master&label=stable&aligned

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

Relevant MDN Page: https://developer.mozilla.org/en-US/docs/Web/CSS/:any-link
Bug Ticket referenced in it: https://bugs.webkit.org/show_bug.cgi?id=220740

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:any-link

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.selectors.any-link`
* Report started: 2024-04-07T21:44:40.545Z

</details>

**Comment by razrdev** [comment]
Just in case, i've double-checked on my Mac in the meantime, and it does ignore the `<link>` element when using the pseudo-class in question with `querySelectorAll`

<img width="1327" alt="Screenshot 2024-04-08 at 14 50 51" src="https://github.com/mdn/browser-compat-data/assets/165213283/a8be149e-54df-4935-853e-1b550ecea1ee">

**Comment by razrdev** [comment]
I double-checked in the meantime on my Mac just in case, and it does not seem to render the `<link>` element(s) when using the pseudo-class in question with `querySelectorAll` on Safari. 
Due to the wording of the bug described in MDN i've also checked the `:link` pseudo-class in addition to `:any-link` and both of them do not select the `<link>` elements on the page, only the `<a>` elements.

<img width="1327" alt="Screenshot 2024-04-08 at 14 50 51" src="https://github.com/mdn/browser-compat-data/assets/165213283/9daea3e2-703f-4749-9c28-7be6fb333dc8">
