### ISSUE TITLE
Best way to do spec integration

### ISSUE THREAD

**Issue by marcoscaceres** [mdn/browser-compat-data#2306]
I'd like to figure out the best way to keep data in sync as we add new attributes, methods, etc. to specs.

**Comment by Elchi3** [comment]
A starting point could be https://github.com/dontcallmedom/webidl2mdnbcd which can create or update compat JSON files from WebIDLs.

**Comment by marcoscaceres** [comment]
Tagging @dontcallmedom. We might pick this up again during TPAC.

**Comment by digitarald** [comment]
@atopal could this be prioritized, or other ways to ensure that compat-data updates in lockstep with fast-moving browsers?

Background: With compat-data being considered for audits, https://github.com/webhintio/hint/issues/30#issuecomment-419248957 discusses some concerns on keeping it synchronized with browser releases. Happy to provide more input if needed.

**Comment by ddbeck** [comment]
This issue is a couple of years inactive now and there hasn't been much discussion about it. While I don't think we've satisfied this issue, I don't think it's clearly defined enough to say what done would look like in any case. I'm going to close this, but if I'm wrong on this, please reopen—or open a new issue—with any ideas you may have. Thanks!

**Comment by jpmedley** [comment]
I've never supported using spec IDL as a guide for updating BCD or MDN. Spec are unreliable proxies for what's implemented in browsers. New specs can be highly volatile.
