### ISSUE TITLE
javascript.builtins.Intl.NumberFormat.NumberFormat - options.numberingSystem support listed incorrectly

### ISSUE THREAD

**Issue by EdgarPl** [mdn/browser-compat-data#23122]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

options.numberingSystem parameter listed as having full support on desktop Firefox 29

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

The option is supported starting Firefox 76

### Did you test this? If so, how?

Tested with "ar-EG" and "ar" locales
1. on Windows Firefox 75:
![Screenshot 2024-05-17 142011](https://github.com/mdn/browser-compat-data/assets/38721905/b40cf558-0ebd-40f1-bcfd-d54f661bdbf9)
2.  working as expected on FF 76 Mac in browserstack

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Intl.NumberFormat.NumberFormat`
* Report started: 2024-05-17T11:02:20.364Z

</details>

**Comment by Josh-Cena** [comment]
There are two things wrong here:

1. `numberingSystem` should be an option of the constructor, not an option of `format`.
2. The only way to test whether `Intl` supports an option is to query `resolvedOptions`. Otherwise, the output may simply be due to lack of data.

Here's the output:

<img width="549" alt="image" src="https://github.com/mdn/browser-compat-data/assets/55398995/50cbe8c2-57dc-4ba9-add5-ae51ef6bda8e">

Therefore Firefox 75 does support `numberingSystem`. It's just that `ar-EG` data did not have the `nu-latn` combination.

**Comment by EdgarPl** [comment]
1. My apologies, I've corrected the screenshot in testing steps to match the actual steps used.
2. I see, that makes sense. Is there any way to detect which numberingSystems are supported beyond checking the resolved options after trying to apply them? 
Locale accessor `numberingSystems` returns `["arab"]` on browsers that resolve the `numberingSystem: "latn"` option which seems to me like it contradicts the notes here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#numberingsystem 
Win/Chrome 125:
![Screenshot 2024-06-12 160604](https://github.com/mdn/browser-compat-data/assets/38721905/7208e6d9-728f-436e-aab1-09741f7f3cbb)

**Comment by Josh-Cena** [comment]
@EdgarPl 

`Locale#numberingSystems` returns the list of numbering systems that are commonly used in the locale. It doesn't necessarily mean the formatter only supports using those particular combinations. When the doc says "For a list of supported numbering system types" it means to refer to the complete table for all values that are considered valid.

> Is there any way to detect which numberingSystems are supported beyond checking the resolved options after trying to apply them?

I'm not sure either, as I'm not an expert on the CLDR data format. In fact, I believe it may be a non-issue in the latest browser version, because the data uses templates that gets filled in with any numbering system you want. For example, `ar-EG` with the `hanidec` (Positional decimal system using Chinese number ideographs as digits) numbering system is an obviously nonsensical combination, but Chrome formats it anyway:

```js
new Intl.NumberFormat("ar-EG", { numberingSystem: "hanidec" }).format(1234)
// 一,二三四
```

`resolvedOptions` also doesn't indicate whether data is available. You may specify a non-sensical combination that doesn't have data, which will cause fallback when calling `format`, but this fallback won't be reflected by any other means.

**Comment by queengooborg** [comment]
We don't track what specific numbering formats or locales are supported in browsers, at least not yet.  As such, I'm going to close this issue.
