### ISSUE TITLE
css.properties.caption-side - incorrect values

### ISSUE THREAD

**Issue by estelle** [mdn/browser-compat-data#23245]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

There are four possible values: inline start, inline end, top, and bottom.

### What did you expect to see?

the values that are in the specifictions:

https://drafts.csswg.org/css-logical/#caption-side
https://drafts.csswg.org/css2/#propdef-caption-side

### Did you test this? If so, how?

no

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/caption-side

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.caption-side`
* Report started: 2024-06-04T03:05:22.098Z

</details>

**Comment by queengooborg** [comment]
It appears that no browser supports `inline-start` or `inline-end`, so they're not tracked in BCD.  The other four values were non-standard, and they were supported in Firefox and [Safari](#23557) at one point, but don't appear to be supported any longer.

I created a collector PR to add tracking for the two `inline` values, so that if support is added in some version, they'll be tracked accordingly!

**Comment by estelle** [comment]
thanks!
