### ISSUE TITLE
api.Document.parseHTMLUnsafe_static - Incorrect Firefox support version

### ISSUE THREAD

**Issue by woody-li** [mdn/browser-compat-data#23354]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Firefox supports data

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

Correct data for the real shipping version and optional description.

### Did you test this? If so, how?

Current support version is 123.

Tested at 124, it throws error: https://bugzilla.mozilla.org/show_bug.cgi?id=1887817
Version 126 and 127 doesn't throws error, but returns a "Restricted Object", and cannot visit any property.

Dev 128 and Nightly 129 works fine.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document/parseHTMLUnsafe_static

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Document.parseHTMLUnsafe_static`
* Report started: 2024-06-12T03:07:25.423Z

</details>

**Comment by hamishwillee** [comment]
The data comes from https://mdn-bcd-collector.gooborg.com/tests/api/Document/parseHTMLUnsafe_static , which matches what the BCD currently says.

My _understanding_ is that 
- this tool tracks the WebIDL - i.e. the presence properties/methods on the corresponding object. 
- BCD doesn't track bugs as such - so even if a feature doesn't work correctly due to a bug we don't indicate the sub versions where that is true. This is a pragmatic decision.

@Elchi3 @queengooborg Is that correct? ^^^ - should we update to the fixed version for Firefox since the BCD data is "deceptive".

**Comment by queengooborg** [comment]
> * this tool tracks the WebIDL - i.e. the presence properties/methods on the corresponding object.

By default, the collector determines if a feature is supported by its presence in WebIDL or otherwise, as that is the safest bet for 99% of features -- so for most features, yes, this is correct.  However, not all features can be checked this way, so the collector supports custom tests, which is useful in cases like this one where support is not directly associated with the presence of the method/property.

> * BCD doesn't track bugs as such - so even if a feature doesn't work correctly due to a bug we don't indicate the sub versions where that is true. This is a pragmatic decision.

This is incorrect.  These cases are exactly why we have a [`partial_implementation` property](https://github.com/mdn/browser-compat-data/blob/main/schemas/compat-data-schema.md#partial_implementation).

**Comment by hamishwillee** [comment]
"Somewhat incorrect" - I've only seen partial implementation added at the beginning of an API introduction - not in the middle due to a late-breaking bug.
But thanks, I get your point.
