### ISSUE TITLE
fr unit compatibility with Internet Explorer

### ISSUE THREAD

**Issue by jareko999** [mdn/browser-compat-data#2355]
Your docs show that the `fr` unit isn't supported in IE (https://developer.mozilla.org/en-US/docs/Web/CSS/flex_value), but according to the W3 docs on the old spec of CSS Grid, it shows `fr` units throughout the page (https://www.w3.org/TR/2011/WD-css3-grid-layout-20110407/#grid-repeating-columns-and-rows) and according to multiple sources, IE11 and IE10 support the old spec of CSS Grid, which seems to be using `fr` units on multiple examples. 

Being that your docs are a top reference for browser support and the fact that many orgs are required to support up to IE11, it would be useful to know that this powerful unit is available and compatible.

**Comment by jareko999** [comment]
Can anyone confirm that the `fr` unit is compatible with both the old and new spec of grid?

**Comment by vinyldarkscratch** [comment]
Sorry that it took so long to get to this!  From manual testing, I wasn't able to get IE 11 to respond to `display: grid`, or any of the associated properties.  As such, I don't think that the unit is supported, since it's a part of the same spec.  I'm going to close this issue as a result, but!  I'm happy to reopen this if I'm wrong.

If you could link some of those sources you mentioned, I'd be happy to look into them more!

**Comment by ddbeck** [comment]
I think this issue may still be live, @vinyldarkscratch. [IE's implementation is prefixed](https://github.com/mdn/browser-compat-data/blob/master/css/properties/display.json#L764), which may explain the issue with `display` you had.

**Comment by jareko999** [comment]
@vinyldarkscratch I linked the sources I mentioned in my [original comment](https://github.com/mdn/browser-compat-data/issues/2355#issue-334895794) ☝️.

**Comment by vinyldarkscratch** [comment]
Aw crud, sorry about that, it looks like I was definitely too hasty to close this one.  I didn't think to try it with prefixes -- even the grid properties are prefixed, whoops!

Well, let me close this issue in another method.  :wink:
