### ISSUE TITLE
api.SpeechSynthesis - <Bot cannot pronounce minus sign when structured like this as a math query: 5-3. The bot says "5 to 3" or "5 3">

### ISSUE THREAD

**Issue by BingoBangit** [mdn/browser-compat-data#24031]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

<Bot cannot pronounce minus sign when structured like this as a math query: 5-3. The bot says "5 to 3" or "5 3">

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet), Firefox, Legacy Edge (12-18), Safari

### What did you expect to see?

Five minus three

### Did you test this? If so, how?

I had a user report this to me and i tested it myself in various formats to enforce a math problem, such as (5-3)

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

No sorry

### Do you have anything more you want to share?

Nope

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.SpeechSynthesis`
* Report started: 2024-08-02T21:48:04.793Z

</details>

**Comment by queengooborg** [comment]
BCD doesn't really track details like this one, so I'm not really sure what we can do here.  The specifics of the text-to-speech conversion aren't something that's mandated by the spec, and as far as I know, speech synthesis is controlled by the operating system rather than the browser, so it isn't something BCD _could_ record anyways.

Technically speaking, though, it seems that the speech output isn't _wrong,_ it's just not properly synthesized for your context.  My best recommendation is to perform a text replacement before calling `.speak()` to replace the minus symbol with the word "minus", to enforce a specific way the text is spoken.
