### ISSUE TITLE
javascript.operators.import_meta.resolve - latest Node also returns a string

### ISSUE THREAD

**Issue by Josh-Cena** [mdn/browser-compat-data#24054]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Says "Returns a URL object instead of a string" which is no longer true with latest Node

### What browsers does this problem apply to, if applicable?

Node.js

### What did you expect to see?

Version information for when it starts returning strings

### Did you test this? If so, how?

```js
console.log(typeof import.meta.resolve("./worker.js"));
```

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://github.com/nodejs/node/pull/49698

I don't know which Node versions it corresponds to exactly; the history in Node docs didn't list this change.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import.meta/resolve

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.operators.import_meta.resolve`
* Report started: 2024-08-06T23:12:42.961Z

</details>

**Comment by isbldr** [comment]
According to [this comment on node.js issue](https://github.com/nodejs/node/issues/49695#issuecomment-1745879521) it got fixed in 20.8.0. It's also in the [changelog](https://nodejs.org/en/blog/release/v20.8.0) and here are the [commit](https://github.com/nodejs/node/commit/20b996dcf12d011a88c5779d4829cf1f24f7f3b9) and [PR](https://github.com/nodejs/node/pull/49698) in which it landed.

**Comment by CodeWitchBella** [comment]
According to [this comment on node.js issue](https://github.com/nodejs/node/issues/49695#issuecomment-1745879521) it got fixed in 20.8.0. It's also in the [changelog](https://nodejs.org/en/blog/release/v20.8.0) and here are the [commit](https://github.com/nodejs/node/commit/20b996dcf12d011a88c5779d4829cf1f24f7f3b9) and [PR](https://github.com/nodejs/node/pull/49698) in which it landed.

**Comment by skyclouds2001** [comment]
per https://github.com/nodejs/node/pull/49698, it is also backlog to [v18.19.0](https://nodejs.org/en/blog/release/v18.19.0)

**Comment by skyclouds2001** [comment]
see https://nodejs.org/docs/latest/api/esm.html#importmetaresolvespecifier
