### ISSUE TITLE
api.Window.documentPictureInPicture - incorrectly marked as incompatible on Chrome for Android and Samsung Internet

### ISSUE THREAD

**Issue by kojo12228** [mdn/browser-compat-data#24373]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Browser compatibility for documentPictureInPicture marked as not available in Chrome and Samsung Internet

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

This API should be marked as available in Chrome for Android and Samsung Internet

### Did you test this? If so, how?

Tested https://lazy-guy.github.io/tomodoro/index.html on phone against Chrome for Android 128.0.6613.100 and Samsung Internet 26.0.3.7.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document_Picture-in-Picture_API

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Window.documentPictureInPicture`
* Report started: 2024-09-08T18:23:35.727Z

</details>

**Comment by queengooborg** [comment]
It looks like that website actually uses a workaround for Chrome Android, where instead of displaying the webpage in a PiP context, it generates(?) and displays a video instead.  This is mentioned in the bottom of the description on the intro page or settings menu.

https://mdn-bcd-collector.gooborg.com/tests/api/DocumentPictureInPicture confirms the API you have specified is not supported.

**Comment by kojo12228** [comment]
Ah thanks, sorry I missed that!
