### ISSUE TITLE
api.Gamepad.axes - The API on Android and chrome only has 4 axes on a 6 axis controller.

### ISSUE THREAD

**Issue by AnthonyTekuma** [mdn/browser-compat-data#24414]
### What type of issue is this?

Browser bug (a bug with a feature that may impact site compatibility)

### What information was incorrect, unhelpful, or incomplete?

No information given about axes array length limit.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Gamepad.axes length should be 6 for a 6 axis controller but only 4 axes appear. 

### Did you test this? If so, how?

Reading the length of the axes array returns 4 on android but 6 on windows using the same controller connected by USB C.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Gamepad/axes

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.Gamepad.axes`
* Report started: 2024-09-11T03:05:14.560Z

</details>

**Comment by queengooborg** [comment]
Unfortunately, as discovered in https://github.com/mdn/browser-compat-data/issues/12180#issuecomment-2211653079, support for different gamepad features (such has haptics, additional axes, etc.) appears to be platform specific.  Whether this is due to the OS or the browser, I am not sure, but I would recommend filing a bug for Chrome anyways if there isn't one.

Regardless, this information is too granular for the scope of BCD, but I've submitted a pull request to add a note to the MDN article to better clarify this.
