### ISSUE TITLE
text-underline-position doesn't work for SVG content in Chrome

### ISSUE THREAD

**Issue by pygy** [mdn/browser-compat-data#2618]
I don't know if it is expected, but `text-underline-position` has no effect on `<text>` nodes in SVG.

Repro: https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA8YeAE8YAPgA6dAFQACYDPnzEAD3gBaJHG4AnBvDK9U8gK50deqGToQA3MtUQNmi1Zt3NAB25gyRibmlhB6jnQAvjKCAPQi4hDSdNFgAG4A5vJYEGTpOAC8ACwADEkqgurw8qL5AMylAMoAagDizhry0BDMfPLesZVJsWnpSdHeZfIAEgAqALIAMn0MBukG3ljRMROckDAIxnRU6ACMJ6i1IBEAuhFAA

**Comment by connorshea** [comment]
I wasn't sure what the example was supposed to be showing until I compared it in Firefox vs Chrome.

Firefox:
<img width="201" alt="screen shot 2018-08-16 at 11 54 29 am" src="https://user-images.githubusercontent.com/2977353/44225599-36465c00-a14b-11e8-84b2-afe06338f13c.png">

Chrome:
<img width="188" alt="screen shot 2018-08-16 at 11 54 33 am" src="https://user-images.githubusercontent.com/2977353/44225600-36465c00-a14b-11e8-8bcf-641056a52fff.png">

**Comment by jwhitlock** [comment]
[bug 770780](https://bugzilla.mozilla.org/show_bug.cgi?id=770780) says that text-underline-position isn't implemented in Firefox. The BCD data is correct:

https://github.com/mdn/browser-compat-data/blob/c7ed4411ce4c8c97471c7ba64742132c7f605642/css/properties/text-underline-position.json#L73-L77

There's a ``underline-position`` that has no current data:

https://github.com/mdn/browser-compat-data/blob/acd28749d38305bb413a446ddfd5d8f434423c4a/svg/elements/font-face.json#L1132-L1140

The compat data appears to be correct - is there a BCD issue?

**Comment by connorshea** [comment]
I'd say the compatibility data is correct as it is now unless we really feel the need to mark the unsupported browsers as false.

**Comment by pygy** [comment]
What about SVG + Chrome?

**Comment by vinyldarkscratch** [comment]
It took me a moment to figure out what was going on.  To clear the air of some confusion, this is NOT related to Firefox at all; this is strictly related to Chrome.  What is reported here is that the `text-underline-position` property does not work on SVG elements.  However, from my manual testing of random properties (color, background-color, padding-left...), it doesn't seem like SVG text elements respond to much at all.

I'm thinking that the correct usage for this styling feature is the SVG's `font-face` `underline-position` property, and due to how many CSS properties aren't functioning for the SVG elements, I'm assuming this is one of those SVG things.

We'll definitely be tackling this more in the goal of eliminating all the `null` values!
