### ISSUE TITLE
RFC: Deprecated vs. Obsolete

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#265]
We have a few definitions for the terms _obsolete_ and _deprecated_.

### MDN definition for _obsolete_
> On MDN, the term obsolete marks an API or technology that is not only no longer recommended, but also no longer implemented in the browser. [...] For Web standard technology, the API or feature is no longer supported by current, commonly-used browsers.  [MDN reference](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Writing_style_guide#Obsolete_vs._deprecated)

### MDN definition for _deprecated_
> On MDN, the term deprecated marks an API or technology that is no longer recommended, but is still implemented and may still work. These technologies will in theory eventually become obsolete and be removed, so you should stop using them. [...] For Web standard technology, the API or feature has been removed or replaced in a recent version of the defining standard.  [MDN reference](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Writing_style_guide#Obsolete_vs._deprecated)

### Current BCD definition for _obsolete_
> A boolean value that indicates if the functionality is only kept for compatibility purpose and shouldn't be used anymore. It may be removed from the Web platform in the future.  [BCD reference](https://github.com/mdn/browser-compat-data/blob/master/compat-data-schema.md#status-information)

Currently, BCD does not have the term _deprecated_ in the status object.

### Request for comments: Should we rename _obsolete_ to _deprecated_ in BCD?
In BCD, `version_added` and `version_removed` indicate support ranges and whether support has ended. 

I think it isn't necessary to also have "no longer implemented in the browser" as a meaning for _obsolete_. The current BCD definition for _obsolete_ also doesn't mention this, it is only in the historical MDN meaning, but people get confused by these two definitions.

Further, on MDN, the _deprecated_ meaning includes "is still implemented and may still work". I think in BCD we shouldn't have this as an implicit meaning of _deprecated_ as we have `version_added` and `version_removed` for when something is supported or not.

Probably _deprecated_ is the more common term for indicating the recommendation status ("do not use this anymore", "it's no longer recommended", "the spec discourages this", etc). So, I think we should use _deprecated_ instead of _obsolete_.  A definition for _deprecated_ in BCD could be:

> A boolean value that indicates if the feature is no longer recommended. It might be removed in the future or might only be kept for compatibility purposes. Avoid using this functionality.

On the Web platform, features are rarely ever removed, because the Web needs to be compatible. For WebExtensions, or other APIs, where deprecated features might actually be removed, I think that _deprecated_ is still a good term, too, as we're not mixing implementation status and recommendation status in our definition.

### Motivation 
I thought it would be nice to answer why we are thinking about this anyway why it isn't entirely bikeshedding (but somewhat bikeshedding). So here is my take:

Fundamentally, I think BCD should have **well defined** answers to the two questions "Can I use this?" and "Should I use this?". 
- For "Can I use this?" (is it possible, how and when?), the support object including `version_added` and `version_removed` and caveats like flags, alternative names etc. give you answers. 
- For "Should I use this?" (is it recommended?), the status object should give you answers.
  - if you only want to use non-experimental features, the `experimental` boolean should be false for you
  - if you only want to use web standard features, the` standard_track` boolean should be true for you
  - if you only want to use features that aren't discouraged to be used (either because the feature is only available still for compat reasons, or is planned to be removed), the `deprecated` boolean should be false for you.

**Comment by chrisdavidmills** [comment]
I really like the new definition, and support these thoughts.

One nitpick - in the definition, "purpose" -> "purposes"

I'd like to take this slightly further and remove "obsolete" from MDN altogether. It's kind of a standards thing that you don't see much any more, and it's confusing. So why don't we just get rid of it?

OR. We could replace it with "removed". That's much more obvious and less confusing.

The states we are concerned with would then be:

* "Implemented" — it's implemented across browsers. You can use this.
* "Non-standard" — it's not a standard. Be careful.
* "Experimental" — it's implemented in a few places, but not everywhere, and it's subject to change. Be careful.
* "Deprecated" — it's removed from the specs but still available in browsers in a few places (but could be removed at any time). Be very careful.
* "Removed" — it's removed from the specs and browsers. You can't use it.

Your above answer definitions seem to nicely cover these cases, and appropriate combinations of them. I'm assuming that removed features are just deleted from the BCD altogether?

**Comment by snoack** [comment]
I agree that the differentiation between _obsolete_ and _deprecated_ is redundant since there is `version_removed`. Furthermore, this abstraction is inconsistent, as `status` is per per feature (not per browser). So if a deprecated feature has only be removed in some of the browsers, it's ambiguous whether it should be considered _obsolete_ or _deprecated_. So it seems to make more sense to merge these two statuses, and have `version_removed` (which is per browser) indicate the feature's browser support.

**Comment by wbamberg** [comment]
This all makes sense to me.

In general, we should avoid including things like "some browsers might not support this" in any definition of terms like `experimental` and `deprecated`, because the details compat data should describe the *current* state of support.

Where terms like `deprecated` are useful is where they give some indication of the *future*: web developers should care about the future as well as the present, and the detailed compat data can't tell them this. So knowing that future runtimes are (more) likely to drop support for a feature is good information.

I like your definition of "deprecated", and would support using it as the MDN definition as well as the BCD one, and would also support removing "obsolete", as Chris suggested.

**Comment by snoack** [comment]
> Where terms like `deprecated` are useful is where they give some indication of the future

Doesn't that apply as well to `experimental`, as semantics and availability of experimental features are matter to change in the future? For example look at flexbox, where the syntax changed 3 times while it was experimental technology, before we ended up with the final standard. In other instances experimental features got completely removed from the standard and implementations later.

**Comment by wbamberg** [comment]
Yes, it absolutely does apply to `experimental` as well.

**Comment by a2sheppy** [comment]
I concur that the term "deprecated" should be used to essentially mean (in simple terms) "no longer considered accepted practice" or something like that, and that "obsolete" isn't needed thanks to the version added and removed information provided by BCD.

**Comment by jpmedley** [comment]
I don't think it affects what you're doing, but you all should know that
Chrome uses deprecation as a preamble to removal.
https://developers.google.com/web/updates/2017/06/chrome-60-deprecations#deprecation_policy

Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by Elchi3** [comment]
Thanks all!
It's really valuable to get these terms and policy sorted out after all.

For BCD, we've made the suggested change in #268.

For MDN, I'll open a thread in our [discourse forum](https://discourse.mozilla-community.org/c/mdn) to make more people aware of this and we'll change MDN's usage policy of "obsolete" and "deprecated" depending on the outcome of that thread. Several here have suggested to use the definition we agreed here on MDN as well, so lets see! 

Thanks again!

**Comment by a2sheppy** [comment]
@Elchi3 -- Did that thread get started? If so, adding a link here might be helpful.

I ask because this is something I may want to address on pages I touch with the SEO project work, since I need to move deprecated stuff aside in certain places and that kind of thing. Might be helpful to have this decision made and finalized. I posted about this on Discourse here: https://discourse.mozilla.org/t/deprecated-obsolete/19098/5 (while trying to get a feel for how to proceed on these article updates I'm doing for SEO).

**Comment by Elchi3** [comment]
@a2sheppy Looks like I forgot about this. We can use your thread to make a call. I think BCD's terms make sense for MDN overall.

**Comment by a2sheppy** [comment]
I agree. Let’s go with “deprecated” and deprecate “obsolete.” :)


Eric Shepherd
Senior Technical Writer, MDN
MDN: https://developer.mozilla.org/
Blog: https://www.bitstampede.com/

On September 14, 2017 at 5:55:27 AM, Florian Scholz (
notifications@github.com) wrote:

@a2sheppy <https://github.com/a2sheppy> Looks like I forgot about this. We
can use your thread to make a call. I think BCD's terms make sense for MDN
overall.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mdn/browser-compat-data/issues/265#issuecomment-329433720>,
or mute the thread
