### ISSUE TITLE
Add links to support tables to show what JSON the table is generated from, along with a CTA if you notice something is incorrect

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/browser-compat-data#2722]
(from a conversation with @marcoscaceres)

It would be really useful if there was a link generated along with each browser compat table on MDN that linked back to the JSON file that the table was generated from. This could be presented as a call to action — if the reader or editor notices that some data is incorrect, or simply wants to make an addition or edit, they can easily find the JSON.

When I was talking to Marcos today about Payment Request/Handler API docs, he noted that the engineering team for these APIs have been trying to help with updating the docs as new features are added, but they had found it difficult to work out how to updated the BCD.

The CTA could be something like

"This table is generated from the data at BlahBlah.json; if you want to add new data or fix an error, please file a pull request."

**Comment by jpmedley** [comment]
I think this is a good idea, but I have a concern. The sources people use for their submitted data may be problematic. For example:

* People submitting data gleaned canisue. Google doesn't officially support caniuse and I don't really have time to backtrack their PRs to learn where the info actually came from. 
* People submitting items based on ChromeStatus listing a version number ahead of that version shipping. For example, I've seen PRs in the last few weeks for items that we plan to ship in Chrome 70. It will be another 10 days before I even know for sure if that stuff will be in beta. (For the items I saw, I had a high degree of confidence that they were in fact shipping. Otherwise I would have said something. Also, I'll see if I can a disclaimer on Chrome Status to discourage using it.)

I'd be surprised if other vendors didn't have similar issues.

To be clear: **I support this.** I'm just pointing out the need for language and/or procedures that help contributors submit good information.

**Comment by marcoscaceres** [comment]
Agree. We should ask people to point to a web platform test that reproducibly proves a feature, attribute, or method is supported by a given browser.

**Comment by marcoscaceres** [comment]
For the above, we should have a pull request template that asks for a link. The test should be verified by a reviewer. 

This will hopefully help also boost the number of web platform tests - in that proof will be needed in the form of a real test🔬.

**Comment by jpmedley** [comment]
WPT tells current conditions, doesn't it? I was referring to sources that provide a version number.

**Comment by marcoscaceres** [comment]
It can do both: one can run the test on a particular browser version or a current/nightly version.

**Comment by connorshea** [comment]
I wasn't able to determine a way to get links to the upstream JSON using the data provided by the npm package for my [Explorer](https://github.com/connorshea/mdn-compat-data-explorer), instead I just generated GitHub search queries, like `https://github.com/mdn/browser-compat-data/search?q=api.Blob`.

I'm not sure that's really a good alternative though :) Maybe someone who's more clever can figure out a good way to link to the JSON.

**Comment by Elchi3** [comment]
We've now at least added a CTA to the tables pointing to this repo [1], which is maybe somewhat more friendly as it presents newcomers an overview and the readme of the project instead of some JSON without guidance.

[1] See any compat table, e.g. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Browser_compatibility

**Comment by marcoscaceres** [comment]
@Elchi3 appreciate this addition! I added a follow up #2908 - I think we are getting somewhere good tho. I'd like to get us from <del>farm to table</del> spec to data, seamlessly, as part of the standardization process. Let's discuss in #2908.
