### ISSUE TITLE
Maybe start automate things?

### ISSUE THREAD

**Issue by jimmywarting** [mdn/browser-compat-data#2883]
Would be cool if we could use [wpt](https://github.com/web-platform-tests/wpt) + [saucelabs](https://saucelabs.com/) to report back what is supported and what is not for upcoming browser versions.

**Comment by connorshea** [comment]
Easier said than done :D

Caniuse has a pretty good test suite that does this (not based on WPT AFAIK), but it also adds far fewer features at a much slower rate because of that. This project does already have the confluence data that it can automatically take data from, as well as the node compat tables project.

I’m not sure if anyone has looked into using WPT data yet :)

Currently it’s pretty much just updated as people find issues and as browsers have new releases, typically based on the changelog/release notes. We have jpmedley contributing data for Chrome/Opera, a bunch of Mozilla employees for Firefox, and some Microsoft employees for Edge releases. The only major browser missing a contributor is Safari. So for the most part, I’d say the project has pretty good manual coverage.

**Comment by sideshowbarker** [comment]
> This project does already have the confluence data that it can automatically take data from

I think you’re referring to:

http://web-confluence.appspot.com/#!/catalog?&q=""

If so then yeah that seems to already be like what’s described in the issue description.

As far as browser results for WPT, there’s https://wpt.fyi/results/

And for getting results for the latest development builds of each browser, https://wpt.fyi/results/?label=experimental

**Comment by jimmywarting** [comment]
http://web-confluence.appspot.com/#!/catalog?&q=""

oh, wasn't sure you did automated test, still saw some yes/no/? at mdn while looking at some data so i thought you didn't do that.

**Comment by connorshea** [comment]
It exists, but it’s not really reliable enough to automatically fill the browser compat data files. It’s mostly there as a supplement when researching feature support.

**Comment by jpmedley** [comment]
+1

I could list it's issues, but the big one is that it doesn't make distinguish between desktop, Android, and Webview. Occasionally there are differences.

**Comment by Elchi3** [comment]
Please see https://github.com/mdn/browser-compat-data/issues/3308 for automation approaches. Feedback welcome.
