### ISSUE TITLE
Internet Explorer supports `grid-row` and `grid-column` prefixed with an older syntax

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/browser-compat-data#3031]
This means that it should be marked as `"partial_implementation": true` with the older syntax documented in the `notes` field.

See&nbsp;also&nbsp;https://github.com/mdn/data/issues/316.

/cc @frenic

**Comment by vinyldarkscratch** [comment]
This is a pretty old (but still relevant issue), however I've been struggling with how to open up a PR, mostly since I'm not certain how to document the spec differences in the existing files.  Since there's such big differences between them, I'm thinking we should probably just make new CSS property files for those prefixed, older properties.

I also found an article from @rachelandrew that I think helps out (thanks, Rachel!): https://rachelandrew.co.uk/archives/2016/11/26/should-i-try-to-use-the-ie-implementation-of-css-grid-layout/
