### ISSUE TITLE
Inconsistency on Webview Android versions

### ISSUE THREAD

**Issue by CKGrafico** [mdn/browser-compat-data#3034]
We are working on this feature for webhint using your awesome package https://github.com/webhintio/rfcs/issues/10

But we have found some inconsistency in the data (maybe we are not understanding well).

When we check the version of webview_android we receive different results:

If we check, at rule media we can see that is supported since version 1, https://github.com/mdn/browser-compat-data/blob/master/css/at-rules/media.json#L45 but the at rule viewport since version https://github.com/mdn/browser-compat-data/blob/master/css/at-rules/viewport.json#L92 but also other subproperty is for version 41 https://github.com/mdn/browser-compat-data/blob/master/css/at-rules/media.json#L201

We have to compare the supported browsers of our list with these versions but we are not sure if we can use 41 as 4.1 or if 41 is browser version a 4.4.3 is for OS version, etc.

https://developer.mozilla.org/en-US/docs/Web/CSS/@media
![img](https://i.imgur.com/933WL4d.png)

**Comment by Elchi3** [comment]
Hey, thanks for working on integrating this dataset into webhint! :) 

WebView versions are a bit tricky, because the browser was coupled with the Android OS version for a while (until Android 5), but then it was possible to update the browser as an app separately, so the latest Chromium version number is used. Caniuse dies this the same way, see the tooltip for "[Android Browser*](https://caniuse.com/#feat=flexbox)", for example.

See also the discussion here https://github.com/mdn/browser-compat-data/pull/2690#issuecomment-417237045 and this file https://github.com/mdn/browser-compat-data/blob/master/browsers/webview_android.json with valid versions for webview android.

**Comment by CKGrafico** [comment]
@Elchi3 that link is enough for us https://github.com/mdn/browser-compat-data/pull/2690#issuecomment-417237045 thanks for your help
