### ISSUE TITLE
NodeJS supports setImmediate() function

### ISSUE THREAD

**Issue by pitust** [mdn/browser-compat-data#3073]
setImmediate is supported on nodejs v8.9.1

**Comment by saichaitanyareddy** [comment]
Yes, setImmediate is supported on nodejs v8.x.
you can go through  the following link for documentation:
[https://nodejs.org/docs/latest-v8.x/api/timers.html#timers_setimmediate_callback_args](url)

**Comment by vinyldarkscratch** [comment]
Thanks for bringing this issue up (and sorry for the delays in responding).  May I ask what your source for the data is, such as manual testing, or documentation?

**Comment by vinyldarkscratch** [comment]
After further review, this seems to be a part of Node's internal Timer API, rather than the Window API like I originally anticipated.  I don't think we've added any Node-specific APIs to our compatibility data, as it's intended for _browser_ compatibility specifically, though there's discussion about adding non-browsers (see #3280).

I'm going to go ahead and close this issue as a result.  If you're interested in Node-specific APIs getting added to this repo, write a comment in the linked PR to let us know!
