### ISSUE TITLE
linter error message is confusing

### ISSUE THREAD

**Issue by wbamberg** [mdn/browser-compat-data#3256]
If an identifier contains disallowed characters, then the linter's message is:

```
   item['path']['to']['item']['parent'] should NOT have additional properties
```

This is wrong and misleading, and it would be much more helpful to say something like:

```
   item['path']['to']['item'] key contains disallowed characters
```

...even better if it could link to docs for allowed characters, but https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md does not seem to document this.

**Comment by wbamberg** [comment]
Actually it's not wrong, it's just unhelpful.

The schema says https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data.schema.json#L197-L206, i.e. "identifiers can only contain '__compat' or properties matching that regex, no other properties".

ajv then applies that to the data and says "wait, there are other properties", which is correct but usually not a helpful error message.

**Comment by Elchi3** [comment]
We might want to look for upstream issues on this or file this issue upstream with ajv.

**Comment by vinyldarkscratch** [comment]
It's been a while since we've looked into this one.  Looking around, I found that ajv has another package that allows for adding custom error messages on schema failure: [`ajv-errors`](https://github.com/ajv-validator/ajv-errors).  Assuming it plays well with `better-ajv-errors`, I think this could solve our issue.
