### ISSUE TITLE
Spec URL Should be Normalized

### ISSUE THREAD

**Issue by jpmedley** [mdn/browser-compat-data#3328]
The spec URLs in BCD should be [normalized](https://www.studytonight.com/dbms/database-normalization.php). In non-tech speech, this means deduplicate. This serves two purposes:

* Eliminates duplication of data. 
* Adds insurance against stale data by providing a single location to update the URL.

An automated consistency check within a file cannot solve this problem because many interfaces contain members that contributed by multiple specs.

**Comment by a2sheppy** [comment]
What spec URLs in BCD? The only URLs commonly used in BCD are the `mdn_url` entries.

Assuming we really are talking about spec URLs though...

This is an interesting idea. I take it the idea is basically to have a table of specifications, with each spec's entry including its base URL, so that links to stuff within that spec are then written relative to that base URL. So something like...

**SpecInfo.json**
```
[
  ...
  {
    "id": "WebRTC",
    "name": "WebRTC 1.0: Real-time Communication Between Browsers",
    "url": "https://w3c.github.io/webrtc-pc/",
    "category": "Media"
  }
  ...
]
```

**RTCPeerConnection.json**
```
{
  "spec": "WebRTC",
  "api": {
    "name": "RTCPeerConnection",
    ...
    "spec_slug": "#rtcpeerconnection-interface"
  }
}
```

Something like that, anyway. I think I have missed the specific use case for this but the general idea is probably something like this for how it would be built, no?

**Comment by ddbeck** [comment]
@a2sheppy the schema has `spec_url` (see: [/schemas/compat-data.schema.json#L151](https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data.schema.json#L151)) but it's undocumented. 😞

At least right now, it only appears to be used in `/javascript/` data.

For more background: #1531 and #2983

**Comment by ExE-Boss** [comment]
I believe we should move `SpecData.json` to&nbsp;[mdn&#x2011;data](https://github.com/mdn/data) and reference it&nbsp;from here (like what I’m doing with `GroupData.json` in&nbsp;https://github.com/mdn/data/pull/342).

**Comment by jpmedley** [comment]
@chrisdavidmills I think moving spec data is a good idea, but until the license issue is resolved this will prevent me from contributing to it.

**Comment by chrisdavidmills** [comment]
@jpmedley this is an issue, certainly, which could perhaps be mitigated in a few ways (e.g. by getting W3C spec folks to add their own specs to our data), but really it would be so much better to sort out the license issue once and for all. I'll bring this up with our lawyer again and see if he managed tro make any headway with the discussion.

**Comment by foolip** [comment]
https://github.com/tobie/specref is a source of truth you could use for this, but I think you'll find some of the URLs still need massaging and getting them updating in specref can be difficult because it sometimes requires updating a page under https://www.w3.org/TR/.

I've dealt with this problem in https://foolip.github.io/day-to-day/ but not in a way that is maintenance-free.

**Comment by Elchi3** [comment]
Closing this. We're not planning to do anything about this for now. Might come back in the future, when MDN is based on more structured data.
