### ISSUE TITLE
Missing data for margin-inline|block, padding-inline|block, border-inline|block

### ISSUE THREAD

**Issue by fvsch** [mdn/browser-compat-data#3444]
I'm seeing "No support" for every browser for:

https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline
https://developer.mozilla.org/en-US/docs/Web/CSS/margin-block
https://developer.mozilla.org/en-US/docs/Web/CSS/padding-inline
https://developer.mozilla.org/en-US/docs/Web/CSS/padding-block
https://developer.mozilla.org/en-US/docs/Web/CSS/border-inline
https://developer.mozilla.org/en-US/docs/Web/CSS/border-block
https://developer.mozilla.org/en-US/docs/Web/CSS/inset-inline
https://developer.mozilla.org/en-US/docs/Web/CSS/inset-block

In my tests, these properties work in Chrome 69 and Firefox Nightly (and at least a few Firefox versions before that). Haven't looked at Safari or Edge yet.

**Comment by vinyldarkscratch** [comment]
It looks like this has been mostly addressed and fixed by #3451, all except for the `inset-inline|block` properties.  While playing around, I found that Safari doesn't support any of these properties, Chrome supports all aside from the bottom two, and Firefox supports all of them.  (Haven't tested with Edge yet.)

Will write a PR to help address `inset-inline|block`!
