### ISSUE TITLE
max-width: fill-available missing compat table

### ISSUE THREAD

**Issue by scheinercc** [mdn/browser-compat-data#3523]
`max-width: fill-available` is listed under "Syntax", but not in the BC table:
https://developer.mozilla.org/en-US/docs/Web/CSS/max-width#Browser_Compatibility

**Comment by vinyldarkscratch** [comment]
It looks like this was called `stretch` instead of `fill-available` for some reason.  I feel that this is misleading.  Submitting a PR to fix this now!

**Comment by ddbeck** [comment]
In the course of reviewing #3611 (thank you again @vinyldarkscratch—that was a good attempt), I think the issue here is a bit more complicated than swapping the name.

There's a problem in that the name `stretch`/`fill`/`fill-available`/`available` isn't settled and doesn't look likely to be settled any time soon. The note in [CSS Intrinsic & Extrinsic Sizing Module Level 3 spec](https://www.w3.org/TR/css-sizing-3/#sizing-values) says: 

> This section previously defined 'stretch' and 'fit-content' as keywords representing the stretch-fit size and fit-content size, respectively. These keywords have been deferred to Level 4

It looks to me that the overall situation is this:

* `stretch` was the most recent name in the level 3 sizing spec (now deferred to level 4)
* `fill` was a previous name in the spec (I'm not 100% sure about this, I couldn't directly find this in the spec repo)
* `-webkit-fill-available` is what Chromium implemented (see [this commit](https://chromium.googlesource.com/chromium/blink.git/+/bf119cdfece210e69c9a99af06f1b9981e2a1bc2))
* `-moz-available` is what Firefox implemented ([see this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1495868))

I think the least-worst solution here is changing the syntax on the MDN page, though I suppose breaking out the non-standard values (`-moz-available` and `-webkit-fill-available`) into their own rows is also an option (I'm not in love with that, but it might be an acceptable stopgap until the level 4 spec provides some clarity).

**Comment by trss** [comment]
I don't think this calls for a separate issue so just adding a note here.

https://github.com/mdn/browser-compat-data/blob/master/css/properties/height.json does not include the -moz-available options which https://github.com/mdn/browser-compat-data/blob/master/css/properties/width.json includes.

Consequently the -moz-available support in FF is:
mentioned at https://developer.mozilla.org/en-US/docs/Web/CSS/width#Browser_compatibility
but not at https://developer.mozilla.org/en-US/docs/Web/CSS/height#Browser_compatibility
and similarly not at the min/max-width/height pages.

And the same gaps are present in the "Can I use..." pages also such as https://caniuse.com/mdn-css_properties_height_stretch.

**Comment by queengooborg** [comment]
At some point, it looks like `fill-available` has been removed from the syntax list, and in Level 4, the official name has become `stretch`.  As such, I'm going to go ahead and close this PR.
