### ISSUE TITLE
Users want to know support info for current browsers.

### ISSUE THREAD

**Issue by stephaniehobson** [mdn/browser-compat-data#361]
User testing the article pages revealed that users want to know if the *current* version of browsers support stuff. It's easy to assume that something added in Firefox 36 is still present in Firefox 57 but when something is reported not to have been available in Firefox 36, it's hard to know if that is still true in 57 or if the data just hasn't been updated. Same with features in active development. If Chrome 60 has the feature behind a flag, it isn't safe to assume Chrome 61 does as well. (also, who even remembers what the current version of Chrome is? It changes so fast.)

I'm not sure we need to repeat information over and over again but maybe we could have some way to indicate the most recent version of the browser the information was verified in?

**Comment by jwhitlock** [comment]
The implicit rule is that a support statement for a version means "this version and the versions after it". I'm OK with making that rule explicit, so that we don't have to duplicate support entries for each version.

In the [previous API implementation](http://browsercompat.readthedocs.io/en/latest/v2/resources.html#versions), we had an ordered list of version numbers for each browser, and annotated them with a release status. Data like that would allow inferring the support of the current browser given the explicit support statements in ``browser-compat-data``. It would also make it easier to validate version numbers (issue #168). Versions data could make this tasks trivial, but would be a maintenance burden.

It may be possible to determine the "last version" in a support list, and use that as a proxy for the current version support. This falls apart when the "last version" is a preview release, however, so we're back to needing metadata about versions.

**Comment by Elchi3** [comment]
Initial browser data is now added to the repo and the package exports it, so it can be used by data consumers: https://github.com/mdn/browser-compat-data/blob/master/browsers/browsers.json
Issue https://github.com/mdn/browser-compat-data/issues/591 tracks adding missing browser data.

So, I think the data part of this is solved. How we should display this, I'm not sure yet. It's also an MDN/KumaScript/data displayer issue, I guess.

**Comment by Elchi3** [comment]
There is isn't really anything left to do here on the data side of things. We did additional user testing with new findings and this will, if at all, be dealt with on the displayer side. Whether that's improvements to the main compat tables on MDN or to a new "summary compat widget" on MDN, is to be seen.
