### ISSUE TITLE
How do we deal with browser-specific edge cases?

### ISSUE THREAD

**Issue by jpmedley** [mdn/browser-compat-data#3669]
Let me explain this issue with a recent example. Pull request #3659 attempts to correct what its author sees as incorrect data concerning the Network Information API in Chromium. Everything its author has done is reasonable when compared to his approach to researching and its seeming consistency with other Chromium features. 

Nevertheless it is wrong.

This particular API is at the mercy of the underlying hardware. The features that appear in DevTools may change depending on the device where the the code is run. In implementing this API, Chrome also had blocking privacy and security issues to content with resulting in an unusually wide divergence in [when supported landed in the various Chromium flavors](https://www.chromestatus.com/features/6338383617982464). 

If I had been on vacation when the above PR was submitted, correct information would have been replaced with incorrect information. I'd be surprised if other browsers didn't have edge cases in danger of being overwritten. 

How do we ensure that unusual data not be overwritten?

Should a note on the feature explain its weirdness? Maybe we could have a list of keys that would let travis throw a warning? I'm not in love with either idea. I just want to get the discussion going.

**Comment by vinyldarkscratch** [comment]
In the mentioned pull request, we determined that notes were the best way to add information regarding said edge case. I believe notes are meant for.  I feel that they are the best possible solution to this problem, without trying to hook up specialized linters.

Since this issue is so old, I think we can safely close this as a result, but if anyone thinks it should remain open, please let me know!
