### ISSUE TITLE
Safari 12.1 enables VisualViewport by default

### ISSUE THREAD

**Issue by connorshea** [mdn/browser-compat-data#3796]
Sources:
- https://trac.webkit.org/changeset/239897/webkit
- https://webkit.org/blog/8566/release-notes-for-safari-technology-preview-74/

I'm not sure how to verify this, so I'm leaving this as an issue for now.

**Comment by vinyldarkscratch** [comment]
Unfortunately I was not able to verify this on the latest Safari -- running `window.visualViewport` in a JS console in Safari returned `undefined`.  I was, however, able to confirm functionality in Safari TP 79.  I believe this may be something that will be released in Safari 12 instead.

**Comment by connorshea** [comment]
@vinyldarkscratch odd, the section at the bottom of [this article](https://webkit.org/blog/8718/new-webkit-features-in-safari-12-1/) mentions TP 74, but I guess that's not as accurate as I had assumed.

**Comment by vinyldarkscratch** [comment]
I totally see what you mean, and I'm surprised at the testing outcome as well!  Based upon what these articles are all implying, we would expect Safari 12.1 to have the support enabled.

Since this has been verified as unsupported by default in Safari, I will close this issue, though I do plan on revisiting this sometime!
