### ISSUE TITLE
Support links to browser docs

### ISSUE THREAD

**Issue by codedokode** [mdn/browser-compat-data#3957]
Currently the schema allows adding links to MDN article or a specification, but doesn't allow linking to browsers' docs. 

For example, browserAction API is supported in Chrome since at least version 5 ([archived docs](https://web.archive.org/web/20131216103708/http://developer.chrome.com/extensions/browserAction.html)), but [current version of documentation](https://developer.chrome.com/extensions/browserAction) says it is supported only since version 29 (don't know why they are doing this).

If we just add version 5 to JSON data, then someone may find that it contradicts current docs and change it to 29. A link to archived version of documentation could clear up this issue.

Also adding links makes it easier to verify the data.

**Comment by vinyldarkscratch** [comment]
I'd have to say that the most fitting location for this would be in the notes of each support block for each browser.  I feel that such cases where it's needed are rare enough that notes do the trick.  The particular scenario you've mentioned also seems like it's more of a bug in Google's documentation.  Is it actually version 5, or is it 29?  If it's version 5, Google needs to update the documentation to reflect as such, so we both have "5".  Otherwise, "29" is what we should put down.

**Comment by Elchi3** [comment]
Yes, we are usually using notes for this. I don't think we need to extend the schema for other doc links. Thanks for your suggestion, though.
