### ISSUE TITLE
lint.js should check browser order

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#398]
It came up recently (e.g., on #387) that we ought to use a consistent order for browsers, for each features. So, for example, `chrome` should precede `chrome_android` in a support array. Rather than have PR reviewers check these by hand, `lint.js` should check the order and warn if it's inconsistent.

**Comment by connorshea** [comment]
Rather than doing this all at once in a massive PR I think it’d be easier to do a bunch of smaller PRs, maybe 20 files per PR? I’m not sure exactly how many files need changing at this point, though, so we may want to change the PR size depending on that info.

Regardless, most PRs currently open are for adding new files rather than changing existing files (PRs of the latter type tend to be merged pretty quickly), so it _probably_ shouldn’t cause merge conflicts in too many of them.

**Comment by connorshea** [comment]
We could also add a lint that’s only run for PRs, and not on the master branch. This way we can make sure that all new PRs have their support info alphabetized but master won’t fail if an old PR is merged.

We’d have to alphabetize all the files on master first though, and there’s still the problem of a PR without alphabetized support items being merged into master and causing new PRs to fail, though 🤔

**Comment by ddbeck** [comment]
Maybe we could use Travis to sort of… upgrade the style as we go? By that I mean, maybe we could break out the #1474 linter changes to run only on files that have changed in a PR. That way, whenever a file is touched during a PR, the author could also be alerted to sort the browsers on only those files? That way sorting could be reviewed incrementally, rather than in large, kinda boring PRs.
