### ISSUE TITLE
Where should web app manifest data be stored?

### ISSUE THREAD

**Issue by jpmedley** [mdn/browser-compat-data#3998]
It still has a [hand-built compatibility table](https://developer.mozilla.org/en-US/docs/Web/Manifest#Browser_compatibility). I'll very soon need to add members from the [Web Share Target API - Level 2](https://wicg.github.io/web-share-target/level-2/#extension-to-the-web-app-manifest).

**Comment by Elchi3** [comment]
I'm still voting to install it under `html/manifest.json`, but happy to hear other opinions.
See also https://discourse.mozilla.org/t/mdn-browser-compat-data-migration-where-to-put-web-app-manifest/28171

**Comment by bershanskiy** [comment]
I started porting PWA manifest data into a JSON and would like to make sure my approach is correct:
 - I made a new folder `/html/manifest` and store data about individual manifest attributes in files `/html/manifest/[attribute].json` because the number of attributes is rather large and some attributes are actually objects with their own attributes or arrays.
 - I also add individual attributes that are [Web App Manifest](https://w3c.github.io/manifest/) draft but are absent from the current table.

I'll make a PR by the end of today to show my work.

**Comment by bershanskiy** [comment]
Please note that the Web App Manifest draft also describes [Installation events](https://w3c.github.io/manifest/#installation-events) that are [supported only by Chromium](https://caniuse.com/#feat=web-app-manifest) and not documented in MDN docs. I did not add JSON for those, but I will if there is interest in it.

**Comment by Elchi3** [comment]
See also https://github.com/mdn/sprints/issues/1676 for the content work discussion.
