### ISSUE TITLE
Is "version_removed" inclusive?

### ISSUE THREAD

**Issue by FranklinYu** [mdn/browser-compat-data#4206]
For example, support for Public Key Pins header is removed in Chrome since 72, which means that 71 is the last Chrome with this feature. However, from the [rendered compatibility table](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Public-Key-Pins#Browser_compatibility), it seems like 72 is the last version. Which one is true?

**Comment by vinyldarkscratch** [comment]
We've defined `version_removed` as exclusive, or in translation, "Browser X version Y no longer supports this feature".  However, looking at the compatibility data, you do strike a good point -- it makes it seem like that version still supported it, but future versions didn't.

@Elchi3, I'd love to get your input on this one!

**Comment by Elchi3** [comment]
The MDN rendering is wrong here. It is tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1417902. The good news is that I think we're unblocked on this one now.

**Comment by FranklinYu** [comment]
I’m not sure I understand that bug. Are we going to re-design the UI, or update the data schema?

And how is #591 related to this issue?

**Comment by vinyldarkscratch** [comment]
The schema will remain the same, but the renderer within Kumascript will be updated, from what I can tell in that tracking bug.  That other issue is relevant because for us to show the prior browser version, we’d need to know what that version is!

**Comment by FranklinYu** [comment]
Cool. In the current version, I think the affected part is

https://github.com/mdn/kumascript/blob/c4ff934bcce1dc3ce873ffda7d8ee1170e56d023/macros/Compat.ejs#L196-L215

Right?

**Comment by Elchi3** [comment]
That is the affected part, correct. I think we can track here as well, so we don't forget about this issue. Implementation needs to be fixed in kumascript, though.

**Comment by foolip** [comment]
I've filed https://github.com/mdn/content/issues/2107 about getting this fixed in Yari.

**Comment by Rob--W** [comment]
This bug affects all version ranges from APIs that were dropped in Firefox for Android 79+, added in https://github.com/rebloor/browser-compat-data/commit/f6ece9402abfeab813c0a9b7ee49314554e9b1de (https://github.com/mdn/browser-compat-data/pull/6590).

`"version_removed": "79"` is meant to mean that the API is not supported in 79+.
However, the rendered compat table renders something like `48 - 79`, which gives the misleading appearance that the APIs were supported in 79. Since there were no Firefox for Android releases between 68 and 79 (exclusive), the actual support range should be `48 - 68`, or at most `48 - 78`.

**Comment by queengooborg** [comment]
I'm going to close this since it's a rendering issue rather than a data issue, and we have an open issue that's closer to the right spot.
