### ISSUE TITLE
the status of requestFullscreen on ios is not right

### ISSUE THREAD

**Issue by Ende93** [mdn/browser-compat-data#4239]
Since `requestFullscreen` was [not avaiable on ios](https://caniuse.com/#search=requestFullscreen), it should be disabled or part support.

**Comment by vinyldarkscratch** [comment]
It appears that CanIUse may have updated their data since this PR was created.  Safari for iOS supports the Fullscreen API as of iOS 12.1, as per the data you have linked (though only on iPad, not iPhone).  Since `api.Element.requestFullscreen` is a part of the Fullscreen API, I'm positive that it's supported.

Of course, we'll be verifying this!

**Comment by vinyldarkscratch** [comment]
Just verified support.  It is available under the `webkit` prefix, just as suspected.  This is not available on iPhone as CanIUse states, but is available on iPad.
