### ISSUE TITLE
CSS property 'stroke' is not supported (no MDN compatibility data)

### ISSUE THREAD

**Issue by Klarence** [mdn/browser-compat-data#4260]
CSS property 'stroke' is not supported (no MDN compatibility data)
I am using PyCharm and I get this error.

Additional CSS properties that are also not supported.

- stroke-dasharray
- stroke-dashoffset
- stroke-linecap
- stroke-width

https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Fills_and_Strokes

**Comment by vinyldarkscratch** [comment]
Hi there -- sorry for how long it took to get a response to you.  Most of our efforts have been focused on the 2019 Key Result within this repository...  Anyways, looking at this issue much closer, I believe that this is more of an issue within PyCharm rather than BCD.  The reason I state this is because the `stroke-*` properties are actually SVG attributes, and not really CSS properties.  CSS just allows for the overriding of SVG attributes, thus extending upon the language.

I would report this to PyCharm, especially if nobody has already.  Essentially, the IDE should be able to determine what's an SVG property, and link to the appropriate documentation.  Hope this helps get you pointed in the right direction!

I will be closing this issue, however if you feel that I'm closing it in mistake, feel free to respond and let me know.
