### ISSUE TITLE
document.currentScript not supported in modules, use instead import.meta

### ISSUE THREAD

**Issue by laukstein** [mdn/browser-compat-data#4292]
Please update https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript documentation mentioning "`document.currentScript` not supported in modules https://github.com/whatwg/html/issues/997, use instead `import.meta` https://github.com/w3ctag/design-reviews/issues/208 https://github.com/whatwg/html/issues/1013".

**Comment by vinyldarkscratch** [comment]
Hey @laukstein -- actually if you sign into the MDN through your GitHub account, you can edit the pages.  Documentation isn't kept in this repository; this is for the browser compatibility chart.  🙂 

I'm going to go ahead and close this issue since it's regarding the documentation and not the browser compatibility.

**Comment by laukstein** [comment]
I just updated, thanks!
