### ISSUE TITLE
Inconsistent data for window.location.host

### ISSUE THREAD

**Issue by nathanwfranke** [mdn/browser-compat-data#4473]
In [this](https://developer.mozilla.org/en-US/docs/Web/API/Location#Browser_compatibility) document the property `host` claims to be supported on all browsers.
However, the linked page attached to `host` [claims otherwise](https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/host)
I think that both of these properties need to be tested again...

Noted: [W3 Schools claims that both of these properties are cross-browser](https://www.w3schools.com/jsref/obj_location.asp)
[Related SO question](https://stackoverflow.com/questions/6725890/location-host-vs-location-hostname-and-cross-browser-compatibility) (Although I could not find a reply about cross-browser compatibility)

**Comment by vinyldarkscratch** [comment]
The reason `host` is unsupported in the second page (the `HTMLHyperlinkElementUtils` API) is because that API in general is unsupported in Internet Explorer.  I believe that there may be a slight confusion about the APIs involved in `window.location` -- to clarify, the `HTMLHyperlinkElementUtils` API is unrelated to `window.location`.  The `Location` API is properly supported in all browsers, as the W3 Schools article claims (the article is specifically for the `Location` API and doesn't mention anything about the `HTMLHyperlinkElementUtils` API).  I've given a quick double-check in IE 11 regarding the two properties, just in case.

Hope this information helps!
