### ISSUE TITLE
POV buttons support

### ISSUE THREAD

**Issue by ymaksyuta** [mdn/browser-compat-data#4475]
046d-c215-Logitech Extreme 3D has 4axes, 12 standard buttons and 4 buttons in POV.
GamepadAPI reports 4 axes and 16 buttons detected.
All axes and 12 buttons, except POV work fine.
In Windows 10 Control Panel joystick testing utility POV woks fine.

046d-c215-Logitech Extreme 3D
Firefox Quantum 67.0.4 (64bit)

**Comment by vinyldarkscratch** [comment]
Sorry, I have no idea how this relates to this repository.  Are you trying to report a Firefox bug?  If so, please head over to https://bugzilla.mozilla.org.

If you believe this issue was closed by mistake and this actually *does* relate to browser compatibility data, let me know with more details as to why and I’ll happily reopen this!
