### ISSUE TITLE
Opera: add a range for pre-Chromium versions?

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#4610]
After the addition of WebView <=37 as a range, another possible range came to mind.  While performing research on Chrome and Safari, I often find myself leaving Opera as `true` when changing all Chromium browsers’ versions.  One of the largest arguments I remember which inspired this ranged version was that the user base for WebView versions below 37 is so small we can virtually ignore it.  Couldn’t the same argument go for Opera <=15 (and Opera Android <=14)?

I propose adding these version ranges into Opera.  As a result, users may still contribute more accurate data for the Presto-powered Opera days, but the majority of users and web developers probably would just want to know about the Chromium-based editions.

This relates to #4482.

**Comment by jpmedley** [comment]
I can't comment on the proposal. The reason for doing WebView this way is because before Chromium 37 Android WebView was not a Chromium fork. The old WebView code is not available for examination and there are no devices available for testing. If something is in an early version of Chrome, we know it was in WebView 37 (unless it's on [this list](https://cs.chromium.org/chromium/src/android_webview/tools/system_webview_shell/test/data/webexposed/not-webview-exposed.txt)), and it might have been in pre-Chromium WebView.
