### ISSUE TITLE
Correct transition events Chrome compat data

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#4618]
See https://twitter.com/simevidas/status/1161863223789981696

https://github.com/mdn/browser-compat-data/pull/4103 might have set too many transition events to Chrome 74. `transitionend` is probably supported earlier.

**Comment by WebReflection** [comment]
I've [tested it live here](https://codepen.io/WebReflection/pen/vYBGYLZ?editors=0111#0) and Chrome 49 already works out of the box.

I haven't filed any PR myself because I don't know which jurassic version of Chrome shipped it without webkit prefixes but I believe for once [W3Schools](https://www.w3schools.com/jsref/event_transitionend.asp) has the versioning right.

**Comment by vinyldarkscratch** [comment]
Looking into this some more, it seems like a lot of the confusion came from Google's own documentation.  In their [Chrome 74 release notes](https://developers.google.com/web/updates/2019/04/nic74#transition-events), they say the following:

> The CSS Transitions specification requires that transition events are sent when a transition is enqueued, starts, ends, or is canceled. These events have been supported in other browsers for a while…
>
> But, until now, they weren’t supported in Chrome. In Chrome 74 you can now listen for:
> 
> - transitionrun
> - transitionstart
> - transitionend
> - transitioncancel

But of course, this doesn't make sense based upon our testing.  I'll play around some and see if we can get to the bottom of this!
