### ISSUE TITLE
Are dev/canary versions acceptable?

### ISSUE THREAD

**Issue by merlinpatt** [mdn/browser-compat-data#4658]
`Array.flat` and `Array.flatMap` are noted as not compatible with Microsoft Edge. However, I am seeing these as available in `Version 76.0.151.0 (Official build) Dev (64-bit)`, which is a dev version. I'm a

Is this acceptable to note? If so, how do I note that it's currently in dev?

Furthermore, I am seeing this on the Mac version of Edge. Is that acceptable to test on or do I need to be testing Microsoft Edge on a Microsoft OS?

**Comment by vinyldarkscratch** [comment]
This is a really good question -- so long-story-short, Microsoft Edge has adapted Chromium as their engine recently, and stopped development on their EdgeHTML engine.  Edge's latest development build uses the Chromium engine, however since it has not yet reached a stable release, we haven't added this data into BCD.  Once it's reached stable status though, we'll be working on getting Edge as a Chromium fork in our data.  :wink:  So, for the time being, I'd say that we should hold off on adding any notes regarding the Chromium-based Edge.

Hope this answers your question!
