### ISSUE TITLE
Represent OS specific limitation in a machine-readable way

### ISSUE THREAD

**Issue by teoli2003** [mdn/browser-compat-data#474]
Some features do not work on all operating systems at the same time.
For example, WebVR has different support versions for Windows and macOS in Firefox.

For the moment, we use notes and multiple support versions, but we may want to store OS specific information in a more machine-readable way.

**Comment by vinyldarkscratch** [comment]
This is a pretty old issue, but it's one that I'm interested in seeing this implemented.  I think that having an array of different support versions is the simplest way, with perhaps an `os` property added on that can be `macos`, `windows`, `linux`, `ios`, or `android` (am I missing any here?), or an array of them.  If the property is undefined, then we assume that it's referring to all OSes.

If this is still something planned for implementation, does that sound reasonable?

**Comment by jpmedley** [comment]
There's some complexity here that needs to documented to help the decision making. I'm just providing information. I make one editorial comment, but otherwise don't intend these as arguments either way.
* It would be inconsistent to have desktop OSs in one structure and mobile OSs as separate entries as we have now for example with Android. Where would webviews go?
* Addressing this would mean restructuring all existing BCD and rewriting the code that consumes it. Not something I'd recommend at this point. 
* Chrome generally does a very good job of maintaining feature parity between Mac, Linux, and Windows. Undefined equalling everything would support our edge cases better.

**Comment by vinyldarkscratch** [comment]
Thinking back on this (and considering the age of this issue), I'd say keeping the data in notes is just fine.  It's not too common for a feature to have differences between operating systems it seems (aside from desktop and mobile, which we already have separated into different browsers), and from what we've seen, putting this data in the notes seems sufficient enough.

I think we should simply close this issue.
