### ISSUE TITLE
Single/double spacing in notes?

### ISSUE THREAD

**Issue by queengooborg** [mdn/browser-compat-data#4829]
With all the styling we're incorporating, I'm wondering if we should enforce single or double spacing in between sentences in notes, to maintain a more consistent writing style.  Since double-spaces get rendered as single spaces by default in browsers anyways, I'm thinking we should stick to single spacing, but I figured I'd open up a discussion here!

**Comment by a2sheppy** [comment]
I'm not sure it's necessary to enforce this too rigidly.

**Comment by ddbeck** [comment]
As a reviewer, I really dislike having to make the call about whether to say something to a PR author about double spacing. I don't like double spacing as a matter of preference and it's not typical in this repo, so I feel like I ought to say something. But it's a nitpicky thing that's distracting and unwelcoming to new contributors, so I don't always do it. Enforcement deals with the inconsistency and puts the problem of saying something about it on a script. 👍

**Comment by vinyldarkscratch** [comment]
I opened this issue as I had an exact instance of what @ddbeck is referring to.  A PR I recently reviewed introduced a change to a note that provided a double space (and nothing else on that line).  I decided to merge as-is without requesting a change as I felt it was not particularly reasonable to ask them to revert it, since there’s no written rule on it.  If we can throw it into a linter, it can help reduce these issues in the future!
