### ISSUE TITLE
CSS: `all: revert` works in Firefox?

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#4939]
It shows up for me in devtools and seems to have an effect, but I'm not sure.
It is marked as false in https://developer.mozilla.org/en-US/docs/Web/CSS/all#Browser_compatibility

**Comment by Malvoz** [comment]
With such a generic name "`revert`" (especially in the space of a bug tracker where stuff gets reverted all the time) this bug was a bit harder to find, but indeed looks like this has been available since v67: https://bugzilla.mozilla.org/show_bug.cgi?id=1215878

Also perhaps worth to mention this bug regarding `revert` behaving like `unset` within `@keyframes`: https://bugzilla.mozilla.org/show_bug.cgi?id=1533327
