### ISSUE TITLE
A proposal for pull request subjects

### ISSUE THREAD

**Issue by jpmedley** [mdn/browser-compat-data#5000]
Some email clients have the ability to autolabel emails based on user-defined criteria. I've used this ability for several years to narrow the number of PRs that I have to review from this database. The convention of including affected browsers in PR names helps refine the filtering even further. Hopefull, most of the people reading this are using similar techniques to make their lives easier. 

But I think we can refine this further.

I'd like to propose a specific naming convention and formatting to make autolabeling more precise and to make reviewing emails quicker.

* Use [some] for emails that affect more than one browser. I don't want to be too stringent on this one. Listing Chrome and Firefox separately is fine. What I'm really looking for is a way to easily identify PRs that touch more than two browsers. I'm not in love with the word 'some'. I'm more picky about putting it in brackets or some other format that's easy for machines to read.
* Use [all] when all browsers are touched. These two could probably be replaced with [multi] or something like that. 
* Always put the browser names and labels close to the beginning of the subject. Many subject lines are cut off in inboxes, which means I have to open many emails that I don't read see which browsers it touches. 

We don't need to be authoritarian about this. This is a case where even partial compliance helps a lot.

**Comment by queengooborg** [comment]
Thank you for your proposal, and sorry it has taken so long to respond!  However, I don't think this is something that we can realistically do.  Even if we were to add a guideline to recommend PR titles, I don't imagine that we'll get much compliance (I know I wouldn't remember to do so).

I think that the proposal in #5134 is a much more obtainable solution to filtering PRs per browser.  We could develop a script to ping browser vendors based upon the changes, rather than have the contributor do as such.
