### ISSUE TITLE
Automatic labeler is down?

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#5089]
Hey @ddbeck / @Elchi3, I noticed that labels weren’t automatically applied to the last few PRs that have come in.  I was wondering if the bot had crashed, or if it’s intentionally disabled temporarily?  (No rush, of course — I know you two are heading out the next couple of days!  I’ll act as a guard dragon in the meantime.  😛)

**Comment by vinyldarkscratch** [comment]
Ah, looks like it's back up again!

**Comment by Elchi3** [comment]
I think glitch was down for a bit. We should change to GitHub actions if possible.

**Comment by ddbeck** [comment]
> We should change to GitHub actions if possible.

Seconding this. I'll try to run through the Actions docs sometime this week and see if I can Actions-ify the labeler in a reasonable amount of time. I'll open a PR or issue depending on the outcome.

**Comment by ddbeck** [comment]
For the record, I've reverted the re-titling of the issue and I'm re-closing it. I'd like the record of the labeler being down to persist. The problem was that the labeler was down, but it came back up—the GitHub Actions is a mitigation against future downtime, not a correction to the original problem, which fixed itself.

For the GitHub Actions stuff, I'll open a new issue shortly with a user story and estimate and other things that managers crave. 😃
