### ISSUE TITLE
Mass update Edge data due to engine change

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#5214]
It looks like the new Edge will be powered by Blink 79 and it will be released in January: https://blogs.windows.com/msedgedev/2019/11/04/edge-chromium-release-candidate-get-ready/

In order to update our data, the idea is to use the current "edge" browser and add new versions to it. Currently, we have versions 12 to 18: https://github.com/mdn/browser-compat-data/blob/master/browsers/edge.json

We would then add version 79 as the subsequent version to Edge 18:

```json
"79": {
  "release_date": "2020-01-15",
  "release_notes": "https://docs.microsoft.com/en-us/something",
  "status": "current",
  "engine": "Blink",
  "engine_version": "79"
}
```

Further, we will need to mass update the Edge compat data: 
- Update to version 79 if a feature is supported in Chrome and is not already supported in Edge 12 to 18.
- Add a new range stating "false" if a feature is supported in Edge 12 to 18 but is no longer supported in Chrome 79.
- Other edge (ha!) cases, that we need to think about?!

Work for a mirroring script has been started in https://github.com/mdn/browser-compat-data/pull/4729. It needs to be reviewed and then we need to create a migration to perform this mass-update.

@kypflug how does this plan sound to you? Are you okay with "79" (and following) appearing as version numbers for Edge in MDN and caniuse compat tables?

**Comment by sideshowbarker** [comment]
An alternative would be to create new `browser` entries for Blinked-based Edge 79+ data, with `edge_blink` (or something) as the browser name. And the Browser Compatibility tables in MDN articles would have separate columns *Edge (Legacy)* and *Edge (Blink)*.

The rationale is that Edge 18 and before and Edge 79+ are in fact completely different browsers, with completely different engines. The only thing they have in common is a name.

I recognize that in the case of Opera — a (superficially) similar case of a browser which has also had multiple engines — the update in https://github.com/mdn/browser-compat-data/pull/3877 caused one `opera` browser to be retained, with separate `engine` data. But I think the case for Edge merits different handling — because:

* Edge market share is much greater and so, developers care more about clearly distinguishing the difference between legacy Edge and current Edge than they do about tracking old versions of Opera
* We have the chance to make a clean break with legacy Edge and just treat current Edge as a new browser. Over time, developers aren’t going to care nearly as much about older versions of Edge.
* There are wholesale changes in support data, due to the fact that Blink has support for many more features than legacy Edge did. So it makes sense to just keep the legacy Edge data as-is, to make it more clear that legacy Edge does not support those features.

**Comment by vinyldarkscratch** [comment]
Regarding separating Edge into a separate column, we've had a similar discussion regarding WebView before, but we've decided that separating it was not the best option.  In @ddbeck's comment on https://github.com/mdn/browser-compat-data/issues/4330, they state two very good points of why not to split it based upon the engine:

> It's unlike what we do for other browsers' name, engine, or operating system distribution changes (otherwise, we'd have separate Presto and Chromium Operas, or a multitude of IEs for the various Windows operating systems). And Google doesn't seem to make a naming distinction (like IE and Edge). What would we even call the two browsers?
>     Finally, it's user hostile. For example, to show this data on MDN, there would need to be a second WebView column and we'd need to educate users on what's a very fine distinction about whether or not WebView is distributed as an APK.

Another big part is that unlike Internet Explorer and Edge vs. old Edge and Chromium Edge, Microsoft is not treating the new Edge as a separate browser, and as such, we shouldn't in BCD either.

> Work for a mirroring script has been started in #4729. It needs to be reviewed and then we need to create a migration to perform this mass-update.

We'll certainly have to revise the mirroring script some, but it can definitely help a lot!  Let me see what I can do to smooth this process along.  :wink:

**Comment by vinyldarkscratch** [comment]
Another little thought: would we want to add a ranged value for pre-Chromium Edge when the original value is `true` or `null`?

**Comment by Elchi3** [comment]
Thanks for your thoughts @sideshowbarker! These are good and valid arguments! I think I prefer the way in which just have one Edge browser since this has work well with Opera and others. Also because then we will have no additional browser in the matrix that we always need to set to `false` for new features (this is what we need to do for IE as it is dead).

We encourage browser vendors to take ownership of their browser compat data and this has worked well with Google and Samsung, for instance. So, in the end, I want Microsoft to make the call how we will represent Edge in BCD. Pinging @kypflug again :-) Please see the discussion above.

**Comment by vinyldarkscratch** [comment]
Glad to say that I got something going for this!  I got a huge mirroring done to mirror the Chrome data over to Edge, as well as set the ranged values for existing `true` values (and for some that are `null` in Edge but truthy in Chrome).  I plan to submit PRs for this data soon!  https://github.com/vinyldarkscratch/browser-compat-data/tree/mirror/edge/chromium

**Comment by chris-kruining** [comment]
I am new to this repo, but would like to help out.
Could someone briefly explain what needs to be done to resolve the issues listed?

**Comment by vinyldarkscratch** [comment]
Hey @chris-kruining, thank you for your interest!  Actually, we're pretty much all wrapped up for what needs to be done for this -- all that's left is to review and merge the pull requests.  We'd certainly love to have your help in other areas, though!  Feel free to check out the [contributing document](https://github.com/mdn/browser-compat-data/blob/master/docs/contributing.md#ways-to-contribute) for other ways you can contribute to the repository.

**Comment by Elchi3** [comment]
@kypflug I'm trying to summarize where this stands.

- We've decided to re-use the current Edge column in the compat tables
- We're continuing Edge with version 79+ after versions 12 to 18.
- We've introduced special version numbers:
  - "≤18" - Implemented sometime within EdgeHTML, we just don't know when
  - "≤79" - Definitely supported in Chromium, but possibly also in EdgeHTML

The linked PRs (see above) now aim to mass-update the data based on this logic:
- If we had stored "true" for Edge and it is also supported in Chrome, we're setting it to "≤18"
- If we had stored "null" for Edge and it is also supported in Chrome, we're setting it to "≤79".
- If Chrome has "null", Edge is now "null"
- If Chrome has any version number and it wasn't supported in old Edge, Edge is now 79.
- If Chrome has "false" and Edge has a version number 12-18, we're adding "version_removed: 79" for Edge.
- If Chrome has any "version_removed", Edge gets "version_removed: 79".

For WebExtensions: We assume the same as APIs as Chromium and applied the same logic. Let me know if this is wrong.

If there are any differences to Chrome (different flags enabled, different web platform support), we don't know about it and it will have to be noted manually.

@vinyldarkscratch let me know if you have additional comments about what our plan is here (or if I got the logic wrong).

**Comment by vinyldarkscratch** [comment]
That's about right with the logic, yeah!  The only logic statement that's not present in my mirroring is the part about setting Edge to `null` if Chrome's `null`.  I feel it makes more sense to leave Edge alone in those cases so we keep the original data around, and if we find Chrome doesn't support it whilst trying to find the real numbers, we should add the `version_added` right then and there.

I'm currently working to implement my little bits and pieces of random code into a dedicated portion of the mirroring script as well, so that we'll be able to run this in the future!  _(And so that it's not just lazy copy-pasted snippets of code loosely rigged to perform the desired actions.  😛 )_

**Comment by vinyldarkscratch** [comment]
And done, the mirroring script now incorporates this logic!

**Comment by WebMechanic** [comment]
I found that "Edgium" appears to lack a handfull of CSS features Chrome has implemented, so despite being _pretty close in their build numbers_, their web-features are not necessarily identical.
Like Safari and "non-iOS" WebKits sometimes differ, too.
This can be "seen" in the amount pf passed tests on Lea's https://css3test.com -- don't know how accurate this is however.

**THANKS A LOT TO ALL VOLUNTEER FOR YOUR HARD WORK!!**

**Comment by Elchi3** [comment]
We haven't received further feedback from Microsoft, so we've now went ahead with the approach outlined above. A new package will be released tomorrow and it will include the Edge on Chromium updates throughout the repo.

**Comment by Elchi3** [comment]
Many thanks to @vinyldarkscratch for driving this effort.
