### ISSUE TITLE
Font-display data confusing and/or incorrect

### ISSUE THREAD

**Issue by roelfjan** [mdn/browser-compat-data#5224]
https://caniuse.com/#search=font-display gives two results:
- https://caniuse.com/#feat=mdn-css_at-rules_font-face_font-display
- https://caniuse.com/#feat=css-font-rendering-controls

The issues:
- When I look at CanIUse, they look the same to me, when I read the description. When I check it at MDN, it is actually about: [CSS @rule](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display) & [the FontFace Web API](https://developer.mozilla.org/en-US/docs/Web/API/FontFace). I think the description for https://caniuse.com/#feat=css-font-rendering-controls is not clear that this is about the FontFace Web API.
- Both features are about `font-display`, but have different browser support. Is that correct? I would expect that the browser support would be exactly the same. The result for `search=font-display` also gives the feature with the least browser support first. This can be confusing, because `font-display` as CSS @ rule is supported in more browsers. https://caniuse.com/#feat=css-font-rendering-controls seams correct to me.

**Comment by Elchi3** [comment]
@Fyrd How did you handle duplicate compat data so far? Do you have a proposal how we could make this situation better?

**Comment by vinyldarkscratch** [comment]
It looks to me like CanIUse no longer displays the MDN data for this particular feature, most likely to de-duplicate.  Interestingly enough, the [feature in CanIUse](https://caniuse.com/#feat=css-font-rendering-controls) _is_ referring to the CSS @rule rather than the API, as indicated by all the linked resources talking about the @rule.

I'm thinking that our data is inaccurate for Chrome (all the other browsers match, not to mention CanIUse matches the data for the API feature, and I wouldn't imagine the API and CSS features wouldn't be implemented together).
