### ISSUE TITLE
Prettier: match mozilla-central config?

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#5359]
After doing some research, I found out that `mozilla-central` [has a `.prettierrc` file](https://dxr.mozilla.org/mozilla-central/source/.prettierrc).  It introduces a couple of additional configuration parameters, as well as `es5` rather than `all` for `trailingComma`.  I'm thinking that maybe we should update ours to reflect `mozilla-central`'s?

Pinging @ddbeck for this one.

**Comment by ddbeck** [comment]
I think changing solely for consistency with mozilla-central isn't great. Trying to shadow something external to the MDN team seems unlikely to stick (this isn't a dependency we can easily import). That's the sort of thing that might've worked if we had gotten consensus on an MDN-wide code style, but I'm doubtful such a thing would be well-maintained otherwise.

Unless we have some user story for changing it (e.g., the trailing commas are a problem for a real consumer), my position is to leave it as is. That said, I don't feel strongly about it, so if you want to leave this open until the new year for Florian's take on this, I'm OK with that too.

**Comment by vinyldarkscratch** [comment]
Thanks for your input, @ddbeck, I see what you mean!  I'm mostly thinking about how we can potentially improve the development of the related MDN ADR as well so we can come to a decision on the code styling rules MDN should use.

There are a couple of parts, however, that I think would be useful, such as enforcing the EOL and indentation levels of two spaces.  We have it in our `.editorconfig` file already (which a good number of modern editors support natively, although there's also a number that would require a plugin, or don't support it at all), so I'm thinking we should enforce the `.editorconfig` as well -- I'll open up a new issue for that one.
