### ISSUE TITLE
SpeechRecognition - AR suppourt

### ISSUE THREAD

**Issue by a0m0rajab** [mdn/browser-compat-data#5397]
I have faced a problem while using SR on phones, if the language is set to Arabic, it only recognize even if the Arabic language installed on the phone, It works well if Arabic is the default language but it does not work if the default is English or anything else.

**Comment by vinyldarkscratch** [comment]
Just to check, when you say "phones", what platform are we talking about, as well as what version (i.e. Android 8.0, iOS 13.2...)  Also, what browser(s) is/are this issue happening in?

**Comment by a0m0rajab** [comment]
Okay,
Platform: android
Version: android 9
Browser: chrome version 79

Actually I was thinking it's a general issue not only for my version or phone since we have tried the same app on multiple phones.

**Comment by vinyldarkscratch** [comment]
Thanks for the response!  Have you tried it in other browsers as well, specifically Firefox Android?

**Comment by a0m0rajab** [comment]
You are welcome,

Unfortunately Firefox doesn't support this feature yet 😭

https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition

**Comment by vinyldarkscratch** [comment]
Ah, yeah, probably should have checked compatibility data before asking that question...  😂 

Well, I'll go ahead and ping @jpmedley, our Chrome expert, for this one, so we can help get to the bottom of this!

**Comment by jpmedley** [comment]
I may have to pull in an expert. Let's deal with the low-hanging fruit first. 

Are you running your own code or accessing someone else's website? If it's your own code, are you serving it through a web server as stated in the compatibility note?

Also note that Chrome unprefixed this at some point. I will try to find out when.

Joe

**Comment by jpmedley** [comment]
For when webkit prefix was removed:

* Chrome Desktop: ≤20
* Chrome Android: 25
* Webkit Android: ≤37

@Elchi3 What should I do about the desktop value? That value is as close as I can get because (for this feature, at least) there's no information older than March 2012. "≤20" is not a allowed value in BCD.

**Comment by a0m0rajab** [comment]
> Are you running your own code or accessing someone else's website? If it's your own code, are you serving it through a web server as stated in the compatibility note?

I am running it on my own [website](https://a0m0rajab.github.io/BahisQuraniDev/finder), using github pages feature.

I dont think its casued by the prefix since its working very well with other languages but arabic, yet i will modify this for future concerns :).

**Comment by jpmedley** [comment]
Sorry for being dense. If it's only Arabic, that sounds like a Chrome bug.
Can you please open a ticket.
https://bugs.chromium.org/p/chromium/issues/list

You're the best one to do this since you know the details.
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by vinyldarkscratch** [comment]
Looks like this has been triaged as a Chrome bug, so I'll go ahead and close the issue here in BCD.  Thanks, you two!

> @Elchi3 What should I do about the desktop value? That value is as close as I can get because (for this feature, at least) there's no information older than March 2012. "≤20" is not a allowed value in BCD.

If need be, I own virtual machines for pretty much every browser of every version not offered by SauceLabs, including Chrome 1-25.  Feel free to ping me if you need help tracking down an old version number!

**Comment by a0m0rajab** [comment]
I will just put the [Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1043593&q=%3Arajab-2&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified) link just in case if anyone wanted to follow up in the future.
