### ISSUE TITLE
http.Content-Security-Policy.require-sri-for - Supported in Safari iOS

### ISSUE THREAD

**Issue by ghost** [mdn/browser-compat-data#5430]
`Require-Sri-For` HTTP Header functions is available in iOS. This needs to be updated.

EDIT; Additional Information:

https://webkit.org/status/#feature-subresource-integrity

**Comment by foolip** [comment]
Per https://github.com/mdn/browser-compat-data/pull/15793#issuecomment-1102405792 I suspect this is wrong, but since the report says it's iOS specifically, maybe it's in iOS's network stack and not in WebKit? I sort of doubt that, but some testing might be able to tell.

It's unfortunate that @ghost won't be able to tell us more...

**Comment by queengooborg** [comment]
The spec in the linked feature on WebKit Status doesn't mention `require-sri-for`.  I realize I should've looked more carefully before opening up a PR for this.
