### ISSUE TITLE
Promise.allSettled browser support update

### ISSUE THREAD

**Issue by moonformeli** [mdn/browser-compat-data#5441]
In MDN, `Promise.allSettled`'s browser support is little different from https://v8.dev/features/promise-combinators#promise.all.

So I'm a little confused about which one's correct. Maybe you should edit the safari support status?

**Comment by vinyldarkscratch** [comment]
I was just looking at the support, but it appears there's actually no differences for `Promise.allSettled` between V8's data and our own.  It appears that you linked `Promise.all` in particular (which also has data that matches our own), was that accidental and you were actually wanting to link `Promise.allSettled` a little lower down?

I think it's safe to close this issue, since I see no differences between the data.  Of course, feel free to comment if you think I should reopen the issue and we'll do so right away!
