### ISSUE TITLE
FormData works with iOS 10.3.3

### ISSUE THREAD

**Issue by pcunite** [mdn/browser-compat-data#5517]
I was looking at the _caniuse.com_ website and noted that **FormData** for iOS seemed to only begin at iOS 13.2. I really needed that to **not** be true! So, I tested with an iPhone 5C, and indeed, FormData works just fine. An example below.

```
HTML
<form id="form1" action="upload.php" method="POST" enctype="multipart/form-data">
<label id="bChoose" for="file">Choose</label>
<input id="file" type="file" accept="video/*" name="file" />
</form>

JavaScript
var formData = new FormData(document.getElementById('form1'));
var xhr = new XMLHttpRequest();

etc ...

xhr.open('post', 'http://server/upload.php', true);
xhr.send(formData);
```

**Comment by vinyldarkscratch** [comment]
Hey there, thanks for opening this issue!  I looked at the CanIUse data, and I think I understand what's going on.  Since the data is marked as `true` on our end for Safari iOS, CanIUse renders it as "it's definitely supported in the current version, but we don't know if it's supported in older versions".  I think the simplest fix is to just mirror the Safari Desktop data over to Safari iOS, which I will do so now!
