### ISSUE TITLE
issues in "what are we missing?" section

### ISSUE THREAD

**Issue by luciancic** [mdn/browser-compat-data#5548]
I noticed two issues:
1. If the table row is a deprecated or experimental feature, the word _Deprecated_ or _Experimental_ is appended to the row name. It would be nice to replace it with the thumbs down or flask icon.
2. On some pages, the _next step_ button does not render
[Example page](https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel#Browser_compatibility)

![image](https://user-images.githubusercontent.com/17990875/73004488-6466ab80-3dd5-11ea-8f05-d6035699afdf.png)

I am willing to submit PRs for this, if someone can point me in the right direction.
Cheers!

**Comment by vinyldarkscratch** [comment]
Thanks for letting us know!  I believe that https://github.com/mdn/kuma is the repository you're looking for -- this repo is all about the data itself, rather than the rendering of said data.  (As a result, I'm going to go ahead and close this issue so that we can get another one going in the other repo.)  Someone over there should be able to either fix it up or point you to the appropriate files!
