### ISSUE TITLE
Incorrect information for Chromium Edge 79 RegExp Unicode Property Escapes

### ISSUE THREAD

**Issue by tjcrowder** [mdn/browser-compat-data#5587]
The information for RegExp Unicode Property Escapes Chromium Edge 79 is incorrect, it says it doesn't support them, but it does.

Would I fix that by changing `version_added` to `"79"` for `"edge"` in the relevant object in https://github.com/mdn/browser-compat-data/blob/master/javascript/builtins/RegExp.json?

**Comment by vinyldarkscratch** [comment]
Currently, we don't have data for Chromium-based Edge, other than the version number in the browser releases.  We're looking to perform a script-based mirroring since there's so many data points -- see #5214 for details on that.

(Since this is a sub-issue of the other issue i linked, I'll go ahead and close this issue, and can promise we'll get the Chromium Edge data in ASAP!)
