### ISSUE TITLE
Update browser compatibility of 'proxy' API

### ISSUE THREAD

**Issue by realslimshanky** [mdn/browser-compat-data#5739]
Browser Extension's proxy API ( https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/settings ) also works in Chrome since version 34. Reference: https://developers.chrome.com/extensions/proxy

**Comment by rebloor** [comment]
@realslimshanky as noted on MDN "Google Chrome provides [an extension API also called "proxy"](https://developer.chrome.com/docs/extensions/reference/proxy/) which is functionally similar to this API, in that extensions can use it to implement a proxying policy. However, the design of the Chrome API is completely different to this API. Because this API is incompatible with the Chrome proxy API, this API is only available through the browser namespace." As the compatibility data covers the Firefox version of `proxy`, it's not possible to include details of the Chrome version.
