### ISSUE TITLE
Lazy loading

### ISSUE THREAD

**Issue by Vanawy** [mdn/browser-compat-data#5751]
Lazy loading feature isn't experimental now

https://github.com/whatwg/html/pull/3752/files

**Comment by sideshowbarker** [comment]
It seems (arguably) still experimental, given it’s still so far only shipped in one engine (Blink).

Until 13 days ago, it wasn’t even implemented in more than one browser engine. It only landed in Gecko on 2020-02-12 (per https://bugzilla.mozilla.org/show_bug.cgi?id=1542784) but it won’t ship until Firefox 75 is released in April.

And it’s not yet implemented at all in WebKit; see https://bugs.webkit.org/show_bug.cgi?id=196698

I guess what has actually changed is that until https://github.com/whatwg/html/pull/3752/ was merged in the HTML spec, lazy loading wasn’t even standard yet (because it wasn’t in any spec).

Anyway for now I went ahead and did https://github.com/mdn/browser-compat-data/pull/5759 to update BCD with Firefox `version_added: 75` for it.
