### ISSUE TITLE
Consistency linter: needs to recursively check parent

### ISSUE THREAD

**Issue by wbamberg** [mdn/browser-compat-data#5765]
I'm not sure this is a good idea, but for discussion: I was reviewing https://github.com/mdn/browser-compat-data/pull/5757, and it lists a subfeature of `onAuthRequired` as supported from Firefox 46, when `onAuthRequired` itself is only supported from Firefox 54.

This seems like a thing we might be able to lint for?

**Comment by vinyldarkscratch** [comment]
We actually already have a linter for this — see `linter/lint-consistency.js` — but it looks like the CI passed just fine?  We should certainly look into why the linter didn’t catch it.

**Comment by vinyldarkscratch** [comment]
Ahhhhh, I see what's going on now...  It appears that the consistency checker doesn't recursively check parents.  The new feature is actually a subfeature of another subfeature (called `details`) of `onAuthRequired`, and because `details` doesn't have its own compat statement, the consistency checker silently ignores it.  The consistency check find the earliest parent that has a compat statement.

I'll see if I can get a fix going on for it!

**Comment by wbamberg** [comment]
Nice! Thanks for digging into it @vinyldarkscratch !
