### ISSUE TITLE
Enhancement Suggestion: allowing ranged versions for "version_added" for all browsers

### ISSUE THREAD

**Issue by gorisanson** [mdn/browser-compat-data#5947]
Now the [ranged versions](https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#ranged-versions) is only allowed for Edge, Opera, Opera Android and WebView Android. But I think it would be useful for other browsers too. I think it is would be better narrowing the `"version_added":` by the ranged version than just marking it `"true"`.

For example, in case of #5593, I think it `"version_added": "≤71"` for Firefox `RTCDataChannel.onmessage` is more informative than just `"version_added": "true"`. Since the ranged version is only allowed on some specific browsers now, some information attained by manual testing (as in case of #5593) has been lost.

**Comment by vinyldarkscratch** [comment]
Thanks for your input on the matter!  Actually, we are now working on the next big key result: removing all `true` and `null` values and replacing them with real version numbers (see #3555).  As stated in https://github.com/mdn/browser-compat-data/pull/3881#issuecomment-510426424:

> We've decided against allowing "<=" freely for every version number in BCD as we're unsure about the side effects, data maintenance and to how much imprecise data this would lead to in the long term.

The primary purpose of the browser and version limitations is because those earlier versions are either challenging/impossible to test (ex. WebView), or they're old enough that just providing a ranged value is good enough (ex. Opera).

I'm going to go ahead and close this issue as a result, but I'm happy to reopen!

**Comment by gorisanson** [comment]
Thanks a lot for your detailed explanation! @vinyldarkscratch
