### ISSUE TITLE
Inconsistency of preference name for "Enable Experimental Web Platform features"

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#6009]
Chromium-derived browsers* use an "Experimental Web Platform features" option on the `chrome://flags` page to turn on various features. This flag is represented in BCD in a few different ways:

* In 133 instances, as a `"preference"` with the name `"Experimental Web Platform features"` (or some variation of capitalization, though this one is canonical)
* In 128 instances, as a `"preference"` with the name `"#enable-experimental-web-platform-features"` (this is the fragment which goes directly to that setting in the page)
* It's not done anywhere in BCD currently but, as evidenced by #6004, it is possible to represent it as a `"runtime_flag"` with the name `"--enable-experimental-web-platform-features"`

We ought to commit to using one and only one of these to represent this flag for applicable browsers. Ordinarily, I'd suggest using the most-frequently mentioned choice, but the two forms of the preference are so evenly divided, I'm not sure that's a great option.

\* At least, definitely Chrome, Opera, and Edge but not Android WebView. I'm not sure if Samsung Internet does.

**Comment by ddbeck** [comment]
To be a little more explicit, the most true to the UI form of the preference is probably this, in JSON form:

```json
"flags": [
  {
    "type": "preference",
    "name": "Experimental Web Platform features",
    "value_to_set": "Enabled"
  }
]
```

**Comment by sideshowbarker** [comment]
I think the `#enable-experimental-web-platform-features` form has some benefits:

* downstream consumers can potentially use it to construct a clickable `chrome://flags/#enable-experimental-web-platform-features` URL
* matches the name of the runtime flag (minus the `#` hash character)

So I think that argues a bit in favor of using that form rather than the display form from the UI.

**Comment by ddbeck** [comment]
> downstream consumers can potentially use it to construct a clickable URL

Oh, that's a very compelling point. I think that moves me into the fragment form camp. I believe there are some other Chromium flags we could adapt similarly.

**Comment by Elchi3** [comment]
Thanks for filing this, Daniel! It makes sense to standardize this. I agree with @sideshowbarker on using the `#enable-experimental-web-platform-features` form.

Last I heard, the vendor (Google) would rather not have flag information at all in BCD, so I'm not sure it is worth asking them which form they would prefer us to use. (cc @jpmedley).

**Comment by ddbeck** [comment]
> would rather not have flag information at all in BCD

Yeah, I almost raised that in the original issue. But I wasn't sure if the removal would extend to the non-Google Chromium-based browsers, so we'd likely be left with some inconsistencies anyway.

**Comment by lpd-au** [comment]
The case has actually changed across different versions of Chrome, if you open an old one (eg 44) it's styled as _**e**xperimental Web Platform features_ compared to the current _**E**xperimental Web Platform features_.

**Comment by phistuck** [comment]
`runtime_flag` is for flags that are needed before launching the browser.
`about:config` is regarded as a `preference`.
While `about:flags` sounds like `about:config`, it is different because you must restart the browser (which makes is not a "preference", as no other preference requires a browser restart in Chrome, from what I know). It is just a shortcut/more formal way of specifying flags, but those are still flags.
So in my opinion, `preference`, according to the schema, is not the right choice.
(Then again, I do not care that much, so those were well spent two cents that did not cost a dime.)

**Comment by jpmedley** [comment]
It's correct that Google would prefer these not even be in the compat data. These are for experimentation only. What we're afraid of is web sites telling users to flip these flags. Flags have been known to change names and features have been known to move from one flag to another. An example of the latter is when a feature moves from the Experimental Web Platform Features flag to a feature specific flag. Needless to say, none of this is what we consider a good user experience. 

There are a few other things to note. Flags are generally not usable after a feature becomes available in stable. The exception is that sometimes a particular flag will be defaulted to "enabled" rather than being removed. This only happens when extra time is needed remove the infrastructure behind the flag. **Features in this state should never be construed as being behind a runtime flag.** 

Flag links deliberately don't work as links. I've never heard why, but it seems this discourages links that only work Chrome, which also discourages asking users to flip them.

**Comment by phistuck** [comment]
> Flag urls deliberately don't work as links. I've never heard why, but it seems this discourages links that only work Chrome, which also discourages asking users to flip them.

@jpmedley - chrome:// URLs are privileged URLs that can have a lot of power (changing settings, enabling flags, revealing passwords in some cases), so they are, by default, completely isolated from the open web (or even the local file:// URLs. By the way, HTTP/HTTPS cannot link to file:// URLs as well, due to a similar reason).
I believe it is not about discouraging Chrome-only links (I think that is just a nice side effect), but about security.

**Comment by phistuck** [comment]
> It's correct that Google would prefer these not even be in the compat data. These are for experimentation only.
I think there is merit in exposing this data in one way or another. If you easily know a browser already implemented something, it gives you a bit more leverage to ask them to ship it.
