### ISSUE TITLE
Safari can not handle "Connection: keep-alive" header

### ISSUE THREAD

**Issue by Alexis-Bize** [mdn/browser-compat-data#6154]
According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive the "Connection: keep-alive" header is supported by Safari. Unfortunately, if a website contains it, it won't load.

Tested on various devices with different versions (iOS / MacOS).
Demo: https://keep-alive.now.sh/

Returned headers (Chrome):
![Capture d’écran 2020-05-14 à 21 15 24](https://user-images.githubusercontent.com/1816892/81975961-1b5a9180-9628-11ea-990f-2260bad5f4e9.png)

**Comment by sideshowbarker** [comment]
The https://keep-alive.now.sh/ problem is due to HTTP/2 disallowing `Connection: keep-alive`:

https://tools.ietf.org/html/rfc7540#section-8.1.2.2
> HTTP/2 does not use the Connection header field to indicate connection-specific header fields; in this protocol, connection-specific metadata is conveyed by other means.  An endpoint MUST NOT generate an HTTP/2 message containing connection-specific header fields; any message containing connection-specific header fields MUST be treated as malformed.

So it’s not that Safari can’t handle the `Connection: keep-alive` header; Safari can handle it fine when it’s in HTTP/1.1 response. But it’s not allowed in an HTTP/2 response.

So https://keep-alive.now.sh/ is sending an invalid, malformed HTTP/2 response. I guess the reason it doesn’t also cause a failure in Chrome or Firefox is that those browsers don’t conform to the HTTP/2 spec requirements to treat the response as malformed. But Safari does.

And `curl` also does. So you can reproduce the Safari behavior with `curl`:

> curl -v https\://keep-alive.now.sh/
> …
> \* http2 error: **Invalid HTTP header field** … **name: [connection], value: [keep-alive]**

I’ve added the warning below to the MDN `Connection` and `Keep-Alive` articles.

> Connection-specific header fields such as `Connection` and `Keep-Alive` are prohibited in HTTP/2. Chrome and Firefox ignore them in HTTP/2 responses, but Safari conforms to the HTTP/2 spec requirements and won’t load any response which contains them.

**Comment by Alexis-Bize** [comment]
Oh! I apologize for jumping to conclusions but thanks for the update! Closing :)

**Comment by sideshowbarker** [comment]
Cheers — glad to help get it resolved. And thanks for having taken time to raise it, because it helped to get the related docs improved a bit at least :)
