### ISSUE TITLE
BCD update needed for devicemotion_event?

### ISSUE THREAD

**Issue by mrisher** [mdn/browser-compat-data#6217]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Since iOS 12.x, Safari requires the user to call `DeviceMotionEvent.requestPermission`. I would recommend that the compatability table reference this required permission.

**Comment by queengooborg** [comment]
Sorry it's taken so long to respond to this with progress!  I just begun to work on this, but I noticed a discrepancy between the data for `requestPermission` and this report.  From what I found in testing, `requestPermission` was added in Safari iOS 14.5, but you're saying that it was required since iOS 12.0.  Can you provide some supporting documentation or examples to show it being required in iOS 12.0?

**Comment by queengooborg** [comment]
I'm going to close this because there hasn't been a response and there's not enough information to be able to make any updates.
