### ISSUE TITLE
Most webview_android entries are outdated

### ISSUE THREAD

**Issue by jungshik** [mdn/browser-compat-data#622]
WebView on Android has been backed up by Blink/Chrome since Android Kitkat (4.4). 
Starting with Android Lolipop, it's a separate APK and is auto-updated independent of OS. 

At the moment, most entries for webview_android is different from Chrome or Chrome Android but should be identical for most features. 

See https://developer.chrome.com/multidevice/webview/overview (a bit outdated). 

I'm aware that in the schema, 'webview_android' is specified to be an old/original webview, but what's the point of tracking the old/original webview  given that WebView has been backed up by Chrome/Blink/v8 for over 4 years ?

**Comment by Elchi3** [comment]
CC'ing @jpmedley 

I'm not entirely sure why we have webview_android as a browser. It has been in the old tables, so we added it as part of this project. Joe, can you shed some light why having webview_android is important? What do you think about our current blink based browsers? Does it make sense to have the three?

**Comment by jpmedley** [comment]
Chrome Android and Android Webview are both based on the Chromium code
base, but they don't always have feature parity. Because of this, we break
them out on chromestatus.com <https://www.chromestatus.com>. Compare Network
Quality Signals <https://www.chromestatus.com/features/5108786398232576>
with Media Capture <https://www.chromestatus.com/features/5522768674160640>
for example.

That webview is the old original webview is not how that field is used. If
it were, it would always be false, so it would take up a lot of space with
little value.

Three blink browsers? Actually we have five. Opera is also Chromium-based,
and I recently saw some PRs to start adding the Samsung browser, which is
also Chromium-based. I've been thinking about how to handle that for a
while. Here's what I think:

   - For the remaining hand-built tables, stick with the status quo.
   They're going away, so there's little value in changing them in any major
   way.
   - For the JSON files themselves, list all six browsers so that we work
   towards a complete data set. This should be part of a plan for how other
   browsers are dealt with. This becomes particularly relevant when you
   consider what browsers are growing in the far east.
   - Deal with what should be shown in the display macro. This gives us the
   freedom to change what people see independent of the data and as needs
   change. Long term I can even imagine controls more granular than the
   Desktop/Mobile switch we currently have.


Joe

Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by Elchi3** [comment]
> Chrome Android and Android Webview are both based on the Chromium code base, but they don't always have feature parity. [...] That webview is the old original webview is not how that field is used. If it were, it would always be false, so it would take up a lot of space with little value.

Thanks, this is good information, and clarifies the question of @jungshik as well, I think.

> For the remaining hand-built tables, stick with the status quo. They're going away, so there's little value in changing them in any major way.

Absolutely, the old tables will all disappear in 2018.

> For the JSON files themselves, list all six browsers so that we work towards a complete data set. This should be part of a plan for how other browsers are dealt with. This becomes particularly relevant when you consider what browsers are growing in the far east.

Yes, you are right, there are lot more chromium-based browsers and we're likely going to add a few more of them to the data set.

> Deal with what should be shown in the display macro. This gives us the freedom to change what people see independent of the data and as needs change. Long term I can even imagine controls more granular than the Desktop/Mobile switch we currently have.

Absolutely agree with you. This is one of the reasons we're doing all this work anyway. The data is separated from the displaying. We are well aware of this being an advantage and we have long ago started work to redesign the tables. You can read more about the redesign effort in this thread: https://discourse.mozilla.org/t/beta-testing-new-compatability-tables/21269
