### ISSUE TITLE
img tag / HTMLImageElement error event seems fine everywhere?

### ISSUE THREAD

**Issue by thw0rted** [mdn/browser-compat-data#6395]
The data for the `error` event / `onerror` property says that most desktop browsers (at least IE, Edge, Chrome) have no support, and FF has only supported it since v51.  I don't have any historical data about this, but I tested those 3 browsers today and they all work fine.  I also can't find any notes anywhere online saying that support was added in a particular version, so I suspect that the event may have been supported all along and that #388 just had the wrong data to start with.

cc: @teoli2003 , @Elchi3 maybe?

Ref: #4724

**Comment by jpmedley** [comment]
I don't follow. html/elements/img.json currently shows true for onerror in Chrome and ≤79 for Edge.

**Comment by thw0rted** [comment]
I came here from [the relevant caniuse page](https://caniuse.com/#feat=mdn-api_htmlimageelement_error_event) as well as [the MDN docs page for HTMLImageElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement#Browser_compatibility).  I was under the impression that this repo contained the backing data for those pages.  And [in the later PR I referenced](https://github.com/mdn/browser-compat-data/pull/4724/files#diff-3c538f2883cd76f0686b947db58e7c48R463) I saw

````json
"error_event": {
        "__compat": {
          "mdn_url": "https://developer.mozilla.org/docs/Web/API/HTMLImageElement/error_event",
          "description": "<code>error</code> event",
          "support": {
            "chrome": {
              "version_added": false
            },
````

Does that `false` mean that Chrome does not have support for `error_event`?

I'm sorry I'm not really familiar with the process here, so I don't know how the file I linked (`api/HTMLImageElement.json`) relates to the one you're referring to.

**Comment by jpmedley** [comment]
Usually it does. In this case, it means that whoever created or updated this file didn't bother to look for this event in the inheritance chain. It should be true.

**Comment by ddbeck** [comment]
It looks to me that there was erroneous data in the handwritten table that used to be on MDN and it was ported to browser-compat-data. In the early days, we were less rigorous about checking the data (to complete the migration quickly), so this isn't exactly surprising.

I'd welcome a PR that updates [`api.HTMLImageElement`](https://github.com/mdn/browser-compat-data/blob/master/api/HTMLImageElement.json). You could use `true` or `false` values for cases where we you don't know or can't find the exact version; I'd be happy to work with you in a review to refine the data, where possible.

Thank you for reporting this!

**Comment by jpmedley** [comment]
I think `true`/`false` would be fine for Chrome in this instance. Given the length of this inheritance chain, finding the exact version this arrived in Chrome would be extremely difficult.

**Comment by Kaiido** [comment]
Hum... why is it even listed here? 

[Element/error_event](https://developer.mozilla.org/en-US/docs/Web/API/Element/error_event) and [Window/error_event](https://developer.mozilla.org/en-US/docs/Web/API/Window/error_event) are the places where this is documented *(not sure why it's been split in two pages since both are actually the same, but that's probably for an other issue)*.  

Indeed, the *error_event* that [fires on HTMLImageElement](https://html.spec.whatwg.org/multipage/images.html#updating-the-image-data:event-error) is the [global `error` event](https://html.spec.whatwg.org/multipage/indices.html#event-error).  
Just like `error_event` is not listed in [HTMLScriptElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLScriptElement#Browser_compatibility), [HTMLIframeElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIframeElement#Browser_compatibility) or any other Interfaces where it may fire, it's not clear why it should be in HTMLImageElement's compat table.

Note that some interfaces like [MediaElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/error_event) or [MediaRecorder](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/error_event) and probably a lot of other ones do have their own error_event (which are correctly documented).

**Comment by jpmedley** [comment]
>Just like error_event is not listed in HTMLScriptElement, HTMLIframeElement or any other Interfaces where it may fire, it's not clear why it should be in HTMLImageElement's compat table.

That may very well be more an indication of a lack of discussion about this issue than evidence of any kind plan or requirement. MDN folks would know more about that.

**Comment by jpmedley** [comment]
Based on what's done in other areas, I'm guessing the solution will be that the MDN page will need to say, "Inherits errors from...".

**Comment by jculver050** [comment]
Close

**Comment by queengooborg** [comment]
The event data was removed in #13006 in favor of the `error` event on `Element`, so this issue is resolved!

**Comment by thw0rted** [comment]
@queengooborg do you know how long it's supposed to take for this update to percolate through to [the caniuse page](https://caniuse.com/mdn-api_htmlimageelement_error_event)?

**Comment by queengooborg** [comment]
That's a question for @Fyrd, I would say.

**Comment by thw0rted** [comment]
I just noticed that the PR you linked merged in October, so I would think that if it fixed the issue (at least for caniuse) it would have showed up by now. Maybe I misunderstand how the data is used?

**Comment by Fyrd** [comment]
The caniuse site is updated every week, but I just discovered that older entries weren't deleted when doing updates. As a result the deletion was basically ignored. Have just fixed that though for future cases. Thanks for bringing that to my attention!
