### ISSUE TITLE
RTCDataChannel data for safari_ios appears to be false or outdated

### ISSUE THREAD

**Issue by wis** [mdn/browser-compat-data#6462]
at least some of the false values for safari_ios blamed for this commit https://github.com/mdn/browser-compat-data/commit/091506182300a755a48e00885be78e64f6b87a0d appear to be outdated.

what is the source for all these false values? what tests where used etc.?

I used the web platform tests for webrtc on an IOS simulator provided online by [Expo Snack](https://snack.expo.io)
[wpt.live/webrtc/RTCPeerConnection-createDataChannel.html
](wpt.live/webrtc/RTCPeerConnection-createDataChannel.html)

most tests passed, most importantly the tests with `ordered` false, which current data says Safari IOS doesn't support:
![7](https://user-images.githubusercontent.com/9993663/89116790-c00aa380-d4a0-11ea-9b19-c9c23a5a46d9.png)
![8](https://user-images.githubusercontent.com/9993663/89116792-c13bd080-d4a0-11ea-8a31-38dbe331f33e.png)
![9](https://user-images.githubusercontent.com/9993663/89116793-c1d46700-d4a0-11ea-983d-37c9d48b8711.png)

**Comment by ddbeck** [comment]
Hi @wis, thanks for raising this issue. You asked:

> at least some of the false values for safari_ios blamed for this commit 0915061 appear to be outdated.

> what is the source for all these false values? what tests where used etc.?

The short version is that the data had some automated changes applied. I'd welcome a PR fixing these APIs.

The longer version is that the change you referenced was a largely mechanical change to resolve BCD's internal discrepancies. Some parent features were recorded as unsupported. For such features, we decided that all the descendant features should be marked as unsupported as well. The fundamental problem was that some of our data contradicted itself (since some of the data is was quite old and unverified). We hoped that any mistakes from such an approach would be discovered by the community.

That's a long-winded way of saying, thank you for finding this one. 😃

**Comment by sideshowbarker** [comment]
@wis If you create a PR this one, I’d be willing to make time to review it. And if you need help with creating such a PR, I’d also be happy help with that in any way.

**Comment by jculver050** [comment]
Close

**Comment by vinyldarkscratch** [comment]
I had made the corrections to the RTCDataChannel API (amongst two other RTC APIs) in #7327, so this is now resolved!
