### ISSUE TITLE
Inconsistent standard status and deprecation of NavigatorID properties and methods

### ISSUE THREAD

**Issue by alattalatta** [mdn/browser-compat-data#6567]
There are some inconsistencies within `NavigatorID`. Note that all of the following items are defined within the [spec](https://html.spec.whatwg.org/multipage/system-state.html#navigatorid), even for those marked as non-standard.

# Marked as standard, non-deprecated

- `appCodeName`
- `appName`
- `appVersion`
- `platform`
- `product`
- `userAgent`
- `vendor` (Note: Defined in `Navigator.json`)

# Marked as standard, deprecated

- `taintEnabled()`

# Marked as non-standard, non-deprecated

- `vendorSub` (Note: Defined in `Navigator.json`)

# Marked as non-standard, deprecated

- `oscpu` (Note: Defined in `Navigator.json`)
- `productSub` (Note: Defined in `Navigator.json`)

Considering that _they are defined in the spec_, shouldn't they all be marked as standard? Also, since most of these (except `platform` and `userAgent`) returns a constant or some historic value, IMO they should be deprecated, but I don't know about BCD's policy around deprecation.

**Comment by sideshowbarker** [comment]
> Considering that _they are defined in the spec_, shouldn't they all be marked as standard?

Yes, for sure

> Also, since most of these (except `platform` and `userAgent`) returns a constant or some historic value, IMO they should be deprecated,

Yes. But I think `platform` should also be deprecated – because, while UAs are optionally allowed to return a non-constant value for it, UAs are also allowed to just return the empty string for it. In fact, UAs are *encouraged* to return the empty string for it (and for all other `NavigatorID` members that only optionally have non-constant values); see the *“user agent implementers are strongly urged to include as little information in this API as possible”*.

So I think it is in fact the spec intent that `platform` should not be used or relied on — which effectively means deprecated.

And so, along with `userAgent`, the only other member that should not be marked as deprecated is `vendor` — because the spec does actually require UAs to return a non-constant value for that.

See #6612 for a patch the makes the changes as summarized above.
