### ISSUE TITLE
Huawei Browser?

### ISSUE THREAD

**Issue by davidmaxwaterman** [mdn/browser-compat-data#6660]
Is there a reason the Huawei Browser is missing in the list of browsers?

**Comment by vinyldarkscratch** [comment]
The browser data within BCD is not guaranteed to be a complete list of all the browsers available.  I believe it's because Huawei itself doesn't seem to have as much of a global marketshare as other browsers do, so it was never really added.

I'm not against adding Huawei Browser to the data, though due to the MDN team's shorthandedness, and the current goals to achieve as much data accuracy as possible, it's not quite something within the current scope.  (I'll leave this issue open though, as we can come back to it later.)

**Comment by ddbeck** [comment]
Related to #7238. I hope to have a guideline we can point to for browser additions soon.

**Comment by jculver050** [comment]
Close
