### ISSUE TITLE
Remove polyfills from BCD?

### ISSUE THREAD

**Issue by queengooborg** [mdn/browser-compat-data#6762]
I remember that there was some [discussion on removing polyfills from MDN](https://discourse.mozilla.org/t/mdn-rfc-001-mdn-wiki-pages-shouldnt-be-a-distributor-of-polyfills/24500), but it doesn't look like there was an issue opened here.  When going through the data, I noticed that there's a few notes that mention polyfills.  However, I'm thinking we should remove them.  While it's nice to have polyfills, I don't think that we should include polyfills in BCD, since they may become old and/or abandoned, or simply redundant as browsers implement support.

**Comment by sideshowbarker** [comment]
I don’t have a strong opinion on this personally — but I think ideally we should find a way to ask web developers what they think about the existing polyfill information that we’re providing, and whether they’d miss it if were gone.

I suggest that because I’m not sure we ourselves are the right set of people to make the best call about whether the polyfill information have value — the community of web developers using it are.

I don’t how best to try to poll web developers on this, but maybe the simplest way would be to tweet a twitter poll from the twitter mozdevnet account (in which case it’s likely to be retweeted from some other accounts such as the “html5” one.

Regardless, it would also be good to get @foolip’s POV on this.

**Comment by foolip** [comment]
I suspect that the value of our polyfill notes probably varies a lot across features. Some are probably obscure and not really useful, while some are the gold standard polyfill that "everyone" uses for a feature.

A list of all the polyfill notes we currently know of would be useful. Thinking about criteria for inclusion is easier given those examples.

One challenge I see is that a polyfill is often not specific to an implementation, and yet useful. https://github.com/sindresorhus/screenfull.js is one case that comes to mind.

**Comment by jculver050** [comment]
Close
