### ISSUE TITLE
Private class fields compatibility table is not accurate

### ISSUE THREAD

**Issue by caiolima** [mdn/browser-compat-data#6773]
The problem is that https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields is showing that Safari 14 supports private class fields, but this is not very accurate. Private class fields were added behind a runtime flag on Safari 14, and this flag is disabled by default. This can cause some confusion because it is not well clarified on article and majority of Safari users won't enable such flag.

It's possible to verify it by running the following program on Safari 14:

```
class C {
  #field ;
}

console.log("test");
```

The result is going to be a `SyntaxError` due to unexpected token `#`.

**Comment by ddbeck** [comment]
Yep, this checks out. It looks like [_public_ class fields were added in Safari 14](https://developer.apple.com/documentation/safari-release-notes/safari-14-release-notes#JavaScript) (though some Safari 14 Beta release notes might've reported otherwise).

The data for `javascript.classes.private_class_fields` needs to corrected, around these lines:

https://github.com/mdn/browser-compat-data/blob/3b5724cb58f313455c4992b808357168da8516a8/javascript/classes.json#L509-L514

The `"version_added"` values would need to be set to `false`. I'd welcome a PR fixing this! Thank you!

**Comment by caiolima** [comment]
> Yep, this checks out. It looks like [_public_ class fields were added in Safari 14](https://developer.apple.com/documentation/safari-release-notes/safari-14-release-notes#JavaScript) (though some Safari 14 Beta release notes might've reported otherwise).
> 
> The data for `javascript.classes.private_class_fields` needs to corrected, around these lines:
> 
> https://github.com/mdn/browser-compat-data/blob/3b5724cb58f313455c4992b808357168da8516a8/javascript/classes.json#L509-L514
> 
> The `"version_added"` values would need to be set to `false`. I'd welcome a PR fixing this! Thank you!

Thank you for pointing out where this should be fixed! I just created a PR for it.
