### ISSUE TITLE
Consider moving or copying internal aspect-ratio data

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#6786]
We have data for the CSS property [`aspect-ratio`](https://github.com/mdn/browser-compat-data/blob/master/css/properties/aspect-ratio.json) ([MDN docs](https://developer.mozilla.org/docs/Web/CSS/aspect-ratio)), but it's rather unusual data. We should consider moving or duplicating the data elsewhere.

All of the implementations to date are browser internals, for the purpose of computing the aspect ratio of replaced elements. No browser appears to have actually shipped the `aspect-ratio` property to web developers (though Firefox and Chrome appear to be developing the feature). We currently indicate this through the `partial_implementation` flag; this seems misleading. As far as web developers are concerned, there is no implementation.

The genuinely useful bit for web developers is the subfeature `internal-mapping`, which captures how browsers are using the `width` and `height` attributes of replaced elements to compute the aspect ratio for rendering a page. To me, this feels like the essential thing—but it's more of a feature of _elements_, rather than the `aspect-ratio` property. For example, [the Firefox UA stylesheet _uses_ the property to do this](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio#Examples); it doesn't appear to be a feature _of_ the property. It seems to me that the story here is that browsers have changed the behavior of certain HTML elements' attributes.

(This structure of the existing data was introduced in #5114, which is useful additional reading.)

I propose something that's a bit fussy, but might more accurately reflect the role of the `aspect-ratio` property today:

1. Copy the internal mapping data to new subfeatures of the applicable individual HTML elements. For example, there would be a new subfeature on `html.elements.img` which communicates the aspect ratio set by the element's attributes.
2. Drop the internal mapping data from `aspect-ratio`.
3. Set the `aspect-ratio` data to `"version_added": false` and link to the relevant implementation bugs in the notes.

I'd welcome feedback on this proposal.

**Comment by ddbeck** [comment]
@rachelandrew You were the originator of the `aspect-ratio` property data, so you might be especially interested in this suggestion.

**Comment by rachelandrew** [comment]
That seems a reasonable approach, it was difficult to figure out what to do with it in the first place. 

BTW It's in Canary already as a property. (Here's a pen: https://codepen.io/rachelandrew/pen/WNrRZaV)

**Comment by jensimmons** [comment]
I agree. The CSS property `aspect-ratio` is a completely separate thing from the change to the HTML specification that changes how HTML attributes & CSS-that-resizes-image interact with each other before the image files have downloading reducing layout shift. 

The support table for `aspect-ratio`, (which appears here: https://caniuse.com/mdn-css_properties_aspect-ratio) should be about the `aspect-ratio` property only. "Partial support" is confusing, since the "internal support only for mapped values" part actually has _nothing_ to do with whether or not a developer can start using `aspect-ratio` in CSS.

Meanwhile — there actually already is another set of data for the image loading improvement. You can see it at: https://caniuse.com/mdn-css_properties_aspect-ratio_internal-value 

We don't have to "move" the data — it's already in a second place (and likely also needs to be updated to be accurate). The title of data page also should be changed. It's currently "CSS property: aspect-ratio: Internal mapping of width and height", but again, this change to HTML is separate from the CSS property aspect-ratio. It's here, in the HTML spec:

<img width="1308" alt="HTMLchange" src="https://user-images.githubusercontent.com/108474/94947353-84de1e00-04ab-11eb-8a81-f078e38571ae.png">

This chart of support for an update to how HTML width & height attributes interact with CSS & improve page loading — I've pointed to the Can I Use page for this chart, but the data is from MDN. I just don't know which MDN page it's on. 

It's totally understandable why this confusion happened. It reflects the journey that the humans took while figuring out these two separate specs. But now that things are sorted out, it'd be great to present a clear message to developers.

**Comment by rachelandrew** [comment]
We also have this issue which relates: https://bugzilla.mozilla.org/show_bug.cgi?id=1639963 

Looks like basic blocks and replaced elements are behind `layout.css.aspect-ratio.enabled` right now, as I have this on a list of CSS things to update. So I can always do this update if we have decided it's the way to go.

**Comment by ddbeck** [comment]
Thank you for the feedback, @rachelandrew and @jensimmons.

> The support table for aspect-ratio, (which appears here: https://caniuse.com/mdn-css_properties_aspect-ratio) should be about the aspect-ratio property only. "Partial support" is confusing, since the "internal support only for mapped values" part actually has nothing to do with whether or not a developer can start using aspect-ratio in CSS.
>
> Meanwhile — there actually already is another set of data for the image loading improvement. You can see it at: https://caniuse.com/mdn-css_properties_aspect-ratio_internal-value

To be clear on this, the data I'm talking about in the issue description is data that appears in these caniuse pages. It appears on caniuse the way it does because of where the data is in BCD. To fix this—to separate the width/height to aspect ratio data from the CSS property—it must move off the `css.properties.aspect-ratio` feature.

But it sounds like we're in agreement that this is not a feature of the `aspect-ratio` property. Soon, I'll start work on a PR to represent this as features of the `width`-and-`height` supporting elements (i.e., `html.elements.{canvas,embed,iframe,img,input,object,video}.aspect_ratio` or similar).

  (I'm still a bit annoyed that it's going to result in some duplication, but I don't see how else to fit it into the schema.)

**Comment by rachelandrew** [comment]
@ddbeck cool, do you want me to update the CSS BCD to only include support for the property as it can be used by developers (given we now have some behind a flag implementations)?

**Comment by ddbeck** [comment]
@rachelandrew yes, if you would open a PR for the property data that would be very much appreciated and I would be happy to review it!

**Comment by rachelandrew** [comment]
@ddbeck PR here: https://github.com/mdn/browser-compat-data/pull/6903

**Comment by ddbeck** [comment]
And I've opened #6918 to relocate the data as planned
