### ISSUE TITLE
Confirm or update inputmode for Firefox (desktop)

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#6921]
#6782 indicated that the desktop data `inputmode` global attribute data needs updating for desktop Firefox. We should check what the current status of `inputmode` is (whether behind a preference or not) and update the data, if needed.

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode
https://developer.mozilla.org/docs/Web/API/HTMLElement/inputMode

**Comment by makotokato** [comment]
Desktop Firefox is https://bugzilla.mozilla.org/show_bug.cgi?id=1205133. This attribute isn't shipped on desktop yet.

Also, other browsers (Safari and Chrome) are shipped. But due to OS API limitation, it may be DOM binding only. Example, Safari/macOS has no on screen keyboard, so this attribute isn't used.
And Chrome/Windows supports on screen keyboard, so this attribute is used on software keyboard, but I don't know on Chrome/macOS and etc.

@dtapuska
I don't know whether Chrome/macOS, Chrome/ChromeOS and Chrome/Linux support `inputmode` attribute (`inputMode` property) on software keyboard UI, I make sense that DOM binding is implemented on all platforms, but I don't know about UX of software keyboard layout.

Does Chrome (macOS, ChromeOS and Linux) support changing layout of software keyboard by `inputmode`?  As long as I know, Windows and Android support layout change by `inputmode`, but I don't know other platforms.

**Comment by queengooborg** [comment]
It looks like this has been taken care of by #13355, which indicates the feature was shipped in Firefox Desktop in Fx 95.  This matches the linked bug!
