### ISSUE TITLE
Update CSP meta for Chrome

### ISSUE THREAD

**Issue by larowlan** [mdn/browser-compat-data#6998]
In my testing Chrome respects CSP rules set via the meta field.
https://caniuse.com/mdn-http_headers_csp_content-security-policy_meta-element-support

Lists it as unknown.

**Comment by sideshowbarker** [comment]
That https://caniuse.com/mdn-http_headers_csp_content-security-policy_meta-element-support browser-version data doesn’t seem to match what’s in BCD:

https://github.com/mdn/browser-compat-data/blob/c31d61db5c146655ecb99fee28d367924b0f7329/http/headers/content-security-policy.json#L657-L663

So, seems like here might be a caniuse.com bug in how it’s consuming the BCD data for that. @Fyrd, any clues?

**Comment by larowlan** [comment]
Oh, awesome - should I close this?

**Comment by sideshowbarker** [comment]
> Oh, awesome - should I close this?

Nah, let’s keep it open for now — because I guess it’s possible the data for this feature has some quirk that’s breaking how it’s getting consumed (though looking through it, I can’t see anything obvious).

But if you can also open an issue for this at https://github.com/Fyrd/caniuse/issues, that would be great — and post a link here. Then if @Fyrd weighs in here to confirm it’s actually a caniuse.com bug, we can close this then.

**Comment by Fyrd** [comment]
Yup, it was a dumb caniuse bug. Should be fixed now.

**Comment by sideshowbarker** [comment]
> Should be fixed now.

Super — thanks much

**Comment by larowlan** [comment]
🤝 nice work - thanks everyone
