### ISSUE TITLE
inputmode=none does not work as specced on iOS Safari

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#7186]
[CSS-Trick claims that inputmode=none does not prevent virtual keyboard on iOS Safari](https://css-tricks.com/everything-you-ever-wanted-to-know-about-inputmode/). We need to check whether this is true and add a note about it.

See also #5085

**Comment by makotokato** [comment]
I guess this is bug (reported as https://bugs.webkit.org/show_bug.cgi?id=200361). This is implemented by https://bugs.webkit.org/show_bug.cgi?id=188896, but UIKit part is backed out by https://bugs.webkit.org/show_bug.cgi?id=198141. But, this is still implemented on DOM binding part.

Some platforms on all engines have no effect for this `inputmode` value since platform UX part isn't implemented.  This discussion is https://github.com/mdn/browser-compat-data/issues/6914 and https://github.com/mdn/browser-compat-data/issues/6921
