### ISSUE TITLE
Allow rebase merging for pull requests for this project in the GitHub settings UI 

### ISSUE THREAD

**Issue by sideshowbarker** [mdn/browser-compat-data#7368]
This is a request that we consider checking the **Allow rebase merging** option in the GitHub settings UI for this project at https://github.com/mdn/browser-compat-data/settings (currently we only have **Allow squash merging** checked).

The result of doing that would be: when a PR branch has multiple commits, we could choose to merge each of the commits as-is to the main branch, rather than squashing them all down into a single commit.

See https://github.com/mdn/browser-compat-data/pull/7263#issuecomment-721623562 for a specific case where this came up recently. But in general the rationale it is that sometimes either:

1. Someone creates a PR which from its start is intentionally constructed from multiple commits; or
2. Someone may start a PR with a single commit but add further commits during review.

For case <span>#</span>2, most often we just want to squash the further commits, but not always.

For case <span>#</span>1, it’s more likely we might want to preserve the original multiple commits as-is.

As far as deciding when we’d want to preserve the original multiple commits as-is on the main branch, the criteria include:

* The separate commit messages have separate good explanations detailing the changes that were made (that’s the case which was commented on in https://github.com/mdn/browser-compat-data/pull/7263#issuecomment-721623562).
* Due to the complexity of the changes, breaking them up into separate commits keeps the change history more clear in the future — to us and to anybody else who goes back and looks through the change history.

As far as the case <span>#</span>1 thing of starting a PR intentionally constructed from multiple commits, there are couple reasons:

* when you want to make it easier for reviewers to review each commit separately
* when one of the commits is something you’re not certain we’ll have agreement to change — and so you want to anticipate the possibility that, during review, we decide to drop that part of the change (which is easier if it’s a separate commit)

Arguably in those cases, you could just make separate PRs for each commit; but the reason I personally don’t sometimes is when it seems better for review purposes to put them together; that is, in where the commits are very closely related to each other, in such as way that it seems to make the most sense to have them reviewed at the same time.

**Comment by ddbeck** [comment]
These are good points, @sideshowbarker. As someone who likes to use the commits in a PR to tell the reviewer a story, I agree that it would sometimes be helpful to retain that history. Before turning on the option, I have a couple of questions/concerns:

1. Do we know what the default merge choice would be? One of the nice things about squashing is that GitHub populates the commit message with the PR number. This is often the only (and best) source of details supporting the change (e.g., there's no corresponding issue or the link to citations was not included in the commit message). Having the reference back to the PR is invaluable in those cases. Can we do anything to make sure that this most common case continues to be the path of least resistance?

2. Can we come up with some brief guidelines for peers/owners to make sure we're using the right merge strategy? For my part, I'd prefer that commits on `master` always link to an issue or PR (we're not 100% successful at this yet and this is my fault, when it comes to releases), or contain the meaningful details from the PR description. (Or perhaps there's some preexisting GitHub Actions automation that might help here.)

Also, as a historical note, I tried to find the original discussion about turning on squash merges in the first place and I was unsuccessful. Perhaps @Elchi3 can shed some light on why we chose this route in the first place.

**Comment by Elchi3** [comment]
> Also, as a historical note, I tried to find the original discussion about turning on squash merges in the first place and I was unsuccessful. Perhaps @Elchi3 can shed some light on why we chose this route in the first place.

I'm not sure 100% anymore, but I think it had to do with two things:

1) Like Daniel says, it is beneficial if every commit points to a PR because PRs often contain evidence about the correctness of the compat data change (at least we strongly encourage everyone to leave useful information in PR descriptions/discussions). This allows us to be a bit more lazy with the actual commit messages.

2) When we started the BCD project, we had a data migration racing going on. It was done manually with the help of the community. To give everyone the same amount of credits in the commit history and in the repo's community stats page, we set things to squash merge only. It also helped to encourage well-sized PRs for better review throughput at the time.

The migration is long done and that said, I think we can allow _rebase merging_ now. When we use that merge strategy, I would say we are required to pay attention to the commits and the messages, though. The default can still be _squash merging_ as I think it works quite well for the majority of the cases still.

**Comment by jculver050** [comment]
Close

**Comment by queengooborg** [comment]
Rebase merging has not been requested again since this issue was opened (as far as I know), and in the cases where retaining the separate commits would be better than squashing them together, I believe that creating separate PRs makes more sense.  Additionally, @Elchi3's point about needing to pay attention to commits and their messages is a big one.  Not only do we have to be careful about the commit messages, we also have no ability to make changes ourselves if needed, since the `main` branch is protected and can't be force pushed.

Also, I _heavily_ rely on the PR numbers within commit messages when tracing the history of a change.  Rebase merging would end up breaking that workflow, so I'm strongly against rebase merging.

I'm going to close this issue as "not planned", but I'm happy to discuss this further and for this issue to be reopened.
