### ISSUE TITLE
@media (hover: hover) feature not working on firefox 83.0

### ISSUE THREAD

**Issue by icarthik** [mdn/browser-compat-data#7541]
Hello,
I believe that media feature support for hover: hover and pointer: fine are provided starting firefox 64.0.
But to my surprise, the media hover feature is not working on my firefox 83.0.

Here is a simple code example:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <style>
      .container {
        width: 100vw;
        height: 100vh;
        background-color: #fff;
      }

      @media (hover: hover) {
        .container:hover {
          background-color: #333;
        }
      }
    </style>
  </head>
  <body>
    <div class="container"></div>
  </body>
</html>
```

**Comment by icarthik** [comment]
It's Buggy. The @media (hover:hover) feature works the first time when the page is loaded. But doesn't work either after a page reload or when switched to touch device using dev tools and then back again to desktop mode. I tried opening the page on the firefox standard edition, instead of the developer edition (while developer edition still running), but the hover states still doesn't work.

Recently I have started using firefox for my web development project because of the intuitive css layout features and ease of trying different variations of css styles and DOM elements. But what value does it add at the end, when some crucial features like the @media features are buggy???

I have started using chrome again for now to continue my development as there is no response from your team...
Though I would love to use firefox if this bug is fixed, if it is a bug.

**Comment by ddbeck** [comment]
Hi @icarthik, thanks for bringing this up.

I took a closer look at the feature and I wasn't able to reproduce the problems with the `@media` hover feature that you reported. Without something more concrete to report to other Web developers, I don't think there's any change we can make here on the browser-compat-data (BCD) project (and, in any case, the behavior of dev tools is out of scope for BCD).

I encourage you to report your bug to the Firefox development team at https://bugzilla.mozilla.org/. If your bug(s) can be confirmed, then we could revisit the issue here and add a note to the Firefox data, but in the meantime, I'm going to close this issue. Let me know if you have any questions about this decision. Thank you!
