### ISSUE TITLE
window.sidebar should contain subfeatures

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#7548]
Notes on window.sidebar reference subfeatures which create for confusing notes. We should probably break this out into subfeatures

https://github.com/mdn/browser-compat-data/blob/71b933b6daf1e09f724ec4794d97e3457cd56597/api/Window.json#L9017-L9065

**Comment by foolip** [comment]
I didn't recognize `window.sidebar`, so I took a look. Turns out that `window.sidebar === window.external` in Firefox, so the fix should probably rather be to redirect https://developer.mozilla.org/en-US/docs/Web/API/Window/sidebar to https://developer.mozilla.org/en-US/docs/Web/API/Window/external. The BCD data for `window.sidebar` subfeatures would then not show up anywhere.

**Comment by ddbeck** [comment]
In that case, `window.external` has the same problem: it should have subfeatures for its methods, plus Firefox ought to have an `alternative_name` statement for `window.external`.

**Comment by foolip** [comment]
Yeah, maybe this can be collapsed with an alt. name statement, that would be nice.

**Comment by queengooborg** [comment]
Since `window.sidebar` is now merged into `window.external`, I think we can close this issue.
