### ISSUE TITLE
Contributor stats are wrong from 3.0.0 release

### ISSUE THREAD

**Issue by sideshowbarker** [mdn/browser-compat-data#7626]
The Statistics section of https://github.com/mdn/browser-compat-data/releases/tag/v3.0.0 says “482 total contributors” but the actual number should be 732 or more (as of right now, we’re at 734).

I guess this week something went wrong with the part of the script which collects that data item.

**Comment by ddbeck** [comment]
Thank you for catching this. I have just corrected it. I mistakenly entered the "Used by" number from the repo, instead of the contributors number.

The contributor information is entered manually because the [contributors API](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#list-repository-contributors) has a bunch of limitations that makes it hard to use for this purpose. Maybe we could scrape it instead. Or just accept that we'll have this sort of problem from time to time.

**Comment by sideshowbarker** [comment]
> The contributor information is entered manually because the [contributors API](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#list-repository-contributors) has a bunch of limitations that makes it hard to use for this purpose. Maybe we could scrape it instead. Or just accept that we'll have this sort of problem from time to time.

I think it‘s fine just to accept that we’ll have this sort of problem from time to time. Relative to everything else, I don’t think it’s a big enough problem to merit investing more time in right now. So I’ll close this, with thanks for fixing the data for this release
