### ISSUE TITLE
Chrome does not expose FontFaceSet

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#7662]
It's marked as supported but it currently does not expose the interface to the global. https://github.com/mdn/browser-compat-data/blob/af4fb4307e0812ba51ed9cb9c9277f4a749f59a1/api/FontFaceSet.json#L3-L9

**Comment by queengooborg** [comment]
Other than Safari, this interface seems to only be exposed via `document.fonts`.  I think that the BCD represents this well enough with the constructor data, but maybe it should be clarified in the MDN content?

**Comment by saschanaz** [comment]
BCD seems wrong about Firefox support, as it does expose `FontFaceSet` 👀

**Comment by saschanaz** [comment]
Also, how can one know from the "No" data that it has no exposure? There should be at least two cases for unsupported constructors:

1. No constructor function at all
1. It exists but is not really callable

**Comment by queengooborg** [comment]
I don't think we need to differentiate between these two cases.  If the interface is exposed on its own, but you can't construct it or do anything with it other than use `document.fonts`, how helpful would recording that data be?  Web developers would simply wish to know whether they can construct a `FontFaceSet` instance or not.

**Comment by saschanaz** [comment]
I think it would be mainly about historical data, since all the specifications except WebGL have changed to expose the constructors to consistently allow `font instanceof FontFaceSet`. This one is just one of the remaining historical remnants.

**Comment by queengooborg** [comment]
@ddbeck, do you have any opinion on this?

**Comment by ddbeck** [comment]
This seems like an application of partial implementation, right? It's something like this:

https://github.com/mdn/browser-compat-data/blob/21a90d153c40d2d3707da57d63fff5d4e5cd5bec/api/SVGGeometryElement.json#L15-L16

where an interface is implemented such that there exist objects which implement the interface, but the name isn't exposed. If _nobody_ exposed it and it was only available via one property, I'd probably treat it a little like a dictionary. But since one browser does expose it, I'd probably use partial and notes to explain what's going on.
