### ISSUE TITLE
ContactPicker API only on Android?

### ISSUE THREAD

**Issue by hamishwillee** [mdn/browser-compat-data#7851]
[Contact Picker API](https://developer.mozilla.org/en-US/docs/Web/API/Contact_Picker_API) indicates support on Chrome 80+. However I think this is only supported on Android.

This is based on chrome test where I ran code on desktop:
```
  let test1 = window.ContactsManager;
  let test2 = navigator.contacts;
```
However both cases these are `undefined`. I then looked at https://web.dev/contact-picker/ and this states "only in android".

> Note, test in docs is `const supported = ('contacts' in navigator && 'ContactsManager' in window);` - but there is no indication that `window.ContactsManager` is defined other than that mention of it.

Can we confirm?

Further, we have https://github.com/mdn/browser-compat-data/blob/master/api/ContactsManager.json , but I can't find a defined attribute `navigator.contacts` in https://github.com/mdn/browser-compat-data/blob/master/api/Navigator.json . Would this just be an omission?

**Comment by ddbeck** [comment]
cc: @jpmedley since you added the original `ContactsManager` data in #6277.

I suspect the missing Navigator feature is an omission (and I'd be happy to see a PR adding it).

The https://web.dev/contact-picker/ article links to [a Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=860467) that appears to substantiate the Android-only aspect, though I don't know if there's been any work on expanding that since or what that means for WebView. Perhaps Joe can shed some light on that part of the story.

**Comment by hamishwillee** [comment]
@ddbeck Thanks very much. I've created draft PR for adding Navigator.contacts #8010 - obviously has to be draft until the above questions are resolved. 

@jpmedley in addition to the above, do you know if any additional work has happened to standardize this (currently it is marked as non-standard in the docs and there is no spec listed).

**Comment by ddbeck** [comment]
There's [a spec](https://wicg.github.io/contact-api/spec/), but it's one of these WICG "not a W3C Standard nor is it on the W3C Standards Track" specifications

**Comment by hamishwillee** [comment]
OK, I've added spec in https://github.com/mdn/content/pull/750 (thanks) and added BCD update for ContactsManager in 
https://github.com/mdn/browser-compat-data/pull/8446

When the BCD entries go in then I will add a note in the [API docs](https://developer.mozilla.org/en-US/docs/Web/API/Contact_Picker_API) that this is currently only enabled for android

**Comment by Rumyra** [comment]
I added these docs recently (I was working with @jpmedley :) ) - I will take a look at this today. Apologies I can't remember off the top of my head 😆

**Comment by Rumyra** [comment]
It appears Chrome 80 Android is correct https://chromestatus.com/feature/6511327140904960

**Comment by hamishwillee** [comment]
Great. The linked items say that (https://github.com/mdn/browser-compat-data/pull/8446 and https://github.com/mdn/browser-compat-data/pull/8010 )

**Comment by jpmedley** [comment]
Sorry for the late reply. I've been out of the office for a while. 

@hamishwillee I wouldn't make any mention of this in the text. Since that's what the BCD is for, it's hit or miss whether a later contributor would think to check the text if the situation ever changed.

Since I've been out of the loop for so long, are there any outstanding questions on this?

**Comment by ddbeck** [comment]
> I wouldn't make any mention of this in the text. Since that's what the BCD is for, it's hit or miss whether a later contributor would think to check the text if the situation ever changed.

Seconding @jpmedley on this. I would keep browser-specific compat details out of the body text of an MDN page if at all possible. BCD is in a much better position to keep that info up to date.

> Since I've been out of the loop for so long, are there any outstanding questions on this?

Since #8010 and #8446 have been merged, I think this is taken care of. I'm closing it now, but if there are any remaining questions on this, @hamishwillee, we can reopen this.

**Comment by hamishwillee** [comment]
Thanks. Back from holiday. All good by me!
