### ISSUE TITLE
Add browser published date

### ISSUE THREAD

**Issue by heramerom** [mdn/browser-compat-data#8501]
This is a feature request.

Browser compatibility show the browser version, it's very useful, but I think the browser published date is also useful. So the developers can determine use the api or not easily.

![image](https://user-images.githubusercontent.com/4046709/103433570-2ea98400-4c2e-11eb-8b65-4cf91bae90e3.png)

**Comment by vinyldarkscratch** [comment]
There's been some discussion about this before, see https://github.com/mdn/kumascript/issues/1119.  It doesn't look like the issue was transferred to https://github.com/mdn/yari, would you be willing to open up an issue in that repository (or find an existing one)?  This repository is solely for the content, not really the display of said content.
