### ISSUE TITLE
css.properties.background-attachment - local background attachment not working Safari 14.0.1

### ISSUE THREAD

**Issue by rexgarland** [mdn/browser-compat-data#8513]
#### What information was incorrect, unhelpful, or incomplete?
Safari 14.0.1 browser compatibility appears broken for "background-attachment: local;"

#### What did you expect to see?
I expected the background to scroll with text.

#### Did you test this? If so, how?
On the mdn page demo for background-attachment with "local" selected, the background scrolls with text on Chrome but not Safari 14.0.1.

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.background-attachment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/background-attachment
* Report started: 2021-01-03T04:25:31.266Z

</details>

**Comment by ddbeck** [comment]
Hi @rexgarland and thanks for reporting this.

It does appear that this issue exists in 14.0.1, but not in 14.0.2. There's an open, unconfirmed WebKit bug for this https://bugs.webkit.org/show_bug.cgi?id=219324.

That said, this feels a bit transient for inclusion into BCD. [As a rule](https://github.com/mdn/browser-compat-data/blob/master/docs/data-guidelines.md#release-lines-and-backported-features), we record data that's generally relevant to a line of releases under a significant version number (e.g., 14), rather than recording data for every patch release. If this bug were long-lived, I'd be more enthusiastic about including it as a note, but it appears that the bug will have a short life.

I'm going to close this issue, but do let me know if you have any questions. Thank you!

**Comment by rexgarland** [comment]
Gotcha. First bug report for me... thanks for the tip!

Cheers
