### ISSUE TITLE
html.elements.input.input-time - chrome compatibility regression

### ISSUE THREAD

**Issue by idefy** [mdn/browser-compat-data#8697]
Chrome 87 windows or mobile.

#### What information was incorrect, unhelpful, or incomplete?
Chrome support: since Google changed to a different input/design, it does not support some parameters for instance STEP is not supported anymore

#### What did you expect to see?
Chrome support should now show : partial support, not full support.

#### Did you test this? If so, how?
Yes, by using own code.
Can be tested on the browser with this: https://codepen.io/idefy/pen/YzGOGYb

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.input.input-time`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time
* Report started: 2021-01-10T20:49:22.104Z

</details>

**Comment by ddbeck** [comment]
Hi @idefy and thanks for reporting this. I'm not sure there's anything to be done here, unfortunately.

I took a few minutes to look around and it appears that this was previously reported as [Chromium bug 1105339](https://bugs.chromium.org/p/chromium/issues/detail?id=1105339). It was closed as wontfix; apparently this behavior is intentional.

Reading [the specification](https://html.spec.whatwg.org/#time-state-(type=time)) for the time input, I don't think it's obligatory for user agents to have the old Chrome behavior (or the new), so marking support for this feature as partial wouldn't be appropriate. A change in UI which doesn't present a compatibility problem with respect to other browsers is not really in-scope for BCD either, unfortunately.

I'm guessing that wasn't really the outcome you were hoping for, but I wanted to thank you again for reporting this.

**Comment by idefy** [comment]
Thank you for the detailed answer. Reading through the original bug report I see that the recommended solution is to use a datalist. May be it would be worth mentioning this in the input time documentation as a possible solution. It's not the best option either, as it won't automatically adapt to user locale (24/12hours) but you get a UI that matches validation rules and doesn't confuse the user. In our company this is considered a bug: if the UI allows it, it is valid, but not everyone has the same definition of accessibility and UX :)

**Comment by ddbeck** [comment]
Documenting the workaround with `<datalist>` on the time input page is a great idea, @idefy. Would you be willing to open [a new issue on mdn/content](https://github.com/mdn/content/issues/new) requesting that? Content issues have a way getting lost here in BCD.
