### ISSUE TITLE
Safari supports pointer events since version 13

### ISSUE THREAD

**Issue by Rezakarimi66** [mdn/browser-compat-data#8709]
#### What information was incorrect, unhelpful, or incomplete?
Safari supports pointer events.  

#### What did you expect to see?
https://caniuse.com/?search=pointerevent

#### Did you test this? If so, how?
No

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLElement.pointerenter_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/pointerenter_event
* Report started: 2021-01-12T07:37:56.350Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @Rezakarimi66.

The [Safari 13 release notes](https://developer.apple.com/documentation/safari-release-notes/safari-13-release-notes) seem to back up caniuse's data:

> Added support for the Pointer Events API enabling consistent access to mouse, trackpad, touch, and Apple Pencil events

Narrowly, this can be fixed with an edit to the Safari and Safari for iOS data in the `pointerenter_event` feature in [`HTMLElement.json`](https://github.com/mdn/browser-compat-data/blob/master/api/HTMLElement.json#L2510-L2590). I'd welcome a PR addressing this specifically, if you (or another contributor) would like to fix that specifically.

It's likely, however, that we'd want to test and update the other events in [the Pointer Events specification](https://w3c.github.io/pointerevents/), too, such as `pointerover` and `pointerdown`. There's a number of features involved, unfortunately, so the first step is probably to make a list of the features that the spec involves.

**Comment by ddbeck** [comment]
#8713 fixes this for `pointerenter`. 👍

**Comment by ddbeck** [comment]
I missed some previous related issues. But since this one contains more information, I'm marking them as duplicates of this one.

- #8747 - `pointerup`
- #7898, #8788 - `pointerdown`

**Comment by ddbeck** [comment]
#9455 fixes a bunch of these.

Also, for the record, the Pointer Events spec defines these events:

- `gotpointercapture`
- `lostpointercapture`
- `pointercancel`
- `pointerdown`
- `pointerenter`
- `pointerleave`
- `pointermove`
- `pointerout`
- `pointerover`
- `pointerrawupdate`
- `pointerup`

**Comment by ddbeck** [comment]
When complete, #9596 ought to resolve the remaining Safari pointer events data.
