### ISSUE TITLE
api.Geolocation - <CHROME ISSUE>

### ISSUE THREAD

**Issue by shannonwoolis** [mdn/browser-compat-data#8737]
Hello,

The API doesn't seem to work on Chrome (Version 87.0.4280.88 (Official Build) (x86_64))

I'm on macOS Big Sur.

It seems to work fine on Firefox and Safari.

I have tried a couple of different sites, including your own test box.

Please could you look into this?

Thanks!

<details>
<summary>MDN page report details</summary>

* Query: `api.Geolocation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API
* Report started: 2021-01-13T09:25:25.988Z

</details>

**Comment by ddbeck** [comment]
Hi @shannonwoolis and thanks for reporting this.

I looked into the availability of the API and Chrome does expose the API (e.g., `navigator.geolocation` is a `Geolocation` object). That said, you're right that the live sample on MDN does not work properly (it works [standalone](https://yari-demos.prod.mdn.mozit.cloud/en-us/docs/web/api/geolocation_api/using_the_geolocation_api/_samples_/Examples) but not in the iframe on MDN).

Since this appears to be more of a content issue than a compatibility issue, I suggest that your report this as an issue on [mdn/content](https://github.com/mdn/content/) instead. Thank you!
