### ISSUE TITLE
api.DOMTokenList.toggle - <Mozilla Dropdown problem>

### ISSUE THREAD

**Issue by Lese08** [mdn/browser-compat-data#8748]
#### What did you expect to see?
I have a toggle function when I hover a select tag element. When I click and un-hover to select from the dropdown list, the dropdown list closes.

#### Did you test this? If so, how?
Yes I am currently creating a component framework and I realized that Mozilla browser is having trouble with the toggle function.
I have used .onmouseover, .onmouseout, and .onclick to test my dropdown and nothing works so far.

<details>
<summary>MDN page report details</summary>

* Query: `api.DOMTokenList.toggle`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle
* Report started: 2021-01-14T06:28:48.274Z

</details>

**Comment by ddbeck** [comment]
Hi @Lese08 and thanks for reporting this issue. I tested the API myself and I was able to get the `DOMTokenList.toggle()` method to behave as expected (with the `classList` of an HTML element). This suggests that the compatibility data we have is correct about this API, at least. Since it sounds like you're working on a more complex problem, it may be that you're having trouble with another API.

If you still think there's a problem with this API that is not reflected in the compatibility data, then feel free to follow up on this issue with minimal sample code that demonstrates the problem. If you wish to report a bug with Firefox itself, then I suggest you report the problem at https://bugzilla.mozilla.org/. Thank you!
