### ISSUE TITLE
javascript.builtins.Date.now - Is not supported on IE 10

### ISSUE THREAD

**Issue by yasarsid** [mdn/browser-compat-data#8760]
Date.now is not supported in desktop version of IE10 (version 1909, OS Build 18363.1256)

#### What information was incorrect, unhelpful, or incomplete?
Date.now is marked as supported in IE10

#### What did you expect to see?
Date.now is not supported in IE10

#### Did you test this? If so, how?
I check this via console - attaching screenshot below
![image](https://user-images.githubusercontent.com/16225376/104681090-87d9e300-5717-11eb-896c-bd8f566abe92.png)

![image](https://user-images.githubusercontent.com/16225376/104681112-9627ff00-5717-11eb-949c-1e00d20a2bc3.png)

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Date.now`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now
* Report started: 2021-01-15T04:18:49.956Z

</details>

**Comment by ddbeck** [comment]
Hi @yasarsid and thanks for reporting this issue.

Unfortunately, I think you may have misunderstood what the data refers to here. This feature reports the support for `Date.now()`, rather than a (hypothetical) method of all constructed `Date` instances (i.e., `Date.prototype.now()`).

But to be sure, I checked that `Date.now()` works in IE 9 and later. I can confirm that, from IE 9, `Date.now()` works as expected (though `(new Date()).now()` does not, also as expected).

While this hasn't resulted in any changes to the data, we did confirm that this data point is correct. I'll be closing this issue now. Thank you!
