### ISSUE TITLE
css.properties.inset - supported in Safari TP

### ISSUE THREAD

**Issue by jpzwarte** [mdn/browser-compat-data#8805]
#### What information was incorrect, unhelpful, or incomplete?

https://caniuse.com/mdn-css_properties_inset shows no support at all for Safari. But from testing just now, it works fine in Safari TP: Release 118 (Safari 14.1, WebKit 16611.1.9.3.1).

#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?
Release 75: https://developer.apple.com/safari/technology-preview/release-notes/

**Comment by ddbeck** [comment]
Hi @jpzwarte and thanks for reporting this issue.

Unfortunately, we can't track Safari Technology Preview releases in BCD yet, since it hasn't been practical for us to map TP versions to regular Safari versions. See https://github.com/mdn/browser-compat-data/pull/8103#issuecomment-759330072 for a little more detail.

We can proceed with this when a non-TP Safari beta or general release appears with this feature, giving us a proper version number to enter. In the meantime, I'm going to label this blocked. If/when we can move ahead on this, I'd welcome a follow up (or PR against [`inset.json`](https://github.com/mdn/browser-compat-data/blob/master/css/properties/inset.json)). Thank you again!

**Comment by vinyldarkscratch** [comment]
This was included in the Safari 14.1 release, which is expressed in the changes from #10129!
