### ISSUE TITLE
api.ServiceWorkerGlobalScope.skipWaiting - Safari support

### ISSUE THREAD

**Issue by bdenhollander** [mdn/browser-compat-data#8811]
#### What information was incorrect, unhelpful, or incomplete?
`skipWaiting()` and `Clients.claim()` are listed as unsupported in Safari.

#### What did you expect to see?
[Is ServiceWorker ready?](https://jakearchibald.github.io/isserviceworkerready/#self.skipwaiting()) linked in See also says they were added in 11.1

#### Did you test this? If so, how?
No

<details>
<summary>MDN page report details</summary>

* Query: `api.ServiceWorkerGlobalScope.skipWaiting`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/skipWaiting
* Report started: 2021-01-20T19:26:40.068Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @bdenhollander.

> [Is ServiceWorker ready?](https://jakearchibald.github.io/isserviceworkerready/#self.skipwaiting()) linked in See also says they were added in 11.1

This appears to be correct. This matches up with the timeline suggested by https://bugs.webkit.org/show_bug.cgi?id=180329, too, since `skipWaiting` was implemented shortly after the release of Safari 11.

To fix this, I'd welcome a PR from you or another contributor that sets the Safari (11.1) and Safari for iOS (11.3) values in [`ServiceWorkerGlobalScope.json`](https://github.com/mdn/browser-compat-data/blob/master/api/ServiceWorkerGlobalScope.json#L1621). Thanks again!

**Comment by bdenhollander** [comment]
@ddbeck PR created. Is there a way to confirm whether `Clients.claim()` was also added in those versions?

https://developer.mozilla.org/en-US/docs/Web/API/Clients/claim

**Comment by ddbeck** [comment]
@bdenhollander sorry, I forgot to follow up on that piece. I tested it and it looks like the entire `Clients` API shipped in 11.1/11.3. I'd welcome a PR for that too!

**Comment by ddbeck** [comment]
I merged #8937 which fixes the `api.ServiceWorkerGlobalScope.skipWaiting` data. I decided to leave this open for `claim`.
