### ISSUE TITLE
css.properties.backdrop-filter - <backdrop-filter is not working on the firefox developer edition>

### ISSUE THREAD

**Issue by Noushad-ablore** [mdn/browser-compat-data#8828]
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.backdrop-filter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter
* Report started: 2021-01-22T14:13:53.074Z

</details>

**Comment by ddbeck** [comment]
Since the issue body questionnaire wasn't completed, I'm assuming that this issue was opened in error and I'm closing it. If you'd like us to reconsider this issue, please edit the issue description, completing all of the questions, and post a follow-up comment to request reconsideration. Thank you.
