### ISSUE TITLE
css.properties.position - <fixed>

### ISSUE THREAD

**Issue by ItsNikkiZeng** [mdn/browser-compat-data#8859]
#### What information was incorrect, unhelpful, or incomplete?

元素会被移出正常文档流，并不为元素预留空间，而是通过指定元素相对于屏幕视口（viewport）的位置来指定元素位置。元素的位置在屏幕滚动时不会改变。打印时，元素会出现在的每页的固定位置。fixed 属性会创建新的层叠上下文。当元素祖先的 transform, perspective 或 filter 属性非 none 时，容器由视口改为该祖先。

above translate information  incomplete ,in English doc has initial block but in this translate no any word about that

#### What did you expect to see?
here is the  adding
该元素会被移出正常文档流，并不为其预留空间,它相对于由视口建立的初始包含块定位,除非该元素的祖先元素存在值非 none 的 transform，perspective或filter属性(详情见 CSS Transforms Spec),在这种情况下，该元素的祖先元素将作为包含块,也就是该元素为参照这个祖先元素定位(注意:各浏览器的渲染视图不一,导致包含块形成不一致).
(额外tips:任何非 none 的 transform ,perspective, filter值,都会导致一个堆叠上下文（Stacking Context）和包含块（Containing Block）的创建。由于堆叠上下文的创建，该元素会影响其子元素的固定定位。设置了 position:fixed 的子元素将不会基于 viewport 定位，而是基于这个父元素)

#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.position`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/position
* Report started: 2021-01-26T02:17:58.004Z

</details>

**Comment by vinyldarkscratch** [comment]
Hi there, this repository is for the Browser Compatibility Data, rather than the content of the pages.  Please file an issue at https://github.com/mdn/content instead.

(Google Translate): こんにちは。このリポジトリは、ページのコンテンツではなく、Browser Compatibility Data（ブラウザの互換性データ）用です。 代わりに、https://github.com/mdn/contentで問題を報告してください。
