### ISSUE TITLE
css.properties.gap.flex_context - flex gap doesn't work on iOS 14.4

### ISSUE THREAD

**Issue by buondevid** [mdn/browser-compat-data#8907]
Hi, my iPhone OS version is 14.4, Mobile Chrome version is 87.0.4280.77.

Gap in flexbox doesn't work, it shows correctly on the inspector (device view) on my Macbook Chrome, but when I actually run the website on the mobile it just doesn't work; had to put margins to items to overcome it.

Thanks

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.gap.flex_context`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/gap
* Report started: 2021-01-30T19:24:55.415Z

</details>

**Comment by vinyldarkscratch** [comment]
Hi there, looking at the compatibility tables on the webpage, it looks like Safari on macOS and iOS/iPadOS doesn't support this property in flex contexts -- so yes, this is expected behavior, unfortunately.  On iOS/iPadOS devices, the browser engine will always be Safari regardless of the app you're using, so for iOS and iPadOS devices, you'll want to refer to the "Safari iOS" column.

Hope this helps!

**Comment by buondevid** [comment]
Oh my bad, didn’t know the engine is always safari even when using chrome app! Thanks :)

**Comment by vinyldarkscratch** [comment]
Happy to help!  It seems that not many know about the Safari engine being tied directly to the OS and the restriction against other browser engines -- we've talked about renaming the column to just "iOS" (see #4833) to help reduce said confusion.
