### ISSUE TITLE
javascript.builtins.Number.toLocaleString - Android Chrome locales not available

### ISSUE THREAD

**Issue by CaptainCrucial** [mdn/browser-compat-data#8922]
Tested on Android 9; Chrome 88.0.4324.93

#### What information was incorrect, unhelpful, or incomplete?
toLocaleString does not apply locale formatting on Android Chrome with OS setup in English (British). MDN shows locale formatting available since v26

`(Math.PI * 1000000).toLocaleString('de-DE') = 3,141,592.654 (UK Format)`

Behaviour suggests the only locale formatting data available on the browser is based on the os language

#### What did you expect to see?

`(Math.PI * 1000000).toLocaleString('de-DE') = 3.141.592,654 (DE Format)`

#### Did you test this? If so, how?
Issue can be replicated on the docs page on MDN, running the example
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Number.toLocaleString`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString
* Report started: 2021-02-01T14:45:14.280Z

</details>

**Comment by CaptainCrucial** [comment]
Same thing affects `Intl.NumberFormat` on Android and can be replicated on MDN page's demo
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat

**Comment by CaptainCrucial** [comment]
See also https://bugs.chromium.org/p/chromium/issues/detail?id=1171671

**Comment by ddbeck** [comment]
Thanks for reporting this issue, @CaptainCrucial.

Reading the Chromium bug, it appears that this has hot fixed in Chrome 88. Since the issue appeared in and was fixed in the same release, I think this bug will ultimately be short-lived enough that a note about the bug won't be of interest to web developers in a matter of days. With that in mind, I don't think we should take any further action on the data here.

That said, if this persists as an issue, please follow up and I can revisit this decision.

Thank you again!

**Comment by ddbeck** [comment]
Oh for the record, I followed the linked bug to the bug it was merged into: https://bugs.chromium.org/p/chromium/issues/detail?id=1169034, where it's been reported that the bug is fixed.
