### ISSUE TITLE
api.RTCIceCandidateStats.relayProtocol - Supported in Chrome ≤88

### ISSUE THREAD

**Issue by sopinon** [mdn/browser-compat-data#8928]
#### What information was incorrect, unhelpful, or incomplete?
At least current Chrome Version (88) supports this property.

#### What did you expect to see?
A green check mark for Chrome.

#### Did you test this? If so, how?
Yes, by checking stats, during WebRtc connection. Only tested Chrome.

<details>
<summary>MDN page report details</summary>

* Query: `api.RTCIceCandidateStats.relayProtocol`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidateStats/relayProtocol
* Report started: 2021-02-02T05:00:07.863Z

</details>

**Comment by ddbeck** [comment]
Hi @sopinon and thanks for reporting this issue.

Related issues: https://github.com/mdn/browser-compat-data/issues/6879 (the organization of RTC stats) and https://github.com/mdn/browser-compat-data/issues/7287 (whether we should even record dictionaries).

Unfortunately, the data for WebRTC is rather messy, in part because of its actual standardization history. This dictionary is no exception. It's somewhat difficult to follow when a specific property might've first shipped in Chrome (though some evidence in Chrome Platform Status points toward stats standardization appearing on or after Chrome 58).

As a partial fix, I'd welcome a PR from you or another contributor that sets [`RTCIceCandidateStats` in `RTCIceCandidateStats.json`](https://github.com/mdn/browser-compat-data/blob/master/api/RTCIceCandidateStats.json) to `true` for Chrome (and Edge and Opera) and sets the descendant features to `null` (or, if tested in a current browser version, `true`).

To truly fix this, with correct version numbers, we would need a test case to run through different versions of Chrome to verify each property's existence. Given the other open questions about the organization of RTC data and whether we ought to even record such dictionaries, I'd advise against putting in significant effort on this until the other questions are resolved.

Thank you again!

**Comment by queengooborg** [comment]
The related file has been removed and the feature is no longer tracked in BCD it seems, so I'm going to go ahead and close this issue.
