### ISSUE TITLE
api.MediaDevices.enumerateDevices - Firefox Android 85, enumerateDevices only return audioinput, missing videoinput

### ISSUE THREAD

**Issue by hdnndh** [mdn/browser-compat-data#9053]
#### What information was incorrect, unhelpful, or incomplete?
MediaDevices.getUserMedia does prompt for permission, after permission granted, no longer request access to camera.
MediaDevices.enumerateDevices only showing "0": audioinput

#### What did you expect to see?
On Firefox Android 68 and other test cases on the same device, MediaDevices.getUserMedia would ask for sharing input:
"Would you like to share your camera and microphone with <site>, Video Source: <>, Microphone to use: <>"
MediaDevices.enumerateDevices shows both audioinput and videoinputs

#### Did you test this? If so, how?
Same piece of code working well on Firefox Android 68, any other Chrome Android, Firefox desktop 85.
Already using the newest adapter.js.

<details>
<summary>MDN page report details</summary>

* Query: `api.MediaDevices.enumerateDevices`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices
* Report started: 2021-02-10T15:11:14.957Z

</details>

**Comment by hdnndh** [comment]
Is this a change/breaking change in Firefox Android?

**Comment by ddbeck** [comment]
Hi @hdnndh. Thanks for reporting this. Unfortunately, I wasn't able to reproduce your problem, since it's rather awkward to test old versions of Firefox for Android. Firefox for Android underwent significant changes from version 68 to 79 (there were no releases between them), so it's possible there was a significant change in behavior.

For clarity, do I understand correctly that, according to your test of Firefox for Android 68, `enumerateDevices` did not list video inputs, but did list audio inputs?

Apart from testing, I did go looking for any evidence of bugs being reported related to your issue. This was the closest I found and it might be of interest to you https://bugzilla.mozilla.org/show_bug.cgi?id=1566118.

Unfortunately, since it's difficult for me to substantiate this information directly, next steps will be limited. If you're able to reproduce this problem in, for example, Firefox for Android 67 or earlier, then we could probably compose a note indicating the the pre-79 versions of Firefox for Android have this discrepancy. If you're unable to do such testing, then I'm inclined to let this fact stand, since it's largely a historical note already, concerning a version of Firefox approaching two years old.

If you are inclined to test, I'd welcome screenshots, sample code, and the like, to help confirm the details.

Incidentally, I did notice a problem in the way the current `enumerateDevices` data is presented on MDN and opened #9225.

Thank you!

**Comment by hdnndh** [comment]
Hello @ddbeck , thanks for reaching out.

> For clarity, do I understand correctly that, according to your test of Firefox for Android 68, `enumerateDevices` did not list video inputs, but did list audio inputs?
Yea. So on my local device, I have both video and audio input physically available, and even with the permission setup, the mentioned behavior happened.
It is a compound problem that happen to both getUserMedia and enumerateDevices, so I think there could be something with either Firefox not expose videoinput for security reasons. about:config on Firefox Android was gone too so I could not check that.
There were 2 cry for help on Stackoverflow and maybe 1 issue found on github when I went through the rabit hole trying to find out if it is my code, but none were answered. People will just claim to either getUserMedia first, or set permission, which I did both.


> Unfortunately, since it's difficult for me to substantiate this information directly, next steps will be limited. If you're able to reproduce this problem in, for example, Firefox for Android 67 or earlier, then we could probably compose a note indicating the the pre-79 versions of Firefox for Android have this discrepancy.

Sure I can spend some time in a few weeks to test this out. I am curious as well. I will be using below snippet in my test for 
`if (navigator.mediaDevices.getUserMedia) 
        {
            navigator.mediaDevices.getUserMedia(constraints)
                .then(....`
I want to know if I spend time to do the test, would this be categorized as a bug, and will there be a fix in one of the future releases of Firefox Android? It does feels like a bug, and Chrome Android/Desktop and Firefox Desktop still handle the exact same code normally.

**Comment by ddbeck** [comment]
> I want to know if I spend time to do the test, would this be categorized as a bug or some kind of issue, and will there be a fix/clarification explicit in one of the future releases of Firefox Android? It does feels like a bug/unintentional behavior, and Chrome Android/Desktop and Firefox Desktop still handle the exact same code normally.

Oh, I'm sorry. To clarify, this repository is to record data about support for web platform features across different browsers, which drives the compatibility tables on MDN (and other tools). This project is not part of Firefox engineering at all and we don't forward bug reports to them.

This is probably a good point to mention: if this problem persists in the latest version of Firefox for Android, then I'd strongly recommend that you report a bug to https://github.com/mozilla-mobile/fenix. Being able to mention a filed bug makes it _much_ easier to represent this information.

If it's a strictly historical—if the problem only appears in older Firefox for Android versions—then they're unlikely to be of much help to you, however. In that case, we'd need to document the relevant details in this issue, then summarize it in a note in the data.

**Comment by jculver050** [comment]
Close

**Comment by jculver050** [comment]
Close
