### ISSUE TITLE
api.Window.postMessage - Not working in the Chrome 74 and 75 version but working fine in the 72 version

### ISSUE THREAD

**Issue by kamesh2111** [mdn/browser-compat-data#9073]
if i reload the page postmessage is not working in the some chrome version (74, 75) (Sometimes it's working sometimes it's not). But working fine in the 72 version. Even i have added 40 seconds timeout. but still no luck

Parent:

```
var win;
if(win == null || win == undefined)
  win = document.getElementById("displayFrame").contentWindow;
if(win != null){
  win.postMessage(JSON.stringify(data), "*"); 
  console.log("pushed success eventtype: "+ JSON.stringify(data) );                 
}
```

Child:
tried both
```
if (window.addEventListener) {
  window.addEventListener('message', this.receiveMessage.bind(this), false);
} else {
 (window as any).attachEvent('onmessage', this.receiveMessage.bind(this));
}
```

```
@HostListener('window:message', ['$event'])
onMessage(event) {
  console.log("OnMessage event in the custom app");
  this.receiveMessage(event);
}
```

**Comment by ddbeck** [comment]
Hi @kamesh2111. Thanks for reporting this issue. Unfortunately, I was unable to reproduce any problems with `postMessage` (nor any difference of behavior between Chrome 72 and 75). Looking at your sample code, I suspect the problem may lie with some library (for example, whatever is providing `receiveMessage`, which is not familiar to me) or your compiler (since you don't appear to be using plain JavaScript). Best of luck tracking down your bug. In the mean time, thank you for reporting your issues with the data and giving us this opportunity to confirm its correctness.
