### ISSUE TITLE
css.properties.custom-property - not supporting images in Safari

### ISSUE THREAD

**Issue by alokjain-lucky** [mdn/browser-compat-data#9075]
If I use image URLs in CSS variables, they are not working in Safari (This works fine in Chrome and Firefox)

Tested in Safari Version 14.0.3 (16610.4.3.1.4)
macOS Big Sur Version 11.2.1 

```
:root {
    --download-icon: url('../img/download.png');
}

@media (prefers-color-scheme: dark) {
    :root {
        --download-icon: url('../img/download_white.png');
    }
}

.document-link {
    background: var(--download-icon) no-repeat center;
}
```

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.custom-property`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties
* Report started: 2021-02-12T10:13:32.342Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this issue, @alokjain-lucky.

I was able to find a couple of WebKit bugs reporting the same problem:

https://bugs.webkit.org/show_bug.cgi?id=190807
https://bugs.webkit.org/show_bug.cgi?id=198512

There's also [changeset 267951](https://trac.webkit.org/changeset/267951/webkit), which shows that this has been fixed in WebKit. I expect an upcoming release of Safari will include this fix, but so far it is unresolved.

The changeset itself hints at a summary of the problem: shorthands containing `url()` and CSS variable(s)
resolve the `url()` relative to the document root instead of the the stylesheet. I'll open a PR to add a note to Safari about this.

Thank you, again!
