### ISSUE TITLE
api.Console.trace - it is added in firefox 6

### ISSUE THREAD

**Issue by smalllong** [mdn/browser-compat-data#9119]
#### What information was incorrect, unhelpful, or incomplete?
The table shows it is added in firefox 10

#### What did you expect to see?
According to https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/6 it is added in firefox 6

#### Did you test this? If so, how?
Tested it on my machine in firefox 6.0.2

<details>
<summary>MDN page report details</summary>

* Query: `api.Console.trace`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Console/trace
* Report started: 2021-02-14T13:58:30.106Z

</details>

**Comment by Elchi3** [comment]
Hey, thanks for filing this issue!

Just for my own research, can you comment on why it matters to you whether it is Firefox 6 or Firefox 10? 
Most of the users probably don't worry much about versions that date back so far, so your issue is interesting :) Did you run into an issue with an old Firefox? Do you use old browsers for some reason and discovered this issue then? Thanks in advance!

**Comment by ddbeck** [comment]
Apart from the motivation here (which would be really interesting to know!): to correct this data, I'd welcome a PR (from you or another contributor) that sets the correct value for Firefox (both of them seems likely) in [`Console.json`](https://github.com/mdn/browser-compat-data/blob/master/api/Console.json#L1470-L1475). Thank you!

**Comment by lucalves** [comment]
Hello @smalllong, how are you? If you could tell us the motivation it would be important, but anyway, I opened a PR #9446 to correct this.

**Comment by smalllong** [comment]
Hi all, I'm just learning new web technologies through checking firefox release notes one by one. It's true that seldom people are using old firefox nowadays. But people on old and low performance machines it's still make sense for them to use an old version browser
