### ISSUE TITLE
Alphabetic sorting and mixins

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#9126]
A while ago we made it so that all features need to be added in alphabetically. The build fails if you don't sort correctly. 

Mixins are exposed to the BCD tree slightly differently using the `api/_mixins` folder. While the files themselves are also sorted strictly alphabetically, they get loaded to their target interfaces at a later time and so the features they expose aren't sorted in alphabetically but rather appended at the end.

I'm not aware of BCD consumers that care about this except for the largest consumer, MDN, which choses to display large tables with feature trees. MDN could sort features for their tables, but doesn't do so currently. See https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement#browser_compatibility where the mixed in features come last.

Does BCD need to sort in mixins alphabetically? I believe ES6 made it so that you can order objects now. So, this might be fixable on the BCD side? Or is it a problem the consumers ought to take care of?

**Comment by ddbeck** [comment]
My take on this is: if we want to provide some canonical traversal order for BCD, then we should do that with an API we can control, rather than contorting ourselves around insertion order.

ES6 objects have an order, but it's insertion order plus the catch that if a key can be parsed as an integer, then that takes precedence in the order. It's a weird order and some parts of the language, such as `for … in`, were not specified as respecting that order until later (though I think most implementations did it anyway before that). That's a long way of saying: it'd be a bit weird for BCD to guarantee an order that it can't completely control.

Moreover, I think that our tree is a collection of objects and not arrays suggests to our consumers that the order is, well, not to be trusted. That it happens to have a sensible insertion order is a happy accident.

(This also suggests something funny about releases in our browser schema. Maybe we should order those as an array since the order does matter!)

If we wanted to offer a useful order to consumers, I think it'd be nice to do that as an explicit part of the package that we can version and change. One way to do that would be to change the schema and use arrays to order the tree (no, thank you). Another would be to offer a traversal API (e.g.. some generator `walk('api.whatever', {depth: 1})`) that can yield features in a guaranteed order.

**Comment by Elchi3** [comment]
The _mixin folder was removed. https://github.com/mdn/browser-compat-data/issues/17024
