### ISSUE TITLE
api.Navigator.clipboard - IE support

### ISSUE THREAD

**Issue by DavidFransch** [mdn/browser-compat-data#9138]
#### What information was incorrect, unhelpful, or incomplete?
Browser Compatibility for the clipboard API should be updated
#### What did you expect to see?
This API is compatible with IE
https://caniuse.com/clipboard
#### Did you test this? If so, how?
I've tested it with this version,
https://internet-explorer-for-mac.en.softonic.com/mac/download 

<details>
<summary>MDN page report details</summary>

* Query: `api.Navigator.clipboard`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard
* Report started: 2021-02-16T11:06:37.216Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @DavidFransch.

As best as I can tell, the data on caniuse refers to the [`document.execCommand()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) way of interacting with the clipboard. IE does support it and our data reflects that.

The page that originated this report refers to the asynchronous `navigator.clipboard` API. I can't find any evidence that IE supported it (or any implementation of Promise-based APIs, since it never implemented Promise itself).

Taken together, I think this issue can be closed. That said, if you think this is in error, please comment here with some sample code that demonstrates support and we can investigate further.

Thank you again!
