### ISSUE TITLE
api.HTMLImageElement.referrerPolicy - iOS Safari doesn't implement this feature

### ISSUE THREAD

**Issue by macabeus** [mdn/browser-compat-data#9145]
#### What information was incorrect, unhelpful, or incomplete?

iOS Safari doesn't implement this feature.

#### What did you expect to see?

Show not send request `Referer` data.

#### Did you test this? If so, how?

Yes. [Testing using my iPhone.](https://www.browserstack.com/guide/how-to-debug-on-iphone)

![image](https://user-images.githubusercontent.com/9501115/108118272-036fdc80-7096-11eb-8cd6-b036f14fd75c.png)

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLImageElement.referrerPolicy`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/referrerPolicy
* Report started: 2021-02-16T20:12:31.096Z

</details>

**Comment by test-ci-linh** [comment]
StopVon meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Bruno Macabeus <notifications@github.com> Datum: 16.02.21  21:32  (GMT+01:00) An: mdn/browser-compat-data <browser-compat-data@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: [mdn/browser-compat-data] api.HTMLImageElement.referrerPolicy - iOS Safari doesn't implement this feature (#9145) 

What information was incorrect, unhelpful, or incomplete?
iOS Safari doesn't implement this feature.
What did you expect to see?
Show not send request Referer data.
Did you test this? If so, how?
Yes. Testing using my iPhone.



MDN page report details

Query: api.HTMLImageElement.referrerPolicy
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/referrerPolicy
Report started: 2021-02-16T20:12:31.096Z



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mdn/browser-compat-data/issues/9145",
"url": "https://github.com/mdn/browser-compat-data/issues/9145",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by test-ci-linh** [comment]
Stop pleas

M.GEHRMANN

marcusgehrmann112 <marcusgehrmann112@gmail.com> schrieb am Di., 16. Feb.
2021, 22:23:

**Comment by ddbeck** [comment]
Hi @macabeus, I was able to confirm that Safari for iOS supports both:

- the `referrerPolicy` DOM attribute (reflecting the element attribute)
- the `<img>` element's `referrerpolicy` attribute (as documented on MDN [`<img>` element page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-referrerpolicy)), respecting the `no-referrer` and `origin` values

Since I wasn't able to reproduce your problem, I suspect the issue may be related to your project or environment specifically.

If you still think this data is incorrect, please feel free to follow up with minimal, reproducible example code and we can go from there. Thank you!
