### ISSUE TITLE
javascript.builtins.decodeURI - <PUT TITLE HERE>

### ISSUE THREAD

**Issue by arezookhrirabedi** [mdn/browser-compat-data#9302]
it doesn't work to me

 decodeURI('https://sandbox.varmi.net/api%E2%80%8B/v1%E2%80%8B/admin%E2%80%8B/landing%E2%80%8B/62')

export const servic=()=>{
return ApiCaller({needToken: true}).get(
 decodeURI('https://sandbox.varmi.net/api%E2%80%8B/v1%E2%80%8B/admin%E2%80%8B/landing%E2%80%8B/62'))
}

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.decodeURI`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI
* Report started: 2021-03-01T03:53:45.249Z

</details>

**Comment by vinyldarkscratch** [comment]
This sounds more like an issue with the other parts of your code rather than with the `decodeURI()` function.  The function is so old that it'd be pretty surprising to see it not working in any modern browser (in fact, I tested it real quick with no issues).  Unfortunately, this repository isn't for providing such code assistance -- for that, I would recommend checking the troubleshooting guide or forums of whatever library is defining that `ApiCaller`, or asking StackOverflow.
