### ISSUE TITLE
api.Element.touchend_event - Safari support needs review

### ISSUE THREAD

**Issue by AnkitJainAJ** [mdn/browser-compat-data#9314]
#### What information was incorrect, unhelpful, or incomplete?
Safari does support this.

#### Did you test this? If so, how?
I tested in virtual device provided by lambdatest

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.touchend_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/touchend_event
* Report started: 2021-03-02T11:39:08.149Z

</details>

**Comment by ddbeck** [comment]
Hi @AnkitJainAJ and thanks for opening this issue.

You mentioned that you tested this. If you could provide a minimal test case with sample code (such as on Codepen), then we could verify this, confirm version numbers, and update the corresponding data.

Ultimately, these features will need to be updated to reflect what we learn:

https://github.com/mdn/browser-compat-data/blob/7bf68abb9b601526887cb9cba392e6d8b24752f1/api/Element.json#L8574
https://github.com/mdn/browser-compat-data/blob/a77c55eb4ad8e352cda07a1519e38e305dc80857/api/Document.json#L11092

**Comment by queengooborg** [comment]
I'm going to close this because there has been no actionable information.  It's unclear whether "Safari" refers to Safari _Desktop_ or Safari on _iOS/iPadOS_, but in the extensive testing I've done around this event, I've only found support in iOS/iPadOS, so I think that our current data is accurate.

If you've found support in Safari Desktop, please feel free to reply to this thread and I'll happily reopen the issue!
