### ISSUE TITLE
svg.attributes.presentation.stop-opacity - missing features in compatibility table

### ISSUE THREAD

**Issue by Havegum** [mdn/browser-compat-data#9402]
#### What information was incorrect, unhelpful, or incomplete?
The compatibility table is incomplete. Specifically, that iOS Safari does not accept `<percentage>` as a value:
> This value is either a `<number>` between 0 and 1 or a `<percentage>` value specifying the opacity of the color gradient stop.

#### What did you expect to see?
A row in the compatibility table, or a note on the iOS Safari block that warns using `<percentage>` as a value will not work on iOS Safari.

#### Did you test this? If so, how?
Tested in Browserstack on iPhone 8 on Safari. The stop-opacity attributes with `<percentage>` values are ignored and the default opacity, 1, is used.

`<number>` values work as expected.

<details>
<summary>MDN page report details</summary>

* Query: `svg.attributes.presentation.stop-opacity`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stop-opacity
* Report started: 2021-03-09T12:01:48.646Z

</details>

**Comment by ddbeck** [comment]
@Havegum Thank you, that's very helpful!

I was able to reproduce the results of your screenshot in iOS 11, 12, and 13, but not before 11 or in iOS 14 (and presumably later).

There remains a question of where to put this data. More soon.

**Comment by ddbeck** [comment]
@Elchi3 I can't believe it's taken me this long to notice, but there's two places where SVG attributes can appear in BCD: as features like `svg.attributes.<category>.<attribute>` and as features like `svg.elements.<element>.<attribute>`. Can you explain the distinction between these two ways of arranging data?

In this case, there's some rather complete data for `svg.elements.stop` and its attributes as subfeatures. Meanwhile, there's incomplete data for the seemingly-equivalent `svg.attributes.presentation.{stop-color,stop-opacity}`. I'm not sure if I should fix both, or just one and drop the other (and, if so, which one is which).

**Comment by Elchi3** [comment]
This is from the time when BCD just imported everything from MDN without thinking further about structures.
The MDN SVG docs pages are these
- https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stop-opacity
- https://developer.mozilla.org/en-US/docs/Web/SVG/Element/stop 

I'm not sure how useful the SVG attribute reference is but apparently it is useful to have dedicated docs for attributes. See also https://github.com/mdn/content/issues/1712 which proposes to do the same for HTML.

In BCD, we should avoid having two data points, though. I'm leaning towards only keeping the svg.elements.stop data.

**Comment by ddbeck** [comment]
@Elchi3 Thank you! That's really helpful. This suggests the right thing to do with SVG might be to closely follow HTML, with a `global_attributes.json` for attributes that apply to many elements and record data for individual elements with the elements themselves. I've opened #9462 to propose that.

**Comment by ddbeck** [comment]
@Havegum OK, we've now got a decent idea for how to move this forward. Here's what I'd suggest:

1. You (or another contributor) opens a PR in this repository to update this entry:

    https://github.com/mdn/browser-compat-data/blob/2084025a3264621792d82cc5f76f397bf9727335/svg/elements/stop.json#L175-L177

   replacing it with an array of two support statements: the first showing `version_added: "3"` and `version_removed: "11"` and a second showing `version_added: "14"`.

   At the same time, we'd remove this entire feature:

   https://github.com/mdn/browser-compat-data/blob/2084025a3264621792d82cc5f76f397bf9727335/svg/attributes/presentation.json#L2213-L2260

2. You (or another contributor) opens a PR on mdn/content to update the reference to the BCD feature for the page where you originally discovered this problem:
    
     https://github.com/mdn/content/blob/f91eadfd12dced6194561e610a180694175b52bf/files/en-us/web/svg/attribute/stop-opacity/index.html#L67-L69

That would fix this up nicely, I think. If you're interested in making these changes, I'd be more than happy to review (and assist with any difficulties). Otherwise, we can let someone else take this one—it might make a good first issue for someone.

**Comment by Havegum** [comment]
Like so? 😅

**Comment by ddbeck** [comment]
#9468 and https://github.com/mdn/content/pull/3156 have been merged, so this is now fixed. Thanks again! 🚀
