### ISSUE TITLE
Issue with "Spread syntax (...)": should it be rest in destructuring?

### ISSUE THREAD

**Issue by arturcarvalho** [mdn/browser-compat-data#9457]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

Hi there,

On the browser compatibility table for the spread syntax, it is mentioned "spread destructuring". Shouldn't it be "rest destructuring" or something along those lines? [Initial discussion](https://twitter.com/rauschma/status/1369932326172524544?s=20).

The error when the syntax is with the wrong order also hints at that:

<img width="395" alt="image" src="https://user-images.githubusercontent.com/2487710/110771930-5aaf3a00-825b-11eb-94fe-c8deadb6082a.png">

Thanks and have a nice day!

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/spread_syntax`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/spread_syntax/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by ddbeck** [comment]
Interesting find. Thanks for reporting this, @arturcarvalho!

I think the problem here is that we've duplicated the data for this syntax:

- incorrectly as [`javascript.operators.spread.spread_in_destructuring`](https://github.com/mdn/browser-compat-data/blob/5e7ff0a7194088756dedebb561d776abaf7ed03d/javascript/operators/spread.json#L131)
- correctly (and in more detail) as [`javascript.operators.destructuring.rest_in_arrays`](https://github.com/mdn/browser-compat-data/blob/4ee5bb9468593a786527a4a658759428e1ec7304/javascript/operators/destructuring.json#L109) and [`javascript.operators.destructuring.rest_in_objects`](https://github.com/mdn/browser-compat-data/blob/4ee5bb9468593a786527a4a658759428e1ec7304/javascript/operators/destructuring.json#L171) ([as seen on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#browser_compatibility))

If I've understood correctly, then the fix here would be to delete [the spread feature](https://github.com/mdn/browser-compat-data/blob/5e7ff0a7194088756dedebb561d776abaf7ed03d/javascript/operators/spread.json#L131-L181). I'd welcome a PR (from you or another contributor) making this change.

**Comment by arturcarvalho** [comment]
Hi @ddbeck, thanks for the reply!

Exactly, deleting would make the table correct. I can send a PR. 
Would it suffice to delete that part you mentioned on the JSON file ` browser-compat-data/javascript/operators/spread.json`? 
It looks like a generated file.

Have a nice day.

**Comment by ddbeck** [comment]
@arturcarvalho That's correct. Our data files aren't actually generated (though we do a fair amount of automation against them)—think of them as very structured writing. 😃

**Comment by arturcarvalho** [comment]
> @arturcarvalho That's correct. Our data files aren't actually generated (though we do a fair amount of automation against them)—think of them as very structured writing. 😃

I laughed out loud with the `very structured writing` 😄 

I'll send a PR after work. Thanks for the reply.
