### ISSUE TITLE
javascript.statements.import - Outdated regarding Node.js

### ISSUE THREAD

**Issue by robsch** [mdn/browser-compat-data#9460]
#### What information was incorrect, unhelpful, or incomplete?
"From version 12.0.0: this feature is behind the--experimental-modules runtime flag."
Still true until version 14.x.

#### What did you expect to see?
It should be mentioned that from version 15 that flag isn't required anymore, since it is now stable.

<details>
<summary>MDN page report details</summary>

* Query: `javascript.statements.import`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
* Report started: 2021-03-15T10:20:25.366Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @robsch! The data is confusing here, as the flag is not required since 13.2.0 (see [this announcement](https://nodejs.medium.com/announcing-core-node-js-support-for-ecmascript-modules-c5d6dc29b663) and #5644), but the data about older versions makes it appear that this continues to be true. I've opened #9463 to fix this.

**Comment by robsch** [comment]
Ok, glad to know that reporting here seems to be the right way. Wasn't sure about that.
