### ISSUE TITLE
api.Element.classList.replace - Feature duplicates api.DOMTokenList.replace

### ISSUE THREAD

**Issue by yuriyvyatkin** [mdn/browser-compat-data#9526]
#### What information was incorrect, unhelpful, or incomplete?
The browser compatibility table indicates that Safari and Samsung Internet do not support the replace() method.

#### What did you expect to see?
Updated compatibility information.

#### Did you test this? If so, how?
Page https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/replace includes the opposite information.

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.classList`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/classList
* Report started: 2021-03-21T01:20:22.413Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this, @yuriyvyatkin.

Since `Element.classList` returns a `DOMTokenList`, we ought to let `DOMTokenList` be authoritative, rather than partially covering the API under. To avoid the confusing and incomplete duplication, we ought to remove the duplicates:

- `api.Element.classList.add_and_remove_multiple_arguments`
- `api.Element.classList.replace`
- `api.Element.classList.toggle_method_second_argument`

All of this data is better represented in the `api.DOMTokenList` tree.

The data affected is here:

https://github.com/mdn/browser-compat-data/blob/d61696555037f2a20020fea925c665d10e0f7d4c/api/Element.json#L1418-L1668

I've opened a PR to remove the data and fix this issue in #10128.

**Comment by yuriyvyatkin** [comment]
Thank you, @ddbeck.
