### ISSUE TITLE
api.Console - Substitution strings

### ISSUE THREAD

**Issue by Riclim** [mdn/browser-compat-data#9597]
#### What information was incorrect, unhelpful, or incomplete?
Browser compatibility table: "Substitution strings" appears in 6 different lines without further information about what functionality they refer to.
#### What did you expect to see?
What features of "Substitution strings" are supported or not.
#### Did you test this? If so, how?

<details>
<summary>MDN page report details</summary>

* Query: `api.Console`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Console
* Report started: 2021-03-24T21:14:35.895Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this issue, @Riclim.

The "Substitution strings" features you see are actually subfeatures of preceding entries in the table. For example, the first one is a subfeature of `debug()`. This is more obvious and documented on [the page for the individual `debug()` method](https://developer.mozilla.org/en-US/docs/Web/API/Console/debug).

Unfortunately, that the table is not clear about the parentage of features is a known issue. It's tracked in https://github.com/mdn/yari/issues/3321. Since we already have an issue for that, I'm going to close this issue.

Thank you again for calling attention to this problem!
