### ISSUE TITLE
Firefox for Android 79+ doesn't support flags

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#9679]
Like #4753 and #7354, Firefox for Android 79+ (Fenix) doesn't appear to ship access to flags / preferences in general releases. That is, `about: config` doesn't do anything in Firefox for Android.

We ought to close any open support statements with flags with a `"version_removed": "79"`, or report `"version_added": false` for such features added at 79 or later.

This would not appear to apply to Firefox for Android version 69 and earlier (i.e., Fennec).

**Comment by hamishwillee** [comment]
"for such features added at 79 or later." > "for such features present in 79 or later."

And perhaps generate that automatically as part of testing.

**Comment by hamishwillee** [comment]
@ddbeck Do we need to be concerned that Fenix might one day provide said access to preferences in a later version? i.e. that we might lose information about those cases where android doesn't support a feature for other reasons.

**Comment by ddbeck** [comment]
No, I don't think we need to worry about it. I think that would be a true discontinuity and we'd need to represent it as separate support statements. For example, suppose there's some long-lived flag that was supported before 79. If Fenix were to support flags from version 99, then we'd need two support statements to show support from X to 79 and from 99 onward.

I suspect the right way to track this sort detail is by an addition to the schema, where we record, per release (not per-browser), whether flags are supported. Then should Firefox for Android ever reintroduces flags, there's a coherent way to permit them back into the Firefox for Android data only for those releases.

**Comment by jculver050** [comment]
Close

**Comment by saschanaz** [comment]
Per GitHub search: [Firefox Nightly has supported prefs since 2019](https://github.com/mozilla-mobile/fenix/pull/5569) (that's before version 79) and [also beta since version 90](https://github.com/mozilla-mobile/fenix/pull/20275).

**Comment by ddbeck** [comment]
That's right. The main point here is that the flags would only be correct for values which are `"preview"`, not a specific numbered stable release.

**Comment by Elchi3** [comment]
Leaving my comment from https://github.com/mdn/browser-compat-data/pull/15678#pullrequestreview-936319162 here as well:

> A side affect for making an exception to the 2 year rule that I didn't think about before  is that if you make different rules for different browsers when to remove irrelevant flags, well then you end up with flags removed for Firefox Android but not for Firefox Desktop with the same version. That looks odd. 

> We should either not make an exception to the two year rule or we should treat Firefox Desktop with the same exception... 

Now:

```
            "firefox": [
              {
                "version_added": "80"
              },
              {
                "version_added": "63",
                "version_removed": "79",
                "flags": [
                  {
                    "type": "preference",
                    "name": "dom.animations-api.compositing.enabled",
                    "value_to_set": "true"
                  }
                ]
              }
            ],
            "firefox_android": [
              {
                "version_added": "80"
              },
              {
                "version_added": "63",
                "version_removed": "79",
                "flags": [
                  {
                    "type": "preference",
                    "name": "dom.animations-api.compositing.enabled",
                    "value_to_set": "true"
                  }
                ]
              }
            ],
```

With the removal of just Firefox Android flags:

```
            "firefox": [
              {
                "version_added": "80"
              },
              {
                "version_added": "63",
                "version_removed": "79",
                "flags": [
                  {
                    "type": "preference",
                    "name": "dom.animations-api.compositing.enabled",
                    "value_to_set": "true"
                  }
                ]
              }
            ],
            "firefox_android": {
              "version_added": "80"
            },
```

Given Vinyl opened a lot of PRs for Firefox Android flag removal, I suppose we should agree on removing Firefox Desktop flags also slightly earlier for the releases until version 79, too. It looks quite inconsistent otherwise between Firefox mobile and desktop imo.

**Comment by Elchi3** [comment]
I saw @foolip merged the PRs that remove Firefox Android flags. Has my above comment been taken into consideration?

**Comment by queengooborg** [comment]
Definitely -- I plan to follow up to remove the same flag data for Firefox desktop, so there's no discrepancies between the two!

**Comment by foolip** [comment]
I didn't read this issue before reviewing/merging those PRs, so we now have lots of cases where Firefox desktop has flag data but Firefox Android does not. There were some cases where this seemed unfortunate to me, in particular where some note was tweaked and mechanically stripping the flag data from desktop wouldn't result in two matching entries. Those will need attention when removing the remaining flag data, and doing that soon rather than waiting a few years would be good, while we still remember why the notes are different.

**Comment by Elchi3** [comment]
Can you
- analyze if this issue should be closed? That is, is the Firefox Android 79+ data now free of flags?
- open a new issue that analyzes the issue you've introduced now? That is, the unfortunate discrepancies between Firefox Android and Firefox flags prior to desktop version 79.

Thanks.

**Comment by foolip** [comment]
> is the Firefox Android 79+ data now free of flags?

Since the end state is going to be no flag data at all for Firefox Android, I tried this change to see what flag data remains:

```diff
--- a/browsers/firefox_android.json
+++ b/browsers/firefox_android.json
@@ -2,7 +2,7 @@
   "browsers": {
     "firefox_android": {
       "name": "Firefox for Android",
-      "pref_url": "about:config",
+      "accepts_flags": false,
       "releases": {
         "4": {
           "release_date": "2011-03-29",
```

With some additional filtering I can say that *no*, all flag data isn't removed for Firefox Android 79+ yet.

@queengooborg do you have open PRs for everything?

As for the discrepancies, won't we be left with these whatever we do? There are plenty of flags introduced before 79 that still aren't enabled by default, and those can't be removed from the desktop data any time soon. But leaving those entries with `"version_removed": "79"` in the Android data also doesn't achieve consistency.

The consistency that could be achieved is for features that have been enabled by default since 79, and that would be good to do. @queengooborg can you file an issue / write a script?

**Comment by foolip** [comment]
I've sent https://github.com/mdn/browser-compat-data/pull/15900 to remove some of the easy cases I found.
