### ISSUE TITLE
http.headers.Feature-Policy - new "browsing-topics" permission

### ISSUE THREAD

**Issue by dmarti** [mdn/browser-compat-data#9814]
#### What information was incorrect, unhelpful, or incomplete?

"interest-cohort" permission appears to be missing

#### What did you expect to see?

Mention which browsers may use  "interest-cohort" (More info at: https://github.com/mdn/yari/issues/3159 )

#### Did you test this? If so, how?

Visited cohort test site at: https://floc.glitch.me/

<details>
<summary>MDN page report details</summary>

* Query: `http.headers.Feature-Policy`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy
* Report started: 2021-04-09T19:30:10.188Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this issue, @dmarti. This is an interesting case!

To record this data, I'd welcome a PR (from you or another contributor) adding the header to [`feature-policy.json`](https://github.com/mdn/browser-compat-data/blob/main/http/headers/feature-policy.json). Because our schema doesn't capture origin trials right now, the feature would likely be represented as all `"version_added": false` values, with a note for Chrome along the lines of, "Federated Learning of Cohorts is in a Chrome origin trial. This policy affects only those versions of Chrome which may implement the origin trial." and perhaps including a link to the relevant Chrome Platform Status entry.

I'd also add that this is somewhat related to https://github.com/mdn/browser-compat-data/issues/10619. There's a little bit of uncertainty about how we record data for future or speculative features (for example, we don't generally record origin trials because of their transient nature). You can learn more about that problem in the linked issue, but I expect we'll settle on a policy that permits high-interest features in development, which this is certainly one. I wouldn't let that stop you from opening a PR, though the outcome of that discussion may prompt some changes in the final PR.

**Comment by bershanskiy** [comment]
Please note the following:
- `interest-cohort` directive has been removed from Chromium together with FLoC (actually, only Google Chrome really ever supported it; apparently, there was a significant controversy over this).
- FLoC was released as an Origin Trial to a 
- there were [plans/rumors](https://github.com/patcg-individual-drafts/topics) that `interest-cohort` would also control Topics API (successor to FLoC), but no actual implementation ever manifested. For details please refer to https://github.com/GoogleChrome/developer.chrome.com/pull/2297 .

Considering the above points, I suggest we close this issue without change to BCD since `interest-cohort` is irrelevant in practice (although it does not fit [BCD description of "irrelevant feature"](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#removal-of-irrelevant-features)).

**Comment by dmarti** [comment]
The `interest-cohort` permission does affect Topics API, which is currently available as part of a Google Chrome origin trial.

https://github.com/patcg-individual-drafts/topics/pull/70#issuecomment-1135146204=

The new permission is `browsing-topics`

**Comment by MichaIng** [comment]
I'm confused, so `interest-cohort` is used again by Chrome and relevant to block FLoC but more importantly the new Topics API? And `browsing-topics` affects the Topic API as well/the same way?

Or did https://github.com/GoogleChrome/developer.chrome.com/pull/2297 finally remove `interest-cohort`?

**Comment by dmarti** [comment]
@MichaIng The `interest-cohort` permission (originally implemented for Google FLoC) is still recognized as an opt out for Topics API by Google Chrome: https://github.com/patcg-individual-drafts/topics/pull/70

The `browsing-topics` permission applies only to Topics API: https://github.com/patcg-individual-drafts/topics#specific-details

According to Google, Topics API will be made available to all Google Chrome users by the second half of 2023: https://developer.chrome.com/en/blog/expanding-privacy-sandbox-testing-2023/

**Comment by MichaIng** [comment]
Thanks for explaining. And FLoC was removed already ~1 year ago from Chrome(ium) code? Just wondering whether only `browsing-topics` should be used nowadays or whether additionally using `interest-cohort` for a while still makes sense, or even only the latter as long as if affects Tocpics API as well.

It is quite hard to find reliable information about all of this online. There are blog posts from 2023 explaining FLoC as "the new thing", as if it at least was still in use.

Sorry for abusing this issue for my questions. Probably collecting this information here at least helps anyone who finds time to implement the permissions properly into MDN. It is the source I trust most about such topics, when choosing security headers, but currently there is a gap on these 🙂.

**Comment by dmarti** [comment]
On recent versions of Google Chrome,  `interest-cohort` does the same thing as `browsing-topics`. Only some origin trial versions of the browser recognized `interest-cohort`.

**Comment by dmarti** [comment]
(correction: recognized `interest-cohort` _only_, or implemented FLoC)

**Comment by MichaIng** [comment]
Okay, means setting `browsing-topics` is the right thing nowadays.

**Comment by queengooborg** [comment]
It appears that this feature will be shipping in the upcoming release of Chrome, if https://chromestatus.com/feature/5680923054964736 is to believe.  Is there a good way to test and confirm support for this feature?
