### ISSUE TITLE
Missing data: `::-webkit-details-marker`

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#9869]
According to this note, `::-webkit-details-marker` exists:

https://github.com/mdn/browser-compat-data/blob/cd6fbfee6af5265b60f950a56fb60a423b00493d/html/elements/summary.json#L58

But we don't actually have a feature entry for this. Rather than reporting on its status via a note on an HTML element, we ought to create a new feature (presumably `css.selectors.-webkit.details.marker`) and populate it with some useful data.

Inspired by #9809.

**Comment by ddbeck** [comment]
Here's a test case:

```html
<html>
  <head>
    <title>css.properties.-webkit-details-marker</title>
    <style>
      summary::-webkit-details-marker {
        display: none;
        margin-inline-end: 0;
      }
    </style>
  </head>
  <body>
    <details>
      <summary>This should not have a marker</summary>
      Here are the details.
    </details>
  </body>
</html>
```

**Comment by ddbeck** [comment]
It works in Safari, but I'm not sure how far back. It works in Chrome up to and including 88, but not 89, and I'm not sure how far back.

**Comment by Baptistou** [comment]
This pseudo-element seems to exist since at least Safari 6 (2012) and Chrome 27 (2013).
I found some resources that might help.

- Webkit
`::-webkit-details-marker` (2012) : https://bugs.webkit.org/show_bug.cgi?id=84557
`list-style` for `<summary>` (2016) https://bugs.webkit.org/show_bug.cgi?id=157323
`display: list-item` by default for `<summary>` (2020) : https://lists.webkit.org/pipermail/webkit-dev/2020-September/031397.html
- Chromium/Chrome
`::-webkit-details-marker` (2013) : https://bugs.chromium.org/p/chromium/issues/detail?id=218341
`::marker` pseudo-element (2015) : https://bugs.chromium.org/p/chromium/issues/detail?id=457718
`::marker` for `<summary>` (2016) : https://bugs.chromium.org/p/chromium/issues/detail?id=590014
`::-webkit-details-marker` deprecated (2021) : https://chromestatus.com/feature/6730096436051968#details
- Firefox
`::marker` pseudo-element (2003) https://bugzilla.mozilla.org/show_bug.cgi?id=205202

**Comment by ddbeck** [comment]
Thank you for the extra details, @Baptistou! This helps narrows things down from the testing I did. I've opened #10013 to resolve this.
