### ISSUE TITLE
It doesn't work, now the Thai accent hasn't arrived, what should I do?

### ISSUE THREAD

**Issue by aomlovebank1212** [mdn/browser-compat-data#9901]
speaktotext() async {
var u = new SpeechSynthesisUtterance();
u.lang = 'th-TH';
u.text = '50 บาท';
window.speechSynthesis.speak(u);
It doesn't work, now the Thai accent hasn't arrived, what should I do?
in flutter web

**Comment by vinyldarkscratch** [comment]
This sounds like a web development assistance request, rather than an issue with BCD.  Please note that this repository is not designed to answer questions around development help -- for that, I would recommend online forums like StackOverflow.

If I've closed this issue in error, feel free to write a response.
