### ISSUE TITLE
api.Element.animate - <endDelay not working on ios 14.4.2>

### ISSUE THREAD

**Issue by ziya5635** [mdn/browser-compat-data#9902]
Hi, endDelay feature is not working on safari and chrome on IOS 14.4.2. not tested Mozilla.
#### What did you expect to see?
I have built a slideshow (sequence of animations) presenting few images. It works perfectly on all web browsers, but not on mobiles.
I just figured out that only when endDelay feature is removed from the first animation, the onFinish method is triggered causing the next animation starts otherwise it doesn't work.

#### Did you test this? If so, how?
tested recently on my own Iphone.

<details>
<summary>MDN page report details</summary>

* Query: `api.Element.animate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/animate
* Report started: 2021-04-18T07:25:38.036Z

</details>

**Comment by ziya5635** [comment]
Ok, seems safari is not supporting this feature. The table is not saying anything about Chrome on ios though.

**Comment by queengooborg** [comment]
I can't find any data for the `endDelay` feature anywhere in either MDN web docs or here in BCD, so I'm not sure what data needs updating.  Maybe we've since removed the feature?  I'm not able to find the removal commit for this, hmm...

Can you provide an example of your code so we can dig further into this?

> The table is not saying anything about Chrome on ios though.

Chrome on iOS is actually just Safari with a different UI -- same goes for any browser on iOS!  As such, we don't keep separate compat columns for other iOS browsers.  😛

**Comment by queengooborg** [comment]
Closing the issue since there hasn't been any response, and it appears the feature was removed in #12765.
