### ISSUE TITLE
padStart Node.JS

### ISSUE THREAD

**Issue by TotallyInformation** [mdn/browser-compat-data#999]
Hi, this is my first time trying to update this data so please forgive me if I'm not doing it right.

I note on MDN that the browser data for padStart is missing for Node.JS

I can confirm, however, that v8.9.4 certainly supports `String.prototype.padStart()`

I'm afraid that I don't know the earliest version however. According to http://node.green/, it required the "harmony" flag until after 7.10.1. So I think the earliest full support was 8.0.0.

**Comment by Elchi3** [comment]
Hi, thanks for looking into this!
It was already fixed in https://github.com/mdn/browser-compat-data/pull/938 and the pages are updated now:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padEnd#Browser_compatibility

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart#Browser_compatibility
